### DISCUSSION TITLE
Basic 'scrollbar appearance' properties setable via userChrome.css/userContent.css

### DISCUSSION THREAD

**Discussion by happysurf** [Aris-t2/CustomCSSforFx#456] [General]
Now is possible change the scrollbar colors and width in userContent.css  without any script.
Look this interesting discussion on Reddit:
https://www.reddit.com/r/FirefoxCSS/comments/98j1a7/psa_you_can_change_scrollbar_properties_directly/
This is the result:

![scroolbar](https://user-images.githubusercontent.com/13637587/47872782-c40f1a80-de0f-11e8-92f6-3a6adcdb7338.png)

```css

:root{
  scrollbar-face-color: rgb(210,210,210); /* Firefox 63 compatibility */
  scrollbar-track-color: rgb(46,54,69); /* Firefox 63 compatibility */
  scrollbar-color: rgb(210,210,210) rgb(46,54,69);
  scrollbar-width: thin;
}
```

**Comment by Aris-t2** [comment]
Thanks for the note. Looks interesting.

References:
https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-color
```css
/* Keyword values */
scrollbar-color: auto;
scrollbar-color: dark;
scrollbar-color: light;

/* <color> values */
scrollbar-color: rebeccapurple green;   /* Two valid colors. 
The first applies to the thumb of the scrollbar, the second to the face. */

/* Global values */
scrollbar-track-color: inherit;
scrollbar-track-color: initial;
scrollbar-track-color: unset;
```

https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-width
```css

/* Keyword values */
scrollbar-width: auto;
scrollbar-width: thin;
scrollbar-width: none;

/* <length> values */
scrollbar-width: 1em;   /* A valid length */

/* Global values */
scrollbar-width: inherit;
scrollbar-width: initial;
scrollbar-width: unset;
```

**Comment by happysurf** [comment]
I don't understand because in some web pages,  no scrollbars appear with the new code.

Try:
https://www.netvibes.com/bibrouen#Litterature (after click dismiss)
https://www.liberoquotidiano.it/

Firefox 64beta with this code:

```css
/* Thin Scrollbar */
:root{
  scrollbar-color: rgb(210,210,210) rgb(46,54,69) !important;
  scrollbar-width: thin !important;
}
```
