### DISCUSSION TITLE
vertical centering of text  on tabs

### DISCUSSION THREAD

**Discussion by rebop** [Aris-t2/CustomCSSforFx#491] [Q&A] [answered]
Just a small one, but the tab text is closer to the bottom than top of the tab. Any place to change padding to get it vertically centered? Using Classic Square tabs and tabs at the bottom of the browser.

Thanks.

**Comment by Aris-t2** [comment, marked as answer]
You are right, tab text needs to move up a few px.

This did a good job in my tests:

```css
.tab-label-container {
  padding-bottom: 2px !important
}
```
