### DISCUSSION TITLE
Separate tab close button and new tab button

### DISCUSSION THREAD

**Discussion by plomari** [Aris-t2/CustomCSSforFx#540] [Ideas]
I'd like to have a tab close button on the very right of the tab bar. (In most configurations, it would be directly below the application menu button in the toolbar.) Tabs themselves shouldn't have a close button.

You can do this with the Close Tab Button extension (1.0.0), which stopped working properly in Firefox 108. I also tried the Close Window Button extension (1.0.2), which is linked from a CustomCSSforFx page, but it doesn't work either. In both cases, no button is visible. Strangely, the buttons are visible if you enter Customize Toolbar mode.

Would it be possible to add this button to this project directly, to make it easier for users?

**Comment by Aris-t2** [comment]
I'm sorry, but CSS can not create (new) buttons.

**Comment by Aris-t2** [comment]
"New tab" button does already exist, so we can make it visible all the time and hide the "new tab" tab:

```css
#tabbrowser-tabs[hasadjacentnewtabbutton]:not([overflow="true"]) ~ #new-tab-button,
#tabbrowser-tabs[overflow="true"] > #tabbrowser-arrowscrollbox > #tabbrowser-arrowscrollbox-periphery > #tabs-newtab-button,
#tabbrowser-tabs:not([hasadjacentnewtabbutton]) > #tabbrowser-arrowscrollbox > #tabbrowser-arrowscrollbox-periphery > #tabs-newtab-button,
#TabsToolbar[customizing="true"] #tabs-newtab-button {
  display: unset !important;
}

#tabs-newtab-button {
  display: none !important;
}
```
