### DISCUSSION TITLE
Unified Extensions button and menu

### DISCUSSION THREAD

**Discussion by Speravir** [Aris-t2/CustomCSSforFx#547] [General]
Aside from the symbol I noticed something some minutes ago in [General questions and feedback](https://github.com/Aris-t2/CustomCSSforFx/discussions/454#discussioncomment-4742487) there is another thing I want to change, but was not successful until now.

The popup menu is too narrow for German language users:
![2023-01-21 00_56_38-unified-extensions](https://user-images.githubusercontent.com/899244/213826943-c1d82d5b-1fd9-4728-a23e-01698b7915e5.png)

It should get a width in a way that the second, smaller text is on one line only. As said I was not successful until now, but noticed that there is a new style

```css
#unified-extensions-panel toolbaritem.unified-extensions-item {
	max-width: max-content;
}
```
When I add there some `width` the whole menu will be affected, but not the items themselves. Also, in my special case with a custom scrollbar (by your userscript) I would presumingly have to add some calculation into the styling for preserving scrollbar space.

**Comment by Aris-t2** [comment]
Have you tried this:

```css
.unified-extensions-item-name,
.unified-extensions-item-message {
  width: unset !important;
}
```

![image](https://user-images.githubusercontent.com/6013569/213882301-db55564d-e2ac-464f-8008-c5b6258043bd.png)

**Comment by Speravir** [comment]
> Have you tried this:

No I had not, because I had not discovered these classes in this complex DOM stack or complex of complex stacks.

But now the gear symbol is not aligned anymore, see this:
![2023-01-22 01_44_09-Unified Extensions button and menu](https://user-images.githubusercontent.com/899244/213896115-4f9326e0-e149-4a64-bb39-174ad1f4ad59.png)

Note the three different texts. Needs apparently some flex or grid setting (or relative positioning?), but I was not yet successful here, too, with any of these variations.

… Oh, is it possible that I spotted a bug in Firefox here? In `unified-extensions.css` I see a rule
```css
/* Align extensions rendered with custom elements. */
unified-extensions-item {
  display: flex;
  align-items: center;
}
```
But there is no element `unified-extensions-item`, but a class `.unified-extensions-item` (which is in the next rule inside the style file). Does not help me, though: After applying to this calls the sub elements still are not flexible.


Do you consider this useful for more people than me, so it could be added into CSSforFx?

**Reply by Aris-t2** [reply]
It is not a bug, the rule actually gets applied to an element they called like this, although that element hat a class of the same name. Probably WIP or leftover.
![image](https://user-images.githubusercontent.com/6013569/213913092-d692423c-fe37-4764-9226-c8e4e0531fb5.png)


Looking through the code and content structure of that popup seems like a total mess to me. They will change code there in the near future for sure a few times.

--------------------------

The only clean way to get around the misalignment in my tests and keeping text in a single like was increasing the default value to `28em` (for German locale, French, Greed, Italian might need higher values):

```css
.unified-extensions-item-name,
.unified-extensions-item-message {
  width: 28em !important;
}
```

![image](https://user-images.githubusercontent.com/6013569/213913214-4e0d622d-a52e-45d5-b8e1-3c1f963a11c5.png)

**Reply by Speravir** [reply]
> It is not a bug, the rule actually gets applied to an element they called like this, although that element hat a class of the same name.

Ah, I did not find this. It was not displayed here while searching for it, strange.

> Looking through the code and content structure of that popup seems like a total mess to me.

You name it.

> They will change code there in the near future for sure a few times.

So, better not adding to CssforFx?
 
> The only clean way to get around the misalignment in my tests and keeping text in a single like was increasing the default value to `28em` (for German locale, French, Greed, Italian might need higher values):

Thanks, or 👍👍. But, ha, I had independently another idea: I saw some variables in several levels of this conglomerate:
```
--panel-width
--menu-panel-width
--menu-panel-width-wide
```
The latter has a value of 29em, so this could be used in CSSforFx, at least it works for me to set the width to the latter variable. With a value of 28em it looks better in German, though, you are right. But then I had the idea to change the variable for the element on the next upper level:

```css
.unified-extensions-item-contents {
	--menu-panel-width: 28em !important;
}
.unified-extensions-item-name,
.unified-extensions-item-message {
  width: var(--menu-panel-width) !important;
}
```
I will use this for now.

Edit: Thinking again about it, this is not better than your solution.

**Reply by Aris-t2** [reply]
> So, better not adding to CssforFx?

I did add it to recent 4.2.9vX builds for popups compact mode. Makes sense there imo.

**Comment by Speravir** [comment]
Citing [myself](../discussions/457#discussioncomment-4742739):
> The button can be made movable with a userscript

Inside of the nav-bar it is actually also possible with CSS alone:
```css
#unified-extensions-button {
  -moz-box-ordinal-group: 0 !important;
}
```
moves it to the very left (in settings with ltr languages, I do not know for the others).

If you want to have it in another position you must assign `-moz-box-ordinal-group` with increasing numbers to _all_ buttons in the nav-bar – and (I did not test this) presumingly also include the addressbar itself, or exactly the `#urlbar-container`.

And very probably also absolute positioning is possible, similar like for the appmenu panel  button (“hamburger menu“), cf. [`appbutton_in_titlebar.css`](../blob/master/current/css/appbutton/appbutton_in_titlebar.css).

**Comment by Acid-Crash** [comment]
Hi here,
I am having the similar issue with the narrow popup for my native locale.
I tried to reduce font size + added layer mask for the extension names.
Here is the code if someone is interested.

```css

.unified-extensions-item-contents .unified-extensions-item-message {
  font-size: 10px !important;
  width: 26em !important;
}

.unified-extensions-item-contents .unified-extensions-item-message, .unified-extensions-item-contents .unified-extensions-item-name {
  white-space: nowrap;
  mask-image: linear-gradient(to left, transparent, black .5em);
}


```
