### DISCUSSION TITLE
Border around main page content missing

### DISCUSSION THREAD

**Discussion by gazecube** [Aris-t2/CustomCSSforFx#574] [Q&A] [answered]
So, I'm on Windows 7, and old versions of FF have a border around the main content to highlight the page when Aero is applied. I can't find any setting to restore this behaviour. Is there any way to get the border back?

FF18:
![image](https://user-images.githubusercontent.com/33785843/225513132-e1c57026-bf78-4a48-9749-d1fe8bf334b0.png)
FF111 with userstyle applied:
![image](https://user-images.githubusercontent.com/33785843/225513161-bab7d83d-af46-47ad-b09d-3b8a24826ca0.png)

**Comment by Aris-t2** [comment, marked as answer]
You can add a border using this:

```css
#appcontent {
  border: 1px solid grey !important;
}
```

**Reply by gazecube** [reply]
Would it also be possible to get that border on the side of the location bar?

**Reply by Aris-t2** [reply]
Sure:

```css
#nav-bar {
  border-left: 1px solid grey !important;
  border-right: 1px solid grey !important;
}
```
