### DISCUSSION TITLE
OS' native tab design?

### DISCUSSION THREAD

**Discussion by gazecube** [Aris-t2/CustomCSSforFx#575] [Ideas]
I'm trying to emulate Firefox 1.x but the tabs on those ancient releases use the OS' native tab design. I feel like this would be good for users trying to get the look of those even earlier browsers.

**Comment by Aris-t2** [comment]
Even, if this would work (like it did in the past), you would get different results requiring individual tweaking on every OS.

```css
.tabbrowser-tab {
  appearance: auto !important;
  -moz-default-appearance: tab !important;
}
```

In the past this did restore OS default tabs:

```css
.tabbrowser-tab {
  -moz-appearance: tab !important;
}
```
