### DISCUSSION TITLE
Is it possible to suppress the tab label on Pinned tabs?

### DISCUSSION THREAD

**Discussion by sshipway** [Aris-t2/CustomCSSforFx#580] [General]
I have a few pinned tabs, and want these to show only the icon so they take up less space.  This was working a long time back but Ive since upgraded many things and it has broken.

To do this I've tried making the pinned tabs smaller with this:
```
.tabbrowser-tab[pinned] {
padding-left: 10px;
padding-right: 10px;
width: 40px;
}
```

however I've not worked out how to hide the text on the tab and so it still tries to show.  Does anyone know what I should do to make this work?

**Comment by Aris-t2** [comment]
If you need to modify pinned tabs like in your example, this code will hide the appearing label:

```css
.tabbrowser-tab[pinned] {
  padding-left: 10px;
  padding-right: 10px;
  width: 40px;
}

.tabbrowser-tab[pinned] .tab-label-container {
  display: none;
}
```
