### DISCUSSION TITLE
Setting background colour for tabs bar and New Tab button

### DISCUSSION THREAD

**Discussion by sshipway** [Aris-t2/CustomCSSforFx#581] [General]
After upgrading, the background of the tabs bar is now #ffffff where I previously wanted it to be #cccccc (the same colour as the menubar).  In addition, the "New Tab" button is now showing about half the size it should be.

What CSS should I set to control the background of the Tabs bar (not the background of the tabs themselves, but the empty space)?  Is there a setting I can use to increase the size of the New Tab button?

**Comment by Aris-t2** [comment]
Are these general questions or specific for this projects tab configurations?

This code will change tab toolbars background color:

```css
#TabsToolbar {
  background: yellow;
}
```

This will increase tab width:

```css
#tabs-newtab-button {
  width: 100px !important;
}
```
