### DISCUSSION TITLE
Firefox V133 system color no longer shown at top

### DISCUSSION THREAD

**Discussion by rw330i** [Aris-t2/CustomCSSforFx#707] [General]
Is this something that can be fixed via CSS? All of the gray at the top now really irritates me. I appologize if I may have posted this in the wrong area. Thank you.
Richard

**Comment by Aris-t2** [comment]
It still is possible to get accent colors on Fx 133+:

![image](https://github.com/user-attachments/assets/5f816846-0ccf-4f67-95ee-e8497193a335)
![image](https://github.com/user-attachments/assets/5f718ffd-de6a-43a2-9f20-a160791b5ebb)



`about:config` > `browser.theme.windows.accent-color-in-tabs.enabled` > `true`

`userChrome.css` or `my_userChrome.css`

```css
#main-window {
  appearance: auto !important;
  -moz-default-appearance: -moz-win-borderless-glass !important;
}
```
