### ISSUE TITLE
[TAB MAX WIDTH] - tabs resizing issue when closing tabs

### ISSUE THREAD

**Issue by kilara1988** [Aris-t2/CustomCSSforFx#100]
1. Describe the issue

When i use "tab_maxwidth.css" to set a maxWidth to the tabs a glitch is introduced.
Open enough tabs so that your tabs start shrinking below the maxWidth value(or even go into tab overflow).
Now start closing tabs from the left side(3rd tab or later) with middle mouse click without moving the mouse.
While you are closing the tabs, as soon as you exit tab overflow your tabs width starts increasing until the maxWidth value is reached.
This leads to your mouse at some point being over a tab from the left group which you didn't want to close.You have to constantly adjust your mouse position if you are closing tabs rapidly.

2. What should have happened instead?

Without "tab_maxwidth.css" enabled closing tabs with middle mouse click does not change the tab width until the mouse moves.This allows us to close rapidly tabs to the right of our mouse since no width change occurs until we move our mouse.

3. Steps to reproduce the issue?

Open enough tabs so that your tabs start shrinking below the maxWidth value(or even go into tab overflow).
Now start closing tabs from the left side(3rd tab or later) with middle mouse click without moving the mouse.
While you are closing the tabs, as soon as you exit tab overflow your tabs width starts increasing until the maxWidth value is reached.

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)

5. System information
- OS & OS version: Win 10 1709
- OS theme name: 
- DPI / HiDPI resolution: 
- Firefox version: 57.0.4
- Firefox theme / lw-theme: default
- This projects settings the issue occurs with: tab_maxwidth.css

**Comment by Aris-t2** [comment]
The only way to achieve this feature without JavaScript was using this code:

```css
.tabbrowser-tab[fadein]:not([pinned]) { 
  max-width: 250px !important;
  overflow: hidden;
}
```

Everything else visually broke tabs toolbar and was not suitable at all. TMP and CTR achieved tabs maximum width differently, but only with the help of JavaScript what is not part of this project.

If someone finds a better solution, I will include it.

**Comment by Aris-t2** [comment]
Looks like there is finally a solution available for this:

```css
.tabbrowser-tab:not([pinned]) {
  min-width: 200px !important;
  min-width: 200px !important;
}

#tabbrowser-tabs:not([overflow="true"]):not([using-closing-tabs-spacer="true"]) .tabbrowser-tab[fadein]:not([pinned]) {
  max-width: 400px !important;
  overflow: hidden !important;
}
```

The fix will be added on next update.
