### ISSUE TITLE
[FIREFOX 58] - some @media rules get ignored [but work fine Firefox 57 and 59]

### ISSUE THREAD

**Issue by Aris-t2** [Aris-t2/CustomCSSforFx#101]
Firefox 58 (release, beta, Nightly) ignores code as shown in this example

```css
@media (-moz-os-version: windows-win7) {
  toolbar {
    background: red !important;
  }
}

@media (-moz-os-version: windows-win10) {
  toolbar {
    background: blue !important;
  }
}
```

Some of this projects features rely on correct OS or theme detection resulting in not applying any code part of these @media rules when loaded through userChrome.css/userContent.css.

- @media (-moz-os-version: windows-win7)
- @media (-moz-os-version: windows-win8)
- @media (-moz-os-version: windows-win10)
- @media (-moz-windows-classic)
- @media (-moz-windows-default-theme)
- @media (-moz-windows-theme:aero)

A filed bug report can be found here: https://bugzilla.mozilla.org/show_bug.cgi?id=1431933

I can confirm the issue is not present in Firefox 59 beta. I suggest to skip Firefox 58 and directly go to **[59 beta 3+](http://ftp.mozilla.org/pub/firefox/candidates/)**, if you are affected by this issue.

This bug might not get fixed, because a developers answer to another "userChrome" issue was 
> We won't fix issues that only occur when using a userChrome.css change.

https://bugzilla.mozilla.org/show_bug.cgi?id=1400542#c1

-------------------------

EDIT
This projects version 1.5.8 contains additional fixed files for Firefox 58. They have to be enabled manually depending on the options used.

-------------------------

EDIT (2018-03-08)
After Firefox 59 release this project will drop support for Firefox 58 (57 should still work fine, but why use it?).

**Comment by MarkRH** [comment]
Interesting. I am on 58 now and using v1.5.0 of your files and everything appears the same as it did with 57 (Windows 7 Pro with Classic skin).  I'll probably leave it as is.  Anyway, thanks for your work.  My current config is here: http://www.markheadrick.com/firefox/firefox_config.php#appearance

**Comment by Aris-t2** [comment]
Only some features broke or cause glitches.

Windows Classic Theme
- classic bookmarks button popups background color 
- appbutton in titlebar + maximized mode
- tabs below navigation toolbar > background/border colors
- context menu labels position
- icons+text / text modes > button appearance

Windows 10
- squared tabs > caption buttons
- tabs below navigation toolbar > top toolbar position

**Comment by motfis** [comment]
actually it is not bug from your css. I tested it without the css, still the same.
Can you make the back button _gray out_ when there is no more previous page? because now it always shows the same color/icon regardless it can be click or not.

**Comment by Aris-t2** [comment]
```css
#back-button[disabled] {
  opacity: 0.5 !important;
  filter: grayscale(100%) !important;
}
```
