### ISSUE TITLE
[OLD SEARCH SUPPORT THREAD] - 'search bar' / 'search textbox' known from older browser builds 

### ISSUE THREAD

**Issue by Aris-t2** [Aris-t2/CustomCSSforFx#104]
# **Due to code changes in Firefox, the old search does not work anymore in Firefox 64+!**

The **old search**, one of "Classic Theme Restorers" main features, is back and works fine on Firefox 57-63.

Files required (included in full package): [oldsearch.css](https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/css/generalui/oldsearch.css) & [oldsearch.xml](https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/css/generalui/oldsearch.xml)

**New "browser.oldsearch.*" settings are automatically present and do not have to be created manually. Visit 'about:config' page to change them.**
- 'about:config > browser.search.openintab': open search in current or new tab / Boolean
- 'about:config > browser.search.suggest.enabled': search suggestions visibility / Boolean
- 'about:config > browser.oldsearch.customwidth': enables custom popup width / Boolean
- 'about:config > browser.oldsearch.customwidthvalue': custom popup width value / Integer
- 'about:config > browser.oldsearch.clearinput': clear searchbox after search / Boolean
- 'about:config > browser.oldsearch.reverttodefault': revert to first engine after search / Boolean
- _search engines popup and search popup will use search boxes width, if not set otherwise_

![oldsearch60](https://user-images.githubusercontent.com/6013569/40277465-8ed8cb94-5c1f-11e8-820d-7a485ed99dd4.png) ![oldsarch_osx](https://user-images.githubusercontent.com/6013569/36065366-f53f7f64-0e99-11e8-9d5e-b17a8ec35fba.png)

[>>> German discussion thread on Camp Firefox forums](https://www.camp-firefox.de/forum/viewtopic.php?f=16&t=124326)

**Comment by ImSpecial** [comment]
Black magic, thought this wasn't possibly anymore...

Does selecting one of the engines, for example Bing, change it to the new default? I hate how now it keeps one as your default and when you go to search something using a different one it reverts back to the default after the search, it's annoying when you have to do multiple searches and don't want the default one.

**Comment by Aris-t2** [comment]
I had to rewrite a few parts in previous "old search" xml and the last thing (switching engine icon) started to work too. "Old search" was partly possible right from the beginning (Fx57) without being actually ready for every day us due do some stuff not working the way it should.

Yes, changing search engine inside popup permanently switches default search engine.

**Comment by simoncarne** [comment]
I am trying to implement the old search, but I seem to be doing something wrong. 

Before starting out on this change, I had version 1.6.0 as my chrome folder, which works just fine.

I have added the command "@import url(./css/generalui/oldsearch.css);" into userChrome AND copied the oldsearch.css file from version 1.6.6 into my chrome/css/generalui folder.  

When I do the above, the search box vanishes entirely. Is there something additional from v1.6.6 that I need to copy into my chrome folder.

NOTE: I have tried using v1.6.6 in place of my chrome folder and the search box works (in the "old search" format), so my browser is fine. But v1.6.6 means that all my other tailored changes vanish and I would need to re-build the folder. Is there any way I adapt my pre-existing chrome folder to import just this one change?

**Comment by Aris-t2** [comment]
You also need the corresponding xml file and image files.
Note: Always use the full release file while testing.

**Comment by simoncarne** [comment]
Thanks for explaining ... and for responding so quickly. I have everything sorted now.

**Comment by Speravir** [comment]
Wow, I called you awesome for the tab title in title bar, but for this I had to escalate if I could.

Ping: [Alte Suche mit Firefox 57](https://www.camp-firefox.de/forum/viewtopic.php?f=16&t=124326). _(Wäre ein eigener Thread für CustomCSSforFx im Camp Firefox oder auch hier nicht eine gute Idee für Leute, die mit dem Englisch Probleme haben?)_

**Comment by Aris-t2** [comment]
Alright, I have added some info about "Old Search" to your Camp Firefox post.

**Comment by Speravir** [comment]
Hmm, either the behaviour has changed (because of what – the changed _urlbar-bindings.xml_?) or I didn’t really have tested this before: In the [release notes for v. 1.6.6](https://github.com/Aris-t2/CustomCSSforFx/releases/tag/1.6.6) you wrote:
> it is possible to edit searches xml file to enable "revert to default engine after search"

I do **not** want this behaviour, and I did _not_ edit the XML file, but the default search engine it set again after each search – the icon of the engine which I used for the search is still be seen, though, cf. following image:
![20180219-fxscreenshot](https://user-images.githubusercontent.com/899244/36388848-802f3696-159d-11e8-938b-842fbbb4998d.png)
My default engine is [DuckDuckGo](https://duckduckgo.com/), but for the last search I used [MetaGer](https://metager.de/) which icon is still visible. I intentionally cleaned the search box here, but this is not the default for me, because sometimes I want to use the same search query for different engines.

**Comment by Aris-t2** [comment]
The code to revert the search is not active like shown here: https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/xml/oldsearch_fx57.xml#L453

Not all "old search" mechanics work properly. The engine icon gets only updated, if you chose a different engine by selecting it through the searchbar icon.

**Comment by Speravir** [comment]
Oh my gosh, I’m embarrassed! The culprit was either the person in front of my monitor (a.k.a. PEBKAC) or a forgotten user script: [SearchEngineWheelscroll](https://github.com/ardiman/userChrome.js/tree/master/searchenginewheelscroll) (note that I have changed settings). I’d love to delete my posting above but then your answer could be misinterpreted.

**Comment by Aris-t2** [comment]
I can delete that part of our conversation, if you like.

**Comment by Speravir** [comment]
Yes, do it, please. I could delete my own, but not your’s, of course.

**Comment by getreadyforme** [comment]
So when is Mozilla dropping XBL ?

**Comment by getreadyforme** [comment]
So when is Mozilla dropping XBL ?

**Comment by Aris-t2** [comment]
No date was set, but there is always movement in the corresponding bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1397874

**Comment by Speravir** [comment]
_Thank you, Aris, for deleting this embarrassing notices._

**Comment by krystian3w** [comment]
Possible add old search addons in `about:addons` with "**moz-binding**" or works value in `about:config` recover old search?

**Comment by Aris-t2** [comment]
I have not tested this, but my guess is "it is not possible". About:addons is just a page while the search box requires the main ui environment (on a different level). The old search just extends the current search and replaces some parts/methods.
Not sure what the actual purpose would be using the search without about:addons.

**Comment by MarkRH** [comment]
Looks like with Firefox 60 the search bar suggestions don't show?

![image](https://user-images.githubusercontent.com/8035962/39944116-eaf23b6e-552a-11e8-8844-396d6cf7debb.png)

I am using version 1.8.5.1 of the CSS now it's still not working.

**Comment by Aris-t2** [comment]
Right-click inside searchbox and check the bottom of the popup.

![123](https://user-images.githubusercontent.com/6013569/39955589-9c31c40c-55d1-11e8-828d-39b2341d6f09.png)

Works for me up to Firefox 62.

![456](https://user-images.githubusercontent.com/6013569/39955592-a5a056e8-55d1-11e8-9e09-a36426af7276.png)

**Comment by MarkRH** [comment]
Hmm.. that is checked.  My userChrome.css is here: https://www.markheadrick.com/firefox/firefox_config.php#appearance

Guess my next thing to try is a clean profile and see what it does.

**Comment by Aris-t2** [comment]
Maybe, try  disabling a few search engines temporarily. Is search history displayed correctly?

**Comment by MarkRH** [comment]
Yeah, too many search engines was collapsing it. Had to uncheck 4 of them to start seeing something (never realized unchecking them did that LOL).  Anyway, looks like your CSS works with all the engines enabled.
![image](https://user-images.githubusercontent.com/8035962/39961051-dbd26fa4-55f3-11e8-8fc4-3308817a7baa.png)

Thanks.

**Comment by krystian3w** [comment]
Maybe activate scroll for 10+ search engines?

**Comment by Aris-t2** [comment]
This might work indeed.

Try this code:
```css
#PopupSearchAutoComplete .search-one-offs  {
  overflow-y: scroll !important;
}
```

**Comment by MarkRH** [comment]
Either of those works well. I went with:
```css
#PopupSearchAutoComplete .search-one-offs  {
  height: 400px !important;
  max-height: 400px !important;
  overflow-y: scroll !important;
} /**/
```
Which yeilds:
![image](https://user-images.githubusercontent.com/8035962/40089019-4f442284-586f-11e8-93a0-e8756645863a.png)

**Comment by Aris-t2** [comment]
I will add an option for this on next update.

**Comment by StanGets** [comment]
Hi,

I thought I had found an answer for my quest here before but I'm unable to retrieve it... unless I'm mistaking.

What I'd like to do is simple. I use Firefox's "old" search toolbar and I wish to have displayed alongside the search engines' names their keyword, something like this:

![ok](https://user-images.githubusercontent.com/42912760/45919623-8fb35080-be98-11e8-822a-8450e006d281.jpg)

I remember a workaround had been given, but can't get to figure it out. Thanks for help/advice.

**Comment by Aris-t2** [comment]
Now I remember what you meant, but the solution was not for the "old search", it was for the current search, if you enable to use labels instead of icons. Then you could add "keywords"/"shortcuts" manually. But this was only a cosmetic feature. I can't find it on Github within the threads either, but I kept the code. Doint this for old search does not work in case you wanted to ask.

```css

#PopupSearchAutoComplete .search-panel-one-offs .searchbar-engine-one-off-item[tooltiptext*="Google"]::after {
  content: attr(tooltiptext) ' (g)' !important;
}

#PopupSearchAutoComplete .search-panel-one-offs .searchbar-engine-one-off-item[tooltiptext*="Bing"]::after {
  content: attr(tooltiptext) ' (b)' !important;
}

#PopupSearchAutoComplete .search-panel-one-offs .searchbar-engine-one-off-item[tooltiptext*="DuckDuckGo"]::after {
  content: attr(tooltiptext) ' (dd)' !important;
}

#PopupSearchAutoComplete .search-panel-one-offs .searchbar-engine-one-off-item[tooltiptext*="Wikipedia"]::after {
  content: attr(tooltiptext) ' (wi)' !important;
}

#PopupSearchAutoComplete .search-panel-one-offs .searchbar-engine-one-off-item[tooltiptext*="Amazon"]::after {
  content: attr(tooltiptext) ' (a)' !important;
}

#PopupSearchAutoComplete .search-panel-one-offs .searchbar-engine-one-off-item[tooltiptext*="Twitter"]::after {
  content: attr(tooltiptext) ' (t)' !important;
}
```

**Comment by StanGets** [comment]
@Aris-t2 that's exactly what I had in mind, many thanks. I mentioned "old search" by mistake.
I'll add this as I had done before (backing it up should I remove it in the future).
Great, as all of CustomCSSforFx, a haven of styles for a nice & smooth Firefox experience.

**Comment by Aris-t2** [comment]
# **Due to code changes in Firefox, the old search does not work anymore in Firefox 64+!**

**Comment by outrighter** [comment]
Please help me with the code to change the font size of the search tips and the space between them:
![87232b997a9c32422e2a1f9676fef497](https://user-images.githubusercontent.com/44705279/48116104-15873180-e276-11e8-998d-05a59b6122bd.jpg)

**Comment by MarkRH** [comment]
Uhm, what selectors would I need to use to change the font-size of the search suggestions, the Google Search at the top, the "Search for DD with", and "Change search settings" at the bottom?

![image](https://user-images.githubusercontent.com/8035962/48180166-15c01500-e2e8-11e8-99b5-9d38d1d9a8bd.png)

**Comment by Aris-t2** [comment]
I don't have the exact selector, but this code works with '*':

```css
#PopupSearchAutoComplete .search-panel-tree > * > * {
  font-size: 24px !important;
}
```
