### ISSUE TITLE
FF 58.0.2: Make v1.6.8 tab bar look like v.1.5.0 

### ISSUE THREAD

**Issue by MarkRH** [Aris-t2/CustomCSSforFx#108]
1. Describe the issue
Trying the newer 1.6.8 code and trying to get the tab bar to look like I had it with the 1.5.0 code. The tabs are much higher. The 26px height doesn't seem to be taking effect. The grey toolbar color is also a bit off.

2. What should have happened instead?
Look the same.

3. Steps to reproduce the issue?
My current 1.5.0 config: https://www.markheadrick.com/firefox/firefox_config.php#appearance

I modified the top portion as:
```
@import url(./classic/config/general_variables.css); /**/
/* @import url(./classic/config/color_variables.css); /**/  /* <- default 'grey' colors */
@import url(./classic/config/color_variables_classic-grey.css); /**/  /* <- 'classic grey' colors */
@import url(./classic/css/buttons/buttons_on_navbar_classic_appearance.css); /**/
@import url(./classic/css/buttons/icons_colorized.css); /**/
@import url(./classic/css/buttons/bookmarks_menu_button_localized_label_on_bookmarks_toolbar.css); /**/
@import url(./classic/css/buttons/bookmarks_menu_button_popup_classic_appearance.css); /**/
@import url(./classic/css/buttons/appbutton_popup_icons_colorized.css); /**/
@import url(./classic/css/tabs/classic_squared_tabs.css); /**/
/*@import url(./classic/css/tabs/classic_squared_tabs_classic_grey.css); /**/
@import url(./classic/css/tabs/tabs_below_navigation_toolbar.css); /**/
/* @import url(./classic/css/tabs/tabs_below_navigation_toolbar_classic_grey.css); /**/
```

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)
1.5.0:
![image](https://user-images.githubusercontent.com/8035962/36347364-36c05388-141b-11e8-82d6-18aa708539a8.png)

1.6.8:
![image](https://user-images.githubusercontent.com/8035962/36347367-4224367c-141b-11e8-9f66-634cdb921859.png)

5. System information
- OS & OS version:  Windows 7 Pro 64bit
- OS theme name:  Windows Classic Theme
- DPI / HiDPI resolution: 96dpi
- Firefox version: 58.0.2
- Firefox theme / lw-theme: Default
- This projects settings the issue occurs with:

**Comment by MarkRH** [comment]
OK, I've separated things out and have corrected the grey background color. Now the only problem is these tall tabs. Here's what I'm loading now for the 1.6.8 version:
```
@import url(./classic168/config/general_variables.css); /**/
@import url(./classic168/config/color_variables_classic-grey.css); /**/  /* <- 'classic grey' colors */
@import url(./classic168/css/buttons/buttons_on_navbar_classic_appearance.css); /**/
@import url(./classic168/css/buttons/icons_colorized.css); /**/
@import url(./classic168/css/buttons/buttons_on_bookmarks_toolbar_old_size_and_appearance.css); /**/
@import url(./classic168/css/buttons/bookmarks_menu_button_localized_label_on_bookmarks_toolbar.css); /**/
@import url(./classic168/css/buttons/bookmarks_menu_button_popup_classic_appearance.css); /**/
@import url(./classic168/css/buttons/appbutton_popup_icons_colorized.css); /**/
@import url(./classic168/css/buttons/appbutton_in_titlebar.css); /**/ /* <-- label only */
@import url(./classic168/css/buttons/appbutton_in_titlebar_autocolor.css); /**/
@import url(./classic168/css/tabs/classic_squared_tabs.css); /**/
@import url(./classic168/css/tabs/tabs_below_navigation_toolbar.css); /**/ 									/* <-- tabs not on top */
@import url(./classic168/css/tabs/missing_tab_favicon_restored_default.css); /**/
@import url(./classic168/css/tabs/tab_close_always_visible.css); /**/
@import url(./classic168/css/tabs/tab_icon_colors.css); /**/
@import url(./classic168/css/generalui/private_mode_indicator_hidden.css); /**/
@import url(./classic168/css/generalui/bookmark_icons_colorized.css); /**/
@import url(./classic168/css/generalui/findbar_on_top.css); /**/
@import url(./classic168/css/generalui/searchbar_glassplus_indicator_hidden.css); /**/
@import url(./classic168/css/generalui/searchbar_go_button_hidden.css); /**/
@import url(./classic168/css/generalui/searchbar_popup_engines_show_labels.css); /**/
@import url(./classic168/css/toolbars/toolbars_old_padding.css); /**/
@import url(./classic168/css/toolbars/tabs_toolbar_adjustments.css); /**/
@import url(./classic168/css/toolbars/bookmarks_toolbar_old_height.css); /**/
@import url(./classic168/css/toolbars/general_toolbar_colors.css); /**/
@import url(./classic168/css/locationbar/locationbar_adjustments.css); /**/
@import url(./classic168/css/locationbar/compact_mode_reduce_fontsize.css); /**/
@import url(./classic168/css/locationbar/identitybox_replace_i_icon_with_globe.css); /**/
@import url(./classic168/css/locationbar/identitybox_colors.css); /**/
@import url(./classic168/css/locationbar/identitybox_padlock_icon_classic.css); /**/
@import url(./classic168/css/locationbar/icons_colorized.css); /**/
@import url(./classic168/css/locationbar/pageaction_separator_in_location_bar_hidden.css); /**/
@import url(./classic168/css/locationbar/pageaction_button_in_location_bar_hidden.css); /**/
@import url(./classic168/css/locationbar/starbutton_is_last_pageaction_button.css); /**/
@import url(./classic168/css/locationbar/dropmarker_at_the_end.css); /**/
@import url(./classic168/css/locationbar/dropmarker_visible.css); /**/
@import url(./classic168/css/locationbar/ac_popup_classic_with_two_lines.css); /**/

```

**Comment by Aris-t2** [comment]
What toolbar buttons do you have on tabs toolbar besides the default new tab button and all tabs buttons?
Does the issue disappear, if all other buttons are moved elsewhere?

**Comment by MarkRH** [comment]
I have an Undo Close Tab button from https://addons.mozilla.org/en-US/firefox/addon/undo-close-tab-button/

I can move that out and see what happens.  If I load v150 /classic/css/tabs/classic_squared_tabs.css instead of the 168 version, then the tab height is the same as it was... so I'm testing things with the differences between the two.

**Comment by MarkRH** [comment]
Interesting, if I comment the following at the bottom, it doesn't increase in size.  It seems to do the opposite of what it says, at least on my system:
```css
/* make sure toolbar buttons do not increase toolbar height */
/*
#TabsToolbar > toolbarpaletteitem,
#TabsToolbar > toolbarbutton {
  min-height: unset !important;
  padding: unset !important;
  margin: unset !important;
}
#TabsToolbar > toolbarpaletteitem  .toolbarbutton-icon,
#TabsToolbar > toolbarbutton  .toolbarbutton-icon{
  min-width: unset !important;
  width: 24px !important;
  min-height: unset !important;
  height: 24px !important;
} /**/

```

**Comment by Aris-t2** [comment]
This code breaks it for some buttons for me too. I'm currently experimenting and replacing it with this one fixes it for me:

```css
#TabsToolbar toolbarbutton .toolbarbutton-badge-stack,
#TabsToolbar > toolbarpaletteitem,
#TabsToolbar > toolbarbutton {
  min-height: unset !important;
  padding: unset !important;
  margin: 0 2px !important;
}

#TabsToolbar > toolbarpaletteitem .toolbarbutton-icon,
#TabsToolbar > toolbarbutton .toolbarbutton-icon {
  min-width: 18px !important;
  width: 18px !important;
  min-height: 18px !important;
  height: 18px !important;
  padding: unset !important;
  margin: unset !important;
}
```

But you also have to remove this one from the file
```css
#TabsToolbar #alltabs-button .toolbarbutton-icon,
#TabsToolbar > #new-tab-button .toolbarbutton-icon,
#TabsToolbar > toolbarpaletteitem > #new-tab-button .toolbarbutton-icon {
  padding: 3px !important;
}
```
