### ISSUE TITLE
Tab Height

### ISSUE THREAD

**Issue by David1501** [Aris-t2/CustomCSSforFx#114]
Ciao Aris....
this is probably the wrong place to post this question...but short&quick: can you help me with tab height? it's from yesterday i'm trying to modify my tab height without success (really miss CTR!!!!).
This is my userChrome.css:

/* Copyright (c) 2017 Haggai Nuchi
Available for use under the MIT License:
https://opensource.org/licenses/MIT
*/

@namespace url(http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul);

toolbarbutton#alltabs-button {
    -moz-binding: url("userChrome.xml#js");
}
#tabbrowser-tabs .tabbrowser-tab .tab-close-button { display:none!important; } #TabsToolbar { height: 20px !important; }
(

I need to add some code to modify Tabs Height... below 20px. Tried to change the value "height: 20px !important; }" but it seems that below 20 does not go... :-(
Can u gime me an Help?

THX
David

**Comment by Aris-t2** [comment]
This is indeed the wrong place. There are support threads inside "issue" area for such questions.

Try this:
```css
#tabbrowser-tabs,
#tabbrowser-tabs > .tabbrowser-arrowscrollbox,
.tabbrowser-tabs[positionpinnedtabs] > .tabbrowser-tab[pinned] {
  min-height: 18px !important;
}
```
