### ISSUE TITLE
addonlists_compact.css > Recently updated

### ISSUE THREAD

**Issue by Acid-Crash** [Aris-t2/CustomCSSforFx#117]
1. Describe the issue
If addonlists_compact.css is enabled extension name and description is on the same line which is ok compact wise. However, this doesn't apply to Recently updated section. Here extension name and description are on separate lines (plus one more line for "latest updates").

2. What should have happened instead?
It would be more logical if Recently updated section would share the same behaviour as default one (aka extension name and description is on the same line)

3. Steps to reproduce the issue?
enable @import url(./css/aboutaddons/addonlists_compact.css);

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)
![addons1](https://user-images.githubusercontent.com/32600318/38265628-1af02a0c-377f-11e8-9435-0478082dab44.png)
![addons2](https://user-images.githubusercontent.com/32600318/38265629-1d647c16-377f-11e8-91a4-7278032cb39a.png)

5. System information
- OS & OS version: Win 10 x64
- OS theme name: default
- DPI / HiDPI resolution: 100
- Firefox version: 59.02
- Firefox theme / lw-theme: default 
- This projects settings the issue occurs with: 
@import url(./css/aboutaddons/addonlists_compact.css);

**Comment by Aris-t2** [comment]
The 'update list' uses different container content for add-on entries compared to the default ones.
That content can not be filled into one or two lines without breaking most of the appearance.

![1](https://user-images.githubusercontent.com/6013569/38277836-1ac6b31e-379a-11e8-819c-1baf887599ed.png)


Add this to userContent.css and see what happens.
```css
	#updates-list .addon .content-inner-container,
	#updates-list .addon .description-outer-container,
	#updates-list .addon .description-outer-container *,
	#updates-list .addon .update-available,
	#updates-list .addon .update-available *{
	  -moz-box-orient: horizontal !important;
	}
```
