### ISSUE TITLE
Container markers are too short when used with classic squared tabs / changed tab length.

### ISSUE THREAD

**Issue by Peacock365** [Aris-t2/CustomCSSforFx#124]
As the title says. Tabs display a container marker when used within a container (it's basically a colored line indicating that and which container is used) and this marker is too short and doesn't stretch across the whole tab when used within classic squared tabs with changed tab length (maximum size 250 pixels in my case).

Firefox 60, High DPI, macOS 10.13.4 High Sierra if this matters.

**Comment by Aris-t2** [comment]
The length of the bottom line in a container environment is controlled by Firefox, where 10% are cut off at the beginning and the end. You can easily override this by using the following code inside userChrome.css

```css
.tabbrowser-tab[usercontextid] > .tab-stack > .tab-background > .tab-bottom-line {
  background: linear-gradient(to right, var(--identity-tab-color),  var(--identity-tab-color)) !important;
}
```

Unfortunately the visual appearance of that line is not suitable for "classic tabs" for two reasons:
1. tab colorized differently compared to default tabs and therefore override that line
2. tab line looks really awful
