### ISSUE TITLE
[TABS BELOW NAVIGATION AND BOOKMARKS TOOLBARS] conflicts with menu bar

### ISSUE THREAD

**Issue by nollinvoyd** [Aris-t2/CustomCSSforFx#132]
Hi Aris,

Fx 61.01, Win 10 Pro, Custom CSS for Firefox v1.9.7

I'm kltpzyxmrm at [Ext] Classic Theme Restorer (Fx29-56/Waterfox/Basilisk)

We discussed the problem with the menu bar being conflicted with.  I thought it was taken care of with the changes you made with my content additions to userchrome.css, but as it turns out, it is caused when `@import url(./css/tabs/tabs_below_navigation_toolbar.css)` is activated, after which, if the menu bar is deselected, you see the attached results

![menubar](https://user-images.githubusercontent.com/20844322/42397742-e3d2f9fa-811b-11e8-9564-2233d6548020.png)

**Comment by Aris-t2** [comment]
This projects files work as they are. If you combine them with "other" custom code conflicts can not be avoided.

What you can do:
- backup your current custom code
- download and extract the full 1.9.7 release into your chrome folder
- enable `@import url(./css/tabs/tabs_below_navigation_toolbar.css)`
- add your code at the end of the userChrome.css

Report, if this helps.

**Comment by Aris-t2** [comment]
I just checked and your result is the default behavior. Once you move tabs below navigation toolbar  / bookmarks toolbar and hide the menubar an "empty" top toolbar stays. Not sure what exactly you wanted to have there, but it was like this with CTR in Fx29-56 and in older Fx builds too.

You can however move the navigation toolbar to a higher position. Look for `MOVE NAVIGATION TOOLBAR TO HIGHER POSITON` inside tab settings area.

For it to work with your code combination, you probably need more tweaking.

![123](https://user-images.githubusercontent.com/6013569/42401651-f47dc7ca-8176-11e8-92f3-1f7de792b957.png)

Here the full code:

```css
/* don't show back or forward buttons if there's nothing to go back or forward to show */
#ctraddon_back-button[disabled="true"],
#ctraddon_forward-button[disabled="true"],
#back-button[disabled="true"],
#forward-button[disabled="true"] {
 display: none !important;
}

/* HIDE MIN/MAX/CLOSE BUTTONS - breaks tab bar narrowness*/

#titlebar-max,
#titlebar-close,
#titlebar-min,
#titlebar-buttonbox {
  min-width: 1px !important;
  width: 1px !important;
  max-width: 1px !important;
  opacity: 0 !important;
}

/* TAB BAR DECREASE HEIGHT AND CENTER TAB TEXT - ARIS */
/* CLOSE BUTTON ON THE LEFT - RED CLOSE BUTTON - NUMBERED TABS - ARIS */
/* tab height */
#tabbrowser-tabs,
#tabbrowser-tabs > .tabbrowser-arrowscrollbox,
.tabbrowser-tabs[positionpinnedtabs] > .tabbrowser-tab[pinned] {
  min-height: 19px !important;
  /*height: 19px !important;*/ /* this might be required for some OS themes */
}

#TabsToolbar #tabbrowser-tabs[overflow="true"] .tabbrowser-tab[pinned] {
  min-height: 18px !important;
  max-height: 18px !important;
}

#TabsToolbar .tabbrowser-tab {
  height: 19px !important;
  min-height: 19px !important;
  max-height: 19px !important;
}

/* tab label  */
.tab-label {
  -moz-box-flex: 1 !important;
  text-align: center !important;
  font-weight: bold !important;
  font-size: 16px !important;
  margin-top: -5px !important;
  -moz-margin-start: 0px !important;
  -moz-margin-end: 0px !important;
  -moz-padding-start: 0px !important;
  -moz-padding-end: 0px !important;
}

/* close icon */
#TabsToolbar #tabbrowser-tabs .tabbrowser-tab:not([pinned]) .tab-close-button {
  -moz-box-ordinal-group: 0 !important;
  -moz-margin-start: -9px !important;
  -moz-margin-end: 0px !important;
}

#main-window #navigator-toolbox #TabsToolbar .close-icon > .toolbarbutton-icon,
#main-window #navigator-toolbox #TabsToolbar .tab-content .close-icon  {
  min-width: 20px !important;
  width: 20px !important;
  min-height: 20px !important;
  height: 20px !important;
}

/* NUMBERED TABS */
#tabbrowser-tabs{
  counter-reset: n_tabs 0;
}
.tabbrowser-tab .tab-content {
  -moz-padding-start: 0px;
}
.tabbrowser-tab .tab-content::before {
  display: -moz-box;
  -moz-padding-end: 8px;
  counter-increment: n_tabs;
  content: counter(n_tabs);
  font-weight: bold !important;
  font-size: 16px !important;
  margin-top: -2px !important;
}

/* REMOVE EDIT MENU (IF YOU ALREADY USE ALL THE KEYBOARD SHORTCUTS) */
#edit-menu { display: none !important; }
#file-menu { display: none !important; }
#view-menu { display: none !important; }
#history-menu { display: none !important; }
#bookmarksMenu { display: none !important; }


/* Firefox userChrome.css - FOR EXITFIREFOXBUTTON_MOVABLE.UC.JS */

toolbarbutton#alltabs-button {
  -moz-binding: url("userChrome.xml#js");
}

#go-quit-application-button {
  list-style-image: url("exit.png") !important;
  -moz-image-region: rect(0px, 16px, 16px, 0px) !important;
}

/* Firefox userChrome.css - FOR OPEN PROFILE DIRECTORY BUTTON */

toolbarbutton#alltabs-button {
  -moz-binding: url("userChrome.xml#js");
}

#launch-profile-directory {
  list-style-image: url("launch.png") !important;
  -moz-image-region: rect(0px, 16px, 16px, 0px) !important;
}

/* fix tab toolbars button width/height for default tabs */

#navigator-toolbox #TabsToolbar .scrollbutton-up,
#navigator-toolbox #TabsToolbar .scrollbutton-down,
#navigator-toolbox #TabsToolbar #alltabs-button,
#navigator-toolbox #TabsToolbar #new-tab-button {
  padding: 0px !important;
}

#navigator-toolbox #TabsToolbar .scrollbutton-up > .toolbarbutton-icon,
#navigator-toolbox #TabsToolbar .scrollbutton-down > .toolbarbutton-icon,
#navigator-toolbox #TabsToolbar #alltabs-button > .toolbarbutton-icon,
#navigator-toolbox #TabsToolbar #new-tab-button > .toolbarbutton-icon,
#navigator-toolbox #TabsToolbar .tabs-newtab-button > .toolbarbutton-icon {
  padding: 0px !important;
  width: 16px !important;
  height: 16px !important;
}

/* hide empty space before and after tabs */
hbox[type="pre-tabs"],
hbox[type="post-tabs"] {
  min-width: 1px !important;
  width: 1px !important;
  max-width: 1px !important;
  opacity: 0 !important;
}


#main-window[tabsintitlebar][sizemode="normal"] #toolbar-menubar[autohide="true"][inactive="true"],
#main-window[tabsintitlebar][sizemode="maximized"] #toolbar-menubar[autohide="true"][inactive="true"] {
  margin-top: unset !important;
}

#main-window[tabsintitlebar] #toolbar-menubar[autohide="true"][inactive="true"] ~ #nav-bar:not(:-moz-lwtheme),
#main-window[tabsintitlebar] #toolbar-menubar[autohide="true"][inactive="true"] ~ #nav-bar {
  -moz-margin-end: 1px !important;
  -moz-appearance: none !important;  
  background: transparent !important;
  border-top: unset !important;
}

#main-window[sizemode="normal"] #navigator-toolbox #nav-bar {
  border-left: 0px !important;
  border-right: 0px !important;
}

#main-window[tabsintitlebar] #toolbar-menubar[autohide="true"][inactive="true"] ~ #nav-bar #nav-bar-customization-target {
  -moz-padding-start: 50px !important;
}
```
