### ISSUE TITLE
v2.0.9: Search Bar suggestions changed appearance.

### ISSUE THREAD

**Issue by MarkRH** [Aris-t2/CustomCSSforFx#144]
1. Describe the issue
I use @import "./classic209/css/generalui/searchbar_popup_engines_show_labels_scrollbars.css"; /**/ and with this version the appearance of the suggestions changed.  The little clock symbol is smashed next to the first letter now:
![image](https://user-images.githubusercontent.com/8035962/46397897-1a762580-c6b9-11e8-81aa-9b2e480f7f68.png)

2. What should have happened instead?
It should look like:
![image](https://user-images.githubusercontent.com/8035962/46397922-34b00380-c6b9-11e8-89ae-2311197ae0a5.png)

With version 197 it does.
3. Steps to reproduce the issue?
@import "./css/generalui/searchbar_popup_engines_show_labels_scrollbars.css";

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)
(See above)

5. System information
- OS & OS version:  Windows 7 Pro
- OS theme name:  Classic Theme
- DPI / HiDPI resolution: Normal
- Firefox version: 62.0.3
- Firefox theme / lw-theme: Default theme
- This projects settings the issue occurs with: 
@import "./css/generalui/searchbar_popup_engines_show_labels_scrollbars.css";

**Comment by MarkRH** [comment]
I fixed it for myself.  Added the following override in my userChrome.css to move it over a bit from `  -moz-margin-end: -3px !important;`:
```css
/* from /generalui/searchbar_popup_engines_show_labels_scrollbars.css */
#PopupSearchAutoComplete .search-panel-tree > .autocomplete-richlistitem > .ac-type-icon {
  -moz-margin-end: 3px !important;
}
```
![image](https://user-images.githubusercontent.com/8035962/46399144-932ab100-c6bc-11e8-94d5-fd01c79d34e2.png)

I'd just assume close this but I'll leave it open for you to decide. :)
