### ISSUE TITLE
[Firefox 63 only][not Firefox 64+] How to restore the 'classic xbl/xml based autocomplete popup with two-lined results'?

### ISSUE THREAD

**Issue by Nyekomimi** [Aris-t2/CustomCSSforFx#153]
1. The suggested page list box is too large (scaling to browser size rather than to adress bar size), as well as lists adress before site name.

2. It's size should be matching (and I'd swear it was before last update) adress bar size, and site name should be before 

3. Steps to reproduce the issue?
Get new Firefox update. Get updated CSS.

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)
https://prnt.sc/l9usn4

5. System information
- OS & OS version: Win 7
- OS theme name: ?
- DPI / HiDPI resolution: ?
- Firefox version: Newest, sadly.
- Firefox theme / lw-theme: Classic
- This projects settings the issue occurs with: no idea

I submit it because I'd swear that before newest Firefox patch it worked correctly, and I did copy all settings from old userChrome to new one.

**Comment by Aris-t2** [comment]
The "full sizes" address bar popup is part of Firefox since years now. You probably used `Classic Theme Restorer` before Firefox 57 to restore it.
This project also offers a way to get the "old" popup back. It was enabled by default when this project started, but now you have to enable it manually.

Open `userChrome.css`, scroll down to the bottom and set popup settings like on this screenshot, if you are using Firefox 63:
![1](https://user-images.githubusercontent.com/6013569/47433244-5411ec00-d7a0-11e8-9e11-3ca7a0ddd8e7.png)

**Comment by Nyekomimi** [comment]
Thanks a lot. 

Long live the restoration project, and lets all just blame Quantum.

**Comment by dana86** [comment]
Hey, I updated today to the newest Firefox 63 (Win 10). For some reason the pop up doesn't show. I downloaded new version of the CSS files and edited the userChrome.css as I had the previous one + made sure to set it the way you mentioned but still it doesn't show up. Any ideas where the problem might be?

**Comment by Aris-t2** [comment]
Did you select the on with **_fx63** at the end like in shown in the above screenshot?

**Comment by Aris-t2** [comment]
@dana86 
Make sure you are using the whole new package from here https://github.com/Aris-t2/CustomCSSforFx/releases and not just updated CSS files, because this option also requires the corresponding xml file.

I just tested this again Fx 63, 64beta3 and 65 Nightly and it works with all three of them.

**Comment by dana86** [comment]
Thanks, that worked although it changed some of my customization for some reason. I'll have to investigate :) thanks for the help

**Comment by Aris-t2** [comment]
@TargetDroneTK421 
The current options do not offer "the old popup" with url only results, but I will add this feature on next update.
Use this in userChrome.css till then:
```css
#PopupAutoCompleteRichResult[autocompleteinput="urlbar"] .autocomplete-richlistbox .autocomplete-richlistitem .ac-title {
  visibility: collapse !important;
}
#PopupAutoCompleteRichResult[autocompleteinput="urlbar"] .autocomplete-richlistbox .autocomplete-richlistitem .ac-action,
#PopupAutoCompleteRichResult[autocompleteinput="urlbar"] .autocomplete-richlistbox .autocomplete-richlistitem .ac-url {
  margin-top: -20px !important;
}
```

@dana86 
Your previous tweaks/settings got removed by overwriting userChrome.css. Always make backups of that file before replacing it.
