### ISSUE TITLE
[Firefox 63] Little cosmetical problem in bookmarks 

### ISSUE THREAD

**Issue by Thalon77** [Aris-t2/CustomCSSforFx#154]
![bookmark](https://user-images.githubusercontent.com/33811707/47569945-3033df00-d935-11e8-97ce-7094603b2194.jpg)
See attached image: the up/down arrows in the bookmarks menu that appears clicking on its icon on the toolbar changed after the update to Firefox 63: is there a way to restore the "old small solid black" ones?
Using V 2.17 with crystal icons style selected.
Thanks in advance.

**Comment by Aris-t2** [comment]
This will be fixed on next update. Use this in userChrome.css till then:

```css
:-moz-any(#customization-container,#nav-bar) #bookmarks-menu-button menupopup :-moz-any(.scrollbutton-up,.scrollbutton-down) .toolbarbutton-icon,
toolbar:not(#nav-bar) #bookmarks-menu-button menupopup :-moz-any(.scrollbutton-up,.scrollbutton-down) .toolbarbutton-icon {
  padding: unset !important;
  width: unset !important;
  height: unset !important;
}
```
