### ISSUE TITLE
[Customize] Scrollbar properties directly via userContent.css in 64+

### ISSUE THREAD

**Issue by happysurf** [Aris-t2/CustomCSSforFx#160]
Now is possible change the scrollbar colors and width in userContent.css  without any script.
Look this interesting discussion on Reddit:
https://www.reddit.com/r/FirefoxCSS/comments/98j1a7/psa_you_can_change_scrollbar_properties_directly/
This is the result:

![scroolbar](https://user-images.githubusercontent.com/13637587/47872782-c40f1a80-de0f-11e8-92f6-3a6adcdb7338.png)

**Comment by Aris-t2** [comment]
Thanks for the note. Looks interesting.

**Comment by happysurf** [comment]
I don't understand because in some web pages,  no scrollbars appear with the new code.

Try:
https://www.netvibes.com/bibrouen#Litterature
https://www.liberoquotidiano.it/

Firefox 64beta with this code:

```css
/* Thin Scrollbar */
:root{
  scrollbar-color: rgb(210,210,210) rgb(46,54,69) !important;
  scrollbar-width: thin !important;
}
```
