### ISSUE TITLE
color in the browser tabs

### ISSUE THREAD

**Issue by gabri25ele** [Aris-t2/CustomCSSforFx#162]
Is possible to have this blue color also in the dark theme:
![cattura](https://user-images.githubusercontent.com/33927879/47988849-a083f280-e0e3-11e8-95e7-bfd5b168f924.PNG)

**Comment by gabri25ele** [comment]
but I don't understand where add this line...
userChrome.css or userContent.css
and at any point of file?

**Comment by Aris-t2** [comment]
Always at the end of `userChrome.css`, if the change is for the user interface (window/toolbars/buttons...).
`userContent.css` is for web pages or content pages like about:addons.

**Comment by Aris-t2** [comment]
You can also specify window colors for active and inactive windows, if you want:

```css
#main-window {
  background-color: #0063b1 !important;
}
#main-window:-moz-window-inactive {
  background-color: black !important;
}
```

**Comment by Aris-t2** [comment]
Looks like current release and beta builds require different code snippets.

**Firefox 63-64**
```css
#main-window,
#main-window #navigator-toolbox,
#main-window #navigator-toolbox #TabsToolbar {
  background-color: #0063b1 !important;
}
#main-window:-moz-window-inactive,
#main-window:-moz-window-inactive #navigator-toolbox,
#main-window:-moz-window-inactive #navigator-toolbox #TabsToolbar  {
  background-color: black !important;
}
```

**Firefox 65+**
```css
#main-window {
  background-color: #0063b1 !important;
}
#main-window:-moz-window-inactive {
  background-color: black !important;
}
```
