### ISSUE TITLE
Extension provided Single Tab Close Button hidden with tabs_below_navigation_toolbar

### ISSUE THREAD

**Issue by rjw62** [Aris-t2/CustomCSSforFx#167]
When using these chrome CSS files with tabs_below_navigation_toolbar.css and tab_close_hidden.css and either https://addons.mozilla.org/en-US/firefox/addon/simple-close-tab-button/ to add a single close button on the right of the tab bar, the close button is hidden unless/until you hover over it with the mouse. I would expect this close button to always be visible.

I'm using Firefox 63.0.1 (64-bit) on Windows 7. The issue does not occur for me with a similar setup on Linux. The extension-added single close button is always visible (though with on-hover highlighting) when not using tabs_below_navigation_toolbar.css .  Also https://addons.mozilla.org/en-GB/firefox/addon/close-the-tab-button/ works fine (i.e. the button is always visible) and other toolbar buttons can be moved to the tab bar in the Firefox customisation system, and they stay visible all the time.

I wonder if something in the close button name used by the two extensions is accidentally being caught by some CSS classes in the chrome CSS customisations.

**Comment by rjw62** [comment]
Actually, on closer inspection, I wonder if it's just that the colour of the cross on the tab close button when it doesn't have its hover highlighting exactly matches (or is too close to) the background colour of the tab bar. So it's there and visible, but just can't be seen over the background.

**Comment by Aris-t2** [comment]
The default setup chooses a light icon on tabs toolbar, which has to be overridden for "tabs not on top mode".

I will fix this on next update, but you can already use the code inside userChrome.css:

```css
/* Simple Close Tab button */
#TabsToolbar:not(:-moz-lwtheme) #_fe8cab45-aaee-45f8-8765-781e0ebea300_-browser-action {
  --webextension-toolbar-image-light: url("moz-extension://7904448c-2319-4f6f-aac9-a1f701258098/icons/Close-dark.svg") !important;
}

/* close tab button */
#TabsToolbar:not(:-moz-lwtheme) #closetab_fmarin_com-browser-action {
  --webextension-toolbar-image-light: url("moz-extension://31006e48-8e00-476f-8ea9-697e40934b02/icons/icon.svg") !important;
  --webextension-toolbar-image-2x-light: url("moz-extension://31006e48-8e00-476f-8ea9-697e40934b02/icons/icon.svg") !important;
}

/* close window button */
#TabsToolbar:not(:-moz-lwtheme) #close-window-button_nanpuyue_com-browser-action {
  --webextension-toolbar-image-light: url("moz-extension://c914bd13-793f-4a2d-ab66-c655a3d75c52/icons/icon.svg") !important;
  --webextension-toolbar-image-2x-light: url("moz-extension://c914bd13-793f-4a2d-ab66-c655a3d75c52/icons/icon.svg") !important;
}
```
