### ISSUE TITLE
Is possible to change the order of add-on listed?

### ISSUE THREAD

**Issue by gabri25ele** [Aris-t2/CustomCSSforFx#168]
![g9cxf9x6hzsz](https://user-images.githubusercontent.com/33927879/48660466-6232ef80-ea62-11e8-86d0-7d1ddc4429b6.png)

change only the order of add-on...
possible?

I don't think is duplicate of that https://github.com/Aris-t2/CustomCSSforFx/issues/76
or I don't read anything about order. 
I don't want hidden anything (./css/tabs/tab_context_menuitems_visibility.css"; /**/)

**Comment by Aris-t2** [comment]
It looks like you are referring to "page content" menu (right-click on web pages) and not tab context menu (right-click on tabs). Those are not the same.

[If you get the ids of all items](https://github.com/Aris-t2/CustomCSSforFx#how-to-find-item-ids-and-attributes), you can change their order like this:

```css
#id_of_first_item {
  -moz-box-ordinal-group: 0 !important;
}
#id_of_second_item {
  -moz-box-ordinal-group: 1 !important;
}
#id_of_third_item {
  -moz-box-ordinal-group: 2 !important;
}
...
```

Note: changing page context menus order sometimes corrupts the whole menu meaning your desired order won't stick or you won't be able to restore the initial one.
