### ISSUE TITLE
Reduce space between icon extensions and search field

### ISSUE THREAD

**Issue by gabri25ele** [Aris-t2/CustomCSSforFx#170]
1) Is possible decrease the space between the icons of extensions (see yellow color Highlight)?
2) Is possible reduce the lenght of the search field? (see red color line)?

![annotazione 2018-12-14 151621](https://user-images.githubusercontent.com/33927879/50008302-05b8e680-ffb4-11e8-9ed3-1acbb9330da8.jpg)

**Comment by Aris-t2** [comment]
Please use the [general talk/discussion thread](https://github.com/Aris-t2/CustomCSSforFx/issues/163) for questions like mentioned in the issue template.
----> https://github.com/Aris-t2/CustomCSSforFx/blob/master/ISSUE_TEMPLATE#L4

1. Customizing mode > Density > compact

2. Yes.
```css
#search-container {
  min-width: 100px !important;
  max-width: 100px !important;
}
```
