### ISSUE TITLE
Restoring toolbar buttons native look

### ISSUE THREAD

**Issue by Yaron10** [Aris-t2/CustomCSSforFx#176]
Hello Aris,

I've just found this repo. Thank you for the numerous gems. :+1: 

I've seen your various "button appearance" files.
I'd like to restore the native 3D look (Win 7 Classic Theme) on hovering/pressing a toolbar button.
Should I manually draw the border? Isn't unsetting some rules enough?
***
What's the CSS syntax for controlling uBO's button?
```
toolbarbutton[id*="uBlock0@raymondhill.net"] { margin-inline-end: 4px !important; }
```
Does not work.

I hope it's OK I've opened an issue here. I'd appreciate your help.
Best regards.

**Comment by Aris-t2** [comment]
This project does not support Windows classic themes default buttons, but one can rewrite the present "classic button" code, which is Win7s old default buttons appearance.

You have to unset this line in userChrome.css first.
`@import "./css/buttons/buttons_on_navbar_classic_appearance.css"; /**/`


Test this:

```css
/* main menu button adjustment */
#PanelUI-button {
  margin-inline-start: 0px !important;
  border-inline-start: 0px solid !important;
  border-image-slice: 0 !important;
  padding-left: 2px !important;
  padding-right: 2px !important;
}
#PanelUI-menu-button {
  -moz-appearance: unset !important;
  background: unset !important;
  box-shadow: unset !important;
  border-image: unset !important;
  border: unset !important;
  padding: unset !important;
  margin: unset !important;
  min-width: unset !important;
  width: unset !important;
  max-width: unset !important;
  min-height: unset !important;
  height: unset !important;
  max-height: unset !important;
}

/* back button adjustment */
#nav-bar #back-button .toolbarbutton-icon {
  border: 0 !important;
}

/* adjust zoom reset and copy buttons position */
#nav-bar :-moz-any(#copy-button,#zoom-reset-button) {
  -moz-margin-start: -1px !important;
  -moz-margin-end: -1px !important;
}
#nav-bar :-moz-any(#edit-controls, #zoom-controls) separator {
  visibility: collapse !important;
}

/* classic button style */
#main-window:not([customizing]) #nav-bar .toolbarbutton-1[disabled=true]:-moz-any([open],[checked],:hover:active,:active) > .toolbarbutton-icon,
#main-window:not([customizing]) #nav-bar .toolbarbutton-1[disabled=true]:-moz-any([open],[checked],:hover:active,:active) > .toolbarbutton-text,
#main-window:not([customizing]) #nav-bar .toolbarbutton-1[disabled=true]:-moz-any([open],[checked],:hover:active,:active) > .toolbarbutton-badge-stack,
#nav-bar toolbarbutton[type="menu-button"] > .toolbarbutton-icon,
#nav-bar .toolbarbutton-1 > .toolbarbutton-menubutton-button[open] + .toolbarbutton-menubutton-dropmarker > .dropmarker-icon,
#nav-bar .toolbarbutton-1[open] > .toolbarbutton-menubutton-button > .toolbarbutton-icon,
#nav-bar .toolbarbutton-1[open] > .toolbarbutton-menubutton-dropmarker > .dropmarker-icon,
#nav-bar .toolbarbutton-1:not([checked]):not([open]):not(:active) > .toolbarbutton-icon,
#nav-bar .toolbarbutton-1:not([checked]):not([open]):not(:active) > .toolbarbutton-text,
#nav-bar .toolbarbutton-1:not([checked]):not([open]):not(:active) > .toolbarbutton-badge-stack,
#nav-bar .toolbarbutton-1:not([buttonover]):not([open]):not(:active) > .toolbarbutton-menubutton-dropmarker:not([disabled]) > .dropmarker-icon {
  background-image: unset !important;
  background-color: unset !important;
  background: unset !important;
  -moz-appearance: none !important;
}
#nav-bar .toolbarbutton-1:not([disabled=true]) > .toolbarbutton-menubutton-button[open] + .toolbarbutton-menubutton-dropmarker > .dropmarker-icon,
#nav-bar .toolbarbutton-1:not([disabled=true]):-moz-any(:hover,[open]) > .toolbarbutton-menubutton-button > .toolbarbutton-icon,
#nav-bar .toolbarbutton-1:not([disabled=true]):-moz-any(:hover,[open]) > .toolbarbutton-menubutton-dropmarker > .dropmarker-icon,
#nav-bar .toolbarbutton-1:not([disabled=true]):not([checked]):not([open]):not(:active):hover > .toolbarbutton-icon,
#nav-bar .toolbarbutton-1:not([disabled=true]):not([checked]):not([open]):not(:active):hover > .toolbarbutton-text,
#nav-bar .toolbarbutton-1:not([disabled=true]):not([checked]):not([open]):not(:active):hover > .toolbarbutton-badge-stack,
#nav-bar .toolbarbutton-1:not([buttonover]):not([open]):not(:active):hover > .toolbarbutton-menubutton-dropmarker:not([disabled]) > .dropmarker-icon {
  background-image: unset !important;
  background-color: unset !important;
  background: unset !important;
  -moz-appearance: none !important;
  box-shadow:	inset 0 1px white,
				inset 0 -1px #808080,
				inset 1px 0 white,
				inset -1px 0 #808080 !important;
  border-radius: 0px !important;
}
#nav-bar toolbarbutton[type="menu"][open]:not([disabled]) > .toolbarbutton-icon,
#nav-bar toolbarbutton[type="menu-button"]:not([open]):hover:not([disabled]):active > .toolbarbutton-icon,
#nav-bar .toolbarbutton-1 > .toolbarbutton-menubutton-button:not([disabled=true]):-moz-any(:hover:active,:active, [open]) > .toolbarbutton-icon,
#nav-bar .toolbarbutton-1[open] > .toolbarbutton-menubutton-dropmarker:not([disabled=true]) > .dropmarker-icon,
#nav-bar .toolbarbutton-1:not([disabled=true]):-moz-any([open],[checked],:hover:active,:active) > .toolbarbutton-icon,
#nav-bar .toolbarbutton-1:not([disabled=true]):-moz-any([open],[checked],:hover:active,:active) > .toolbarbutton-text,
#nav-bar .toolbarbutton-1:not([disabled=true]):-moz-any([open],[checked],:hover:active,:active) > .toolbarbutton-badge-stack {
  background-image: unset !important;
  background-color: unset !important;
  background: unset !important;
  -moz-appearance: none !important;
  box-shadow:	inset 0 1px #808080,
				inset 0 -1px white,
				inset 1px 0 #808080,
				inset -1px 0 white !important;
  border-radius: 0px !important;
}
#nav-bar toolbarbutton[disabled=true] > .toolbarbutton-icon {
  opacity: .6 !important;
}

#nav-bar toolbarbutton[disabled=true]{
  opacity: 1.0 !important;
}

```
