### ISSUE TITLE
[Fx57][Win7][Classic]v1.1.6: icons_colorized.css causes icons to swap locations.

### ISSUE THREAD

**Issue by MarkRH** [Aris-t2/CustomCSSforFx#18]
Originally, I made a report here https://github.com/bsiegel/http2-indicator/issues/6 cause I thought it had to do with [HTTP/2 Indicator :: Add-ons for Firefox](https://addons.mozilla.org/en-US/firefox/addon/http2-indicator/?src=ss)

With /css/locationbar/icons_colorized.css being imported it causes the location bar icons to start flipping positions and/or disappear with the mouse hovering over them.

Before: https://i.imgur.com/cHUS6Lu.png
After: https://i.imgur.com/TRQ5XOp.png

It would also do it with these two:
https://addons.mozilla.org/en-US/firefox/addon/awesome-rss/
https://addons.mozilla.org/en-US/firefox/addon/feedly-webextension/

57beta12 in Windows 7 Pro with Classic Theme.

**Comment by Aris-t2** [comment]
Thanks for reporting.

This is a very weird issue as it occurs with a certain combination of code only, a combination one would think has no effect on moving/jumping buttons at all.

The problem is caused by the combination of "starbuttons is last page action button" and "icons_colorized". Using only one of them does not cause the issue.

After further investigation I found the error and I'm not sure, if this is not a Firefox bug.

Combining
```css
#star-button-box{
  -moz-box-ordinal-group: 100 !important;
}
```
and
```css
#urlbar #page-action-buttons > .urlbar-icon:-moz-any(:hover,:hover:active,[open]){
  filter: brightness(1.25) !important;
}
```
causes the problem. However for me it does not make any sense, that changing buttons/icons brightness via filter rule causes jumping.


I will fix this issue soon by excluding brightness filter from urlbar icons.
