### ISSUE TITLE
[Firefox 65] url and title 50 percent does not work properly (too wide)

### ISSUE THREAD

**Issue by Nyekomimi** [Aris-t2/CustomCSSforFx#180]
http://prntscr.com/mdyaou
http://prntscr.com/mdyc61

As seen here. It's really distracting, to see it not start where it should and not end where it should. 

(Why does Mozilla keep breaking main thing that makes people use Firefox, aka support for CustomCSS?)

**Comment by Acid-Crash** [comment]
Hi,
I use the same rule (also on FF65) 
```css
@import "./css/locationbar/ac_popup_url_and_title_50percent_width.css"; /**/
```
but with addition of custom widths
```css

#PopupAutoCompleteRichResult[autocompleteinput="urlbar"] .autocomplete-richlistitem:-moz-any([type*="heuristic"],[actiontype="searchengine"],[actiontype="visiturl"],[actiontype="keyword"],[actiontype="switchtab"]) .ac-url-text,
#PopupAutoCompleteRichResult[autocompleteinput="urlbar"] .autocomplete-richlistitem .ac-title-text {
  min-width: calc((100vw - 100px)*0.45) !important;
  width: calc((100vw - 100px)*0.45) !important;
}

#PopupAutoCompleteRichResult[autocompleteinput="urlbar"] .autocomplete-richlistitem:-moz-any([type*="heuristic"],[actiontype="searchengine"],[actiontype="visiturl"],[actiontype="keyword"],[actiontype="switchtab"]) .ac-title-text,
#PopupAutoCompleteRichResult[autocompleteinput="urlbar"] .autocomplete-richlistitem .ac-url-text {
  min-width: calc((100vw - 100px)*0.55) !important;
  width: calc((100vw - 100px)*0.55) !important;
}
```
Works fine for me.
![default](https://user-images.githubusercontent.com/32600318/51941701-e4a23d00-241d-11e9-9ba4-8a9d6a803c0a.png)
Also if I recon correctly it's always been full width without any margins #5
