### ISSUE TITLE
[macOS][Firefox 65+][tabs not on top] caption buttons glitch

### ISSUE THREAD

**Issue by Aris-t2** [Aris-t2/CustomCSSforFx#186]
**fbnk:**
https://github.com/Aris-t2/CustomCSSforFx/issues/164#issuecomment-459461195
https://github.com/Aris-t2/CustomCSSforFx/issues/164#issuecomment-459466510
https://github.com/Aris-t2/CustomCSSforFx/issues/164#issuecomment-459476636

Hey there, which lines/commands do I have to enable (or disabale?), when using Aris-t2 script (2.3.8) on a Mac running macOS 10.14 and FF 65.0 to achieve the changes shown in the screenshot below?
Thanks in advance!
![bildschirmfoto 2019-01-31 um 19 12 30_2](https://user-images.githubusercontent.com/13615809/52077846-3ec40f00-2592-11e9-834b-4d4a3c45bb1f.png)

**@fbnk** 
Add `/*` before
```css
@import "./css/appbutton/appbutton_in_titlebar.css";
@import "./css/appbutton/appbutton_in_titlebar_autocolor.css";
@import "./css/locationbar/icons_colorized.css";
```

Remove `/*` before
```css
/* @import "./css/tabs/tabs_below_navigation_toolbar_fx65.css";
/* @import "./css/tabs/tabs_below_navigation_toolbar_fx65_macOS_fix.css";
```

The blue star is there by default.

Try this:

```css
#urlbar #star-button[starred],
#urlbar #star-button-animatable-box[starred]:-moz-any(:hover,:hover:active),
#urlbar #star-button[preloadanimations][animate][starred]:-moz-any(:hover,:hover:active),
#urlbar #star-button-box[open] #star-button[starred],
#urlbar #star-button[starred]:-moz-any(:hover,:hover:active) {
  filter: grayscale(100%) !important;
}
```

**fbnk:**
Thanks! Almost, but now it looks like this :) 

<img width="308" alt="bildschirmfoto 2019-01-31 um 20 33 01" src="https://user-images.githubusercontent.com/13615809/52080280-aaf54180-2597-11e9-9704-4e1a56a85b03.png">
