### ISSUE TITLE
[macOS][Firefox 65+][tabs not on top] Can Not Customise Tabs Colour or Text Completely

### ISSUE THREAD

**Issue by ChasCB** [Aris-t2/CustomCSSforFx#187]
1. Describe the issue:
Via
 ./config/custom_tab_color_settings.css
./config/custom_tab_text_settings.css
only the Selected Tab is showing my customisations. This issue only started with FF65.0.

2. What should have happened instead?
Should show different Tab colours & font style, font size, font weight & text colour per Tab state as per the attached css files including my_userChrome.css file

3. Steps to reproduce the issue?
[FineWines relevant css files.zip](https://github.com/Aris-t2/CustomCSSforFx/files/2824014/FineWines.relevant.css.files.zip)

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)
![screen shot 2019-02-02 at 16 25 51](https://user-images.githubusercontent.com/7608263/52159395-d5b2d780-2708-11e9-99ed-b9e0fbb74f00.png)

5. System information
- macOS10.14.3
- DPI / HiDPI resolution: standard macOS 1600 X 900
- Firefox version: 65.0
- Firefox theme / lw-theme: Default theme in Compact mode

**Comment by Aris-t2** [comment]
Tested a clean setup of CustomCSSforFx with and without themes.

`classic_squared_tabs.css` +
`tabs_below_navigation_toolbar_fx65.css` +
`tabs_below_navigation_toolbar_fx65_macOS_fix.css` + 
`custom_tab_color_settings.css `

![03](https://user-images.githubusercontent.com/6013569/52166138-9d5fc900-2709-11e9-8750-d1a38aca9a73.png)

`classic_squared_tabs.css` +
`tabs_below_navigation_toolbar_fx65_macOS_fix.css` + 
`custom_tab_color_settings.css` +
`tabs_below_main_content_fx65.css`


![05](https://user-images.githubusercontent.com/6013569/52166186-3abafd00-270a-11e9-972b-8b6ee2052b11.png)

_Note_
I will also add a duplicate of "tabs_below_navigation_toolbar_fx65_macOS_fix.css", because it is required for proper appearance.

**Comment by ChasCB** [comment]
Thank you Aris I look forward to the updates. 🎓
Cheers 🍷

**Comment by ChasCB** [comment]
I do apologise Aris I sent you the wrong userChrome.css file. The one I sent you is my own very old no longer used personal one. 

But anyway for me FF65 played around with my settings and I ended up with Tabs On Top with no colours and it went down hill from there. All very strange.

I am using **your whole package** (which is brilliant) with the wanted various @import css files activated within your userChrome.css file. The only files I have altered are the Tabs colour & text. 

Again I have to apologise as going through the custom_tab_color_settings code I had a double # for one of the colour hex codes so the colours were not working as the should.

AND, having researched your own github issues discussions I have discovered that the .tabbrowser-tab[unread] is now no more, bugger.

I also have activated **@import "./my_userChrome.css";** for my own small customisations for which this discussion has made me rewrite and clean up. 

I include it here for people to; use, improve upon or just generally comment on.

[FineWines_my_userChrome.css.zip](https://github.com/Aris-t2/CustomCSSforFx/files/2825119/FineWines_my_userChrome.css.zip)

Cheers 🍷

**Comment by Aris-t2** [comment]
I'm still wondering what happens on your end when you put [the complete release](https://github.com/Aris-t2/CustomCSSforFx/releases) into `/chrome/` folder and only change one line inside userChrome.css.
`/* @import "./config/custom_tab_color_settings.css"; /**/`
--->
`@import "./config/custom_tab_color_settings.css"; /**/`

Post a screenshot of that.

**Comment by ChasCB** [comment]
The first screenshot is as requested using the **default  userChrome.css** with only **@import "./config/custom_tab_color_settings.css"; /**/ activated**.
![custom_tab_color_settings-default](https://user-images.githubusercontent.com/7608263/52187274-62889d00-2891-11e9-90fc-c134133ba426.png)

The next screenshot is with my own customisations.
![my_customisations](https://user-images.githubusercontent.com/7608263/52187360-e3e02f80-2891-11e9-9c91-e2cbf24b133f.png)
Have been meaning to ask for ages about the gab between the top of the Tabs on the TabsToolbar and the bottom of the PersonalToolbar. Is there away to change the width of that gap, make it smaller ?

Cheers 🍷

**Comment by Aris-t2** [comment]
The problem is caused by the file `tabs_below_navigation_toolbar_fx65_macOS_fix.css`

Replace its code with this one:
```css
#main-window[tabsintitlebar]:not([sizemode="maximized"]):not([sizemode="fullscreen"]):not([inDOMFullscreen="true"]) #navigator-toolbox {
  margin-top: calc(-1px + var(--tab-min-height_tnot)) !important;
}

#TabsToolbar {
  height: var(--tab-min-height_tnot) !important;
}

#main-window[tabsintitlebar]:not([sizemode="maximized"]):not([sizemode="fullscreen"]):not([inDOMFullscreen="true"]) .titlebar-buttonbox-container {
  position: fixed !important;
  top: 0 !important;
}
```

**Comment by ChasCB** [comment]
Thank you Aris. That code fixed the original problem but now has created two new ones.
REFER TO SCREEN SHOT
1 - The Tab now overlaps into the main content by approximately 3px
2 - It has created a thin grey bar (#EEEEEE) of approximately 10px wide inside and on the bottom of the PersonalToolbar.

![screen shot 2019-02-05 at 10 27 11](https://user-images.githubusercontent.com/7608263/52240032-be583200-2934-11e9-9f5f-463886ba887f.png)

**Comment by Aris-t2** [comment]
Try to add this code and tell me, if you can find two values (e.g. -5 to 5) instead of `0`, that fix the issue:

```css
#tabbrowser-tabs .tabbrowser-arrowscrollbox {
  margin-top: 0px !important;
  margin-bottom: 0px !important;
}
```
