### ISSUE TITLE
recentupdates_category_always_visible.css doesnt work in Nightly 67.0a1

### ISSUE THREAD

**Issue by Acid-Crash** [Aris-t2/CustomCSSforFx#190]
1. Describe the issue
recentupdates_category_always_visible.css stopped working on Nightly 67.0a1

2. What should have happened instead?
Recent Updates section should be visible when opening about:addons

3. Steps to reproduce the issue?
- open about:addons
- notice that Recent Updates is hidden

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)
![about_addons](https://user-images.githubusercontent.com/32600318/54024841-7b8eb180-41a1-11e9-918e-2b18484fa943.png)

5. System information
- OS & OS version: Win 10x64
- OS theme name: Default
- DPI / HiDPI resolution: 100
- Firefox version: 67.0a1
- Firefox theme / lw-theme: default
- This projects settings the issue occurs with: 

<details>

```css
/* version number for add-ons - [only use one at a time] ****************************************/
/* [!] version number's xml file now restores add-on 'description' on Firefox 64+ ***************/
/* @import "./css/aboutaddons/addonlists_show_addon_version_number.css"; /**/
/* @import "./css/aboutaddons/addonlists_show_addon_version_number_hide_description.css";

/* show 'last updated' date for add-ons - [only use one at a time] ******************************/
@import "./css/aboutaddons/addonlists_show_addon_date_last_updated.css"; /**/
/* @import "./css/aboutaddons/addonlists_show_addon_date_last_updated_start_position.css"; /**/

/* addons page appearance - [only use one at a time] ********************************************/
/* @import "./css/aboutaddons/addons_manager_alternative_appearance.css"; /**/
/* @import "./css/aboutaddons/addons_manager_alternative_appearance_aero.css"; /**/ /* <-- AERO colors */
/* @import "./css/aboutaddons/addons_manager_alternative_appearance_v2.css"; /**/
/* @import "./css/aboutaddons/addons_manager_alternative_appearance_v2_aero.css"; /**/  /* <-- AERO colors */
/* @import "./css/aboutaddons/addons_manager_alternative_appearance_fx67.css"; /**/ /* if new html-based version is used */
/* @import "./css/aboutaddons/addons_manager_alternative_appearance_aero_fx67.css"; /**/    /* <-- AERO colors */ /* if new html-based version is used */

/* addons page appearance extra [requires one 'alternative appearance option' to be active] *****/
/* @import "./css/aboutaddons/addons_manager_alternative_appearance_compact_categories.css"; /**/

/* compact item lists - [only use one at a time] ************************************************/
/* @import "./css/aboutaddons/addonlists_compact.css"; /**/
/* @import "./css/aboutaddons/addonlists_compact_more_compact.css"; /**/

/* other settings *******************************************************************************/
/* @import "./css/aboutaddons/addonlists_disabled_addons_colorized_icons.css"; /**/
/* @import "./css/aboutaddons/addonlists_disabled_tag_hidden.css"; /**/
/* @import "./css/aboutaddons/addonlists_only_show_buttons_on_hover.css"; /**/
/* @import "./css/aboutaddons/addonlists_replace_button_labels_with_icons.css"; /**/
/* @import "./css/aboutaddons/addonlists_move_button_to_start.css"; /**/
/* @import "./css/aboutaddons/addonlists_green_dot_hidden.css"; /**/
@import "./css/aboutaddons/details_page_alternative_content_order.css"; /**/
/* @import "./css/aboutaddons/details_page_switch_banner_label_position_for_themes.css"; /**/
@import "./css/aboutaddons/recentupdates_category_always_visible.css"; /**/
/* @import "./css/aboutaddons/search_category_always_visible.css"; /**/


/************************************************************************************************/
/* about:preferences ****************************************************************************/
/************************************************************************************************/

/* preferences page appearance - [only use one at a time] ***************************************/
/* @import "./css/aboutpreferences/preferences_alternative_appearance.css"; /**/
/* @import "./css/aboutpreferences/preferences_alternative_appearance_aero.css"; /**/   /* <-- AERO colors */
/* @import "./css/aboutpreferences/preferences_alternative_appearance_v2.css"; /**/


/************************************************************************************************/
/* about:newtab / about:home ********************************************************************/
/************************************************************************************************/

/* a dark appearance for inbuilt 'Dark' theme is present by default in Firefox 61+ **************/
/* @import "./css/aboutnewtab/dark_appearance.css"; /**/
/* alternative background color for about:newtab/home pages 'Dark' theme present in Firefox 61+ */
/* @import "./css/aboutnewtab/dark_appearance_alternative_background.css"; /**/


/************************************************************************************************/
/* WEB CONTENT **********************************************************************************/
/************************************************************************************************/

/* top level image on white background - [only use one at a time] *******************************/
/* [!] this settings can sometimes cause glitches ***********************************************/
/* @import "./css/webcontent/toplevel_image_classic_v1.css"; /**/
/* @import "./css/webcontent/toplevel_image_classic_v2.css"; /**/

/* Screenshots - internal browser add-on ********************************************************/
/* @import "./css/webcontent/screenshots_alternative_save_ui.css"; /**/

/* CUSTOM SCROLLBARS VARIABLES (Firefox 63+ only) - EXPERIMENTAL ********************************/
/* [!] Might not work on every page! This issue is for Mozilla to solve. ************************/
/* [!] not compatible with custom scrollbar JavaScipt userChrome scripts ************************/
/* [!] custom size values only compatible with 'web content' scrollbars at the moment ***********/
/* [!] more info inside 'custom_scrollbar_appearance.css' file **********************************/
/* @import "./config/custom_scrollbar_appearance.css"; /**/     /* <--- EXPERIMENTAL */

```

</details>

**Comment by Aris-t2** [comment]
Test the new code:

```css
/* Firefox Quantum userChrome.css tweaks ************************************************/
/* Github: https://github.com/aris-t2/customcssforfx ************************************/
/****************************************************************************************/

@-moz-document url-prefix(chrome://mozapps/content/extensions/extensions.xul), url-prefix(about:addons) {

  #category-recentUpdates[disabled] {
	  opacity: 1 !important;
	  min-height: 48px !important;
	  height: 48px !important;
	}
	
	#category-recentUpdates[hidden] {
	  opacity: 1 !important;
	  min-height: 48px !important;
	  height: 48px !important;
	  display: inherit !important;
	  transition: unset !important;
	}

}
```
