### ISSUE TITLE
Auto Complete Font Size help

### ISSUE THREAD

**Issue by mrochaaa** [Aris-t2/CustomCSSforFx#212]
I'm using firefox 67.0.4 I want change font size of Auto Complete popup I use below code but it don't change Search Suggestions font, what I can do?

#PopupAutoCompleteRichResult .autocomplete-richlistitem:not([actiontype="searchengine"]) .ac-title,
#PopupAutoCompleteRichResult .autocomplete-richlistitem:not([actiontype="searchengine"]) .ac-action 
{ font-size: 20px !important;} 

and how I can decrease the width of this popup and remove the big side margins?

Someone know how remove Close, Minimise and Maximize buttons completelly?

Thanks!

**Comment by Aris-t2** [comment]
This should work in userChrome.css (at least it works for the styles offered by this project)

```css
#PopupAutoCompleteRichResult[autocompleteinput="urlbar"] .autocomplete-richlistitem .ac-title, 
#PopupAutoCompleteRichResult[autocompleteinput="urlbar"] .autocomplete-richlistitem .ac-url 
{ font-size: 20px !important;}
```

**Comment by mrochaaa** [comment]
very good, thanks! 

Please you know how I can decrease the big side margins of this suggestions popup and how remove Close, Minimise and Maximize buttons completelly?

**Comment by Aris-t2** [comment]
Look here to find code about removing unused space around results: https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/css/locationbar/ac_popup_title_and_url_50percent_width.css#L9

This will hide caption buttons, but now every OS supports hiding them.
```css
.titlebar-buttonbox {
  display: none !important;
}
```

**Comment by mrochaaa** [comment]
popup margin problem SOLVED, thanks again, good docs here, just one thing my fox is 67.0.4, the below code dont work, tabs can go over buttons but do not hide buttons, you know another solution?

.titlebar-buttonbox {
  display: none !important;
}

**Comment by Aris-t2** [comment]
That depends on your OS. Try to install/enable a theme and report, if something changes.
Which OS are you using?

**Comment by mrochaaa** [comment]
I tried install theme but any change buttons continue the tabs go over the buttons, I use Win 7, an another question, have some code to hide horizontal scrollbar to this ff version, I got many but all have issues, 
thanks

**Comment by Aris-t2** [comment]
You can not remove Win7s caption buttons, they are hard-coded into the OS themes (AeroGlass).
Scrollbar CSS does not work within default style sheets since a while now. Using JavaScript like here ( https://github.com/Aris-t2/CustomJSforFx/blob/master/scripts/custom_scrollbars.uc.js ) offers a few modification features.

**Comment by mrochaaa** [comment]
Thanks again... Please if you can help me, I have more 2 doubts...

1- Have some code to hide "http://" text from URLs in location bar and hide "i" icon keeping padlock and popup working ?

2- when using plugins like "Search Autocomplete" this plugin show search suggestions, this suggestions have an "green plugin icon" and if mouse over in one suggestion show "Extension:" text in urlbar, have too an "default first line" with an tip "Type your search etc" and in each suggestion have the an green url in front. Please you know how I can remove the itens:

Remove "Extension:" text
Remove Green Urls in Suggestions 
Remove The First Default Line (with the tip)
And remove suggestions text length limit

I'm asking this here because I see which you have a lot of knowledge in this matter, thanks again....

**Comment by Aris-t2** [comment]
1.
browser.urlbar.trimURLs pref controls the http:// visibility.
There are padlock settings inside this projects files and an option to replace the i icon with another icon.

2. Not sure what this is about. Post screenshots.
You can't remove the "moz-extension://" for extensions internal page url.
The "green" is set by @import "identitybox_colors.css", you have to disable it to remove the colorization of identity box.

"ac_popup_searchwith_and_visit_items_hidden.css" removes part of the suggestions.

**Comment by mrochaaa** [comment]
browser.urlbar.trimURLs hide "http" have some css to trim "https"? 

I read the "identitybox_replace_i_icon_with_globe.css" have some code to hide "i" icon without keeping popup working? 

How I can hide tags row from "new bookmark popup" ?

How I can hide "disabled" or "empty" back and forward buttons?

I search in all your docs but I cant find this codes, and in internet have some codes but dont worked to my version,

thanks again the attention...

**Comment by Aris-t2** [comment]
> browser.urlbar.trimURLs hide "http://" have some css to trim "https://"?

No, this is not done by CSS.

> I read the "identitybox_replace_i_icon_with_globe.css" have some code to hide "i" icon without keeping popup working?

`#identity-icon {display: none !important;}`
Keep in mind, this will have visual side effects in some cases.

> How I can hide tags row from "new bookmark popup" ?

`#editBMPanel_tagsRow {display: none !important;}`

> How I can hide "disabled" or "empty" back and forward buttons?
`#back-button[disabled], #forward-button[disabled] {display: none !important;}`

**Comment by mrochaaa** [comment]
tag row = done! back forward button = done     thanks!

an question, urls text have two colors is possible change this colors with css? On net say which can't, is true?

you know how remove the separator between Reader Button and Page Actions Button?

#identity-icon {display: none !important;}
This hide "i" but popup can't open any more, is possible hide "i" and hide padlock, keeping an small space just to click to open the panel?

you know how reduce find bar height, I can't find any doc about.

Thanks so much,

**Comment by Aris-t2** [comment]
> urls text have two colors is possible change this colors with css? On net say which can't, is true?

URL test is always black here or white for dark themes. Why would you want to change that? There were scripts in the past that changed url text based on identity/security level, but I don't think they work on current Fx versions.

> you know how remove the separator between Reader Button and Page Actions Button?

`#pageActionSeparator {display: none !important;}`

> This hide "i" but popup can't open any more, is possible hide "i" and hide padlock, keeping an small space just to click to open the panel?

```css
#connection-icon, #identity-icon {
  opacity: 0 !important;
  min-width: 4px !important;
  width: 4px !important;
  max-width: 4px !important;
}

```

There is no documentation on tweaking Mozilla products. Never found anything useful myself ;-)

> how reduce find bar and quick search bar heights

```css
.findbar-container,
.findbar-container * {padding:0 !important;}
```


If you need to find code for items to hide, you can use[ this instruction](https://github.com/Aris-t2/CustomCSSforFx#how-to-find-item-ids-and-attributes).

**Comment by mrochaaa** [comment]
Ok, sorry, so much asks, is because I'm very ignorant about css and I see which you know very much, I can find something with Dev Tools, but some items do not show "red border" and popups auto close like url suggestions. Is because I'm an old Firefox user, and I used the old FF years and years and now I take the quantum and I'm very sad with Mozilla UI and other feature limitations, but... What I can do?

Thanks the last post the codes worked again, if possible an last 3 asks: ahuahahahau :D

1- Is possible add Next and Previous buttons to Quick Find bar? Why? Because I like the auto hide 'n search when typing features.

2 - how I can hide the green separator between padlock and "https://"

3 - how reduce tab titles side margins

thanks,

**Comment by Aris-t2** [comment]
1. https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/userChrome.css#L511

2. No green sep here > screenshot? Devtools?
Try

```css
#urlbar[pageproxystate="valid"] :-moz-any(.insecureLoginForms,.mixedActiveContent,.notSecure,.notSecureText),
#urlbar[pageproxystate="valid"] .verifiedIdentity,
#urlbar[pageproxystate="valid"] .verifiedDomain {
  border-inline-end: 0px  !important;
  border-image: unset !important;
  border-image-slice: unset !important;
}
```

3. Devtools? Change margin and padding values of .tab-label-container, .tab-text and/or .tab-label classes.

Look through this projects files. Most stuff is or was already changed in some way by this projects files.
