### ISSUE TITLE
send_to_device_menuitems_hidden.css update needed

### ISSUE THREAD

**Issue by Acid-Crash** [Aris-t2/CustomCSSforFx#213]
1. Describe the issue
Firefox 68 introduced new elements related to Firefox Account (Updated section within AppMenu button and separate Firefox Account toolbar button). 
The mentioned elements also have reference to "Send to device"

2. What should have happened instead?
It might be a good idea to update _send_to_device_menuitems_hidden.css_ to include new elements.
I recon this is a new element that needs to be added
```css
#PanelUI-fxa-menu-sendtab-button {display: none !important;}
```

A bit offtopic:
If we are already touched sync topic, maybe it would be nice to add a new module to hide all reference to "Synced Tabs" and "View Synced tabs Sidebar"
_synced_tabs_menuitems_hidden.css_

3. Steps to reproduce the issue?
Navigate to mentioned elements

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)
![image](https://user-images.githubusercontent.com/32600318/60894376-38d20880-a26b-11e9-893a-d4028dcbfb86.png)

5. System information
- OS & OS version: Win10x64
- OS theme name: Default
- DPI / HiDPI resolution: 100
- Firefox version: 68
- Firefox theme / lw-theme: default 
- This projects settings the issue occurs with: 
send_to_device_menuitems_hidden.css

**Comment by Aris-t2** [comment]
I will add the id to the corresponding file one next update. Send me all related ids, if present, as I don't use any sync or profile features.

**Comment by Acid-Crash** [comment]
```css

/* Hide synced Tabs */ #PanelUI-fxa-menu-remotetabs-button, #PanelUI-fxa-menu-view-sidebar, #sidebarMenu-popup toolbarbutton#sidebar-switcher-tabs {display: none !important;}

```
