### ISSUE TITLE
(constancy) starbutton_alternative_icon_v2.css

### ISSUE THREAD

**Issue by mrochaaa** [Aris-t2/CustomCSSforFx#221]
please, using "starbutton_alternative_icon_v2.css" how show yellow star also in Url Bar Suggestions?

**Comment by Aris-t2** [comment]
Will be done with next update. Until then use this code in userChrome.css.

```css
/* yellow star button */
.urlbarView-row[type=bookmark] > .urlbarView-row-inner > .urlbarView-type-icon {
  list-style-image: url("chrome://browser/skin/bookmark.svg") !important;
  -moz-context-properties: fill !important;
  filter: unset !important;
  fill: #ffd100 !important;
}
```

**Comment by mrochaaa** [comment]
Continue an gray icon, I use this code too, have some relation ?


#PopupAutoCompleteRichResult[autocompleteinput="urlbar"] .autocomplete-richlistitem .ac-url, 
#PopupAutoCompleteRichResult[autocompleteinput="urlbar"] .autocomplete-richlistitem .ac-separator,
#PopupAutoCompleteRichResult[autocompleteinput="urlbar"] .autocomplete-richlistitem .ac-action  
{display:none !important;} 

#PopupAutoCompleteRichResult {
    width: 625px !important;
    max-width: 625px !important;
    margin-left: 0 !important;}

#PopupAutoCompleteRichResult[autocompleteinput="urlbar"] .autocomplete-richlistitem {
  -moz-margin-start: 0 !important;
  -moz-padding-start: 0 !important;
}

#PopupAutoCompleteRichResult[autocompleteinput="urlbar"] .autocomplete-richlistitem {
  border-inline-end: 0px solid transparent !important;
}

**Comment by Aris-t2** [comment]
Update to Firefox 68.

**Comment by mrochaaa** [comment]
I can't, because FF 68 can't disable multi process, and my machine have very low memory,

**Comment by Aris-t2** [comment]
This will cover Fx60-70:

```css
#PopupAutoCompleteRichResult[autocompleteinput="urlbar"] .ac-type-icon[type=bookmark],
.urlbarView-row[type=bookmark] > .urlbarView-row-inner > .urlbarView-type-icon,
#urlbar #star-button {
  list-style-image: url("chrome://browser/skin/bookmark.svg") !important;
  -moz-context-properties: fill !important;
  filter: unset !important;
  fill: #ffd100 !important;
}
```
