### ISSUE TITLE
[Nightly 70] Tabs look wrong...

### ISSUE THREAD

**Issue by nicolaasjan** [Aris-t2/CustomCSSforFx#225]
1. On the current Nightly (2019-08-28) the position of the tabs has shifted.

2. What should have happened instead?
Well, it should look like before ( see screenshots)

3. Steps to reproduce the issue?
Update to the latest Nightly

4. SCREENSHOTS:
![before](https://user-images.githubusercontent.com/14093220/63922639-563e7a00-ca45-11e9-84bf-c6148e95eab8.png)

   ![after](https://user-images.githubusercontent.com/14093220/63922646-59d20100-ca45-11e9-8587-890612f3a5e6.png)

5. System information
- OS & OS version: Linux Mint 19.2 Mate
- OS theme name: Mint-X/Emerald Window Decorator
- DPI / HiDPI resolution: 
- Firefox version: 70.0a1
- Firefox theme / lw-theme: default
- This projects settings the issue occurs with: 
`@import "./css/tabs/tabs_below_navigation_toolbar_fx68.css"; /**/ /* <-- tabs not on top - Fx68+ - Windows/Linux */`

**Comment by Aris-t2** [comment]
Test this one
`@import "./css/tabs/tabs_below_main_content_fx65_macOS.css`
instead of
`@import "./css/tabs/tabs_below_navigation_toolbar_fx68.css"; /**/ /* <-- tabs not on top - Fx68+ - Windows/Linux */`

macOS code did not require Fx68 changes like Windows/Linux code did.

I currently can not test this on macOS myself, but report back, if something changed.

**Comment by nicolaasjan** [comment]
> Test this one
> `@import "./css/tabs/tabs_below_main_content_fx65_macOS.css`
> instead of
> `@import "./css/tabs/tabs_below_navigation_toolbar_fx68.css"; /**/ /* <-- tabs not on top - Fx68+ - Windows/Linux */`
> 
> macOS code did not require Fx68 changes like Windows/Linux code did.
> 
> I currently can not test this on macOS myself, but report back, if something changed.

Now it looks like this:

![screenshot3](https://user-images.githubusercontent.com/14093220/63957383-8fe4a480-ca88-11e9-8489-65f4f88c1c19.png)

Not quite right yet...

**Comment by Aris-t2** [comment]
Add this to your code

```css
#TabsToolbar .tabbrowser-tab {
  max-height: var(--tab-min-height_tnot) !important;
}
```

**Comment by nicolaasjan** [comment]
> Add this to your code
> 
> ```css
> #TabsToolbar .tabbrowser-tab {
>   max-height: var(--tab-min-height_tnot) !important;
> }
> ```

Result:

![screenshot4](https://user-images.githubusercontent.com/14093220/63959532-aab91800-ca8c-11e9-9ef4-182609cc72af.png)

Much better.
Thanks!

The divider under the tabs is thicker; is that as intended?
And the folders in the bookmarks toolbar have changed color to dull grey, or is that as a result of yet another Nightly update I just got?

**Comment by Aris-t2** [comment]
The thicker bar was not intended. Mozilla seems to have added another line/shadow to that area. Are you using a lw-theme?

Try something like
```css
#main-window #TabsToolbar,
#main-window:not([style*='--lwt-header-image']):-moz-lwtheme:-moz-lwtheme-brighttext #TabsToolbar:-moz-lwtheme,
#main-window:not([style*='--lwt-header-image']):-moz-lwtheme-brighttext #TabsToolbar:-moz-lwtheme,
#main-window #navigator-toolbox::after,
#main-window #navigator-toolbox {
  border-bottom: 0px !important;
  box-shadow: unset !important;
}
```

The icons also where changed by Mozilla.

There is an option within this collection to change those icons and it is enabled by default. Not sure if  latest update broke it on macOS.
