### ISSUE TITLE
Reader View Button 

### ISSUE THREAD

**Issue by Infernoflower** [Aris-t2/CustomCSSforFx#228]
Hello, since I updated to Firefox 69, the Reader View button still shows up despite me turning on the code to hide it. Please can you help me fix this?

**Comment by Aris-t2** [comment]
```css
#reader-mode-button {
  display: none !important;
}
```

Please use general discussion thread next time: https://github.com/Aris-t2/CustomCSSforFx/issues/211#issuecomment-527516583
