### ISSUE TITLE
[Firefox 71+][appbutton in titlebar] - navigation toolbar issues

### ISSUE THREAD

**Issue by Aris-t2** [Aris-t2/CustomCSSforFx#231]
The "appbutton in titlebar" feature causes major issues with navigation toolbar on recent Firefox 71 Nightly builds.

A dirty workaround exists, but no general fix. 

**Workaround**
In addition to the current code this has to be added to userChrome.css depending on your setup (fix persists of two parts)

**Part 1**
```css
/* tabs on top + menubar hidden */
#main-window[tabsintitlebar] #nav-bar #PanelUI-button {
  position: relative !important;
  margin-top: -60px !important;
  margin-bottom: 66px !important;
}
```
or
```css
/* tabs on top + menubar visible / tabs not on top + menubar visible / tabs not on top + menubar hidden */
#main-window[tabsintitlebar] #nav-bar #PanelUI-button {
  position: relative !important;
  margin-top: -32px !important;
  margin-bottom: 40px !important;
}
```

**Part 2**
```css
/* adjust nav-bar for appbutton with label / appbutton with label + icon */
#main-window[tabsintitlebar] #nav-bar-customization-target {
  -moz-margin-start: -90px !important;
}
```
or
```css
/* adjust nav-bar for appbutton with icon only */
#main-window[tabsintitlebar] #nav-bar-customization-target {
  -moz-margin-start: -38px !important;
}
```
