### ISSUE TITLE
[Firefox 70] ac_popup_result_separator.css does not work

### ISSUE THREAD

**Issue by Hobbix** [Aris-t2/CustomCSSforFx#238]
"ac_popup_result_separator.css" does not work (Firefox 70).

I use together with "ac_popup_classic_with_two_lines_fx68.css"

**Comment by Aris-t2** [comment]
Will be fixed on next update.

**Comment by Aris-t2** [comment]
```css
.urlbarView-row + .urlbarView-row {
  border-top: 1px solid lightgrey !important;
  border-bottom: 1px solid transparent !important;
}
```
