### ISSUE TITLE
[Firefox 71] compact_mode_reduce_fontsize.css does not work

### ISSUE THREAD

**Issue by circcc** [Aris-t2/CustomCSSforFx#239]
"compact_mode_reduce_fontsize.css" have problem with FF71 Beta.
Reduce text font size in location bar is still working,
but it's not working in search bar anymore.
--------
OS: win7 x86

**Comment by Aris-t2** [comment]
Will be fixed on next update.

```css
#main-window[uidensity="compact"] :-moz-any(.searchbar-textbox, #urlbar,#searchbar) {
  font-size: 12px !important;
}
```
