### ISSUE TITLE
How to make an exception for the "Firefox Button" when the other buttons are displayed with labels?

### ISSUE THREAD

**Issue by hacklex** [Aris-t2/CustomCSSforFx#24]
Hello and thank you for your work! 
I copied your scripts **appbutton_on_navbar_start_position** and **toolbar_mode_icons_and_text** to my userChrome.css. Both worked perfectly, but the **appbutton** looks not quite good in Firefox Developer Edition due to its way too long name. Is there a way to either alter the name to just "Firefox", or to remove the name for that specific button at all?

My current solution is very hacky:
```
#PanelUI-button .toolbarbutton-text {
  width: 48px !important; //this shows "Firefox...", which looks better, but still sad
  content: 'Main Menu' !important; //this has no effect :(
  display: none !important; //this too; 
}
```

Sorry if I'm doing it wrong by posting an issue here, just suggest a way to contact you that is most convenient, if that's okay at all.

Thanks!

**Comment by Aris-t2** [comment]
I know of three ways to solve this issue, although you already mentioned one of them.

**1. Hiding text**
```css
#PanelUI-menu-button .toolbarbutton-text {
  display: none !important;
  visibility: collapse !important;
}
```

**2. Limiting text width**
```css
#PanelUI-menu-button .toolbarbutton-text {
  max-width: 50px !important;
}
```

**3. Replacing text with own label**
```css
#PanelUI-menu-button .toolbarbutton-text {
  display: none !important;
  visibility: collapse !important;
}
#PanelUI-menu-button::after {
  display: block !important;
  content: "Firefox" !important;
}
```
