### ISSUE TITLE
[Firefox 72] compact_mode_reduce_fontsize.css does not work.

### ISSUE THREAD

**Issue by circcc** [Aris-t2/CustomCSSforFx#253]
it's not working with FF 72.0b1.

**Comment by Aris-t2** [comment]
Maybe the preconfigured font size of 12px is not small enough anymore. The code works for me even in Fx73 Nightly. Test this:

```css
#main-window[uidensity="compact"] :-moz-any(.searchbar-textbox, #urlbar,#searchbar) {
  font-size: 8px !important;
}
```
