### ISSUE TITLE
Tab toolbar left/right scroll buttons are white for Fx71

### ISSUE THREAD

**Issue by noresk1** [Aris-t2/CustomCSSforFx#260]
1. Describe the issue
Tab toolbar left/right scroll buttons are white for Fx71; however, the 'open a new tab' and 'list all tabs' buttons are still black as before

2. What should have happened instead?
In all previous versions the left/right tab toolbar scroll buttons were black

3. Steps to reproduce the issue?

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)
![image](https://user-images.githubusercontent.com/58830974/70755414-61b96680-1cff-11ea-9170-855a29774b9b.png)
![image](https://user-images.githubusercontent.com/58830974/70755451-7d247180-1cff-11ea-82ca-94ab09ac9f1c.png)

5. System information
- OS & OS version: Win 7 SP1
- OS theme name: default
- DPI / HiDPI resolution: 
- Firefox version: 71.0
- Firefox theme / lw-theme: default
- This projects settings the issue occurs with: tab toolbar below navigation

**Comment by Aris-t2** [comment]
This will be fixed on next update.

```css
/* Fx71+ fix */
:-moz-any(.tabs-newtab-button,#tabs-newtab-button,.scrollbutton-up,.scrollbutton-down):not(:-moz-lwtheme),
:-moz-any(.tabs-newtab-button,#tabs-newtab-button,.scrollbutton-up,.scrollbutton-down):-moz-lwtheme-darktext,
.tabbrowser-arrowscrollbox::part(scrollbutton-up),
.tabbrowser-arrowscrollbox::part(scrollbutton-down) {
  fill: var(--classic_squared_tabs_new_tab_icon_color) !important;
  color: var(--classic_squared_tabs_new_tab_icon_color) !important;
}
```

**Comment by noresk1** [comment]
Thank you, thank you! I applied this and it now works beautifully!

**Comment by noresk1** [comment]
Hello,

 

Not sure if you are monitoring via this email or whether I should submit new issue through GitHub, but the tab toolbar left/right scroll buttons are showing up again as being white on Firefox 76.0.1.  I saw you had a fix for Fx76 in the css file for tabs_below_nav_68, but I upgraded from Fx75 to Fx76.0.1.

 

Greatly appreciate any time you can lend to fixing this issue.

 

Thanks!

**Comment by Aris-t2** [comment]
Yes,  I still get notification even, after and issue gets closed:
```css
toolbarbutton#scrollbutton-up[part="scrollbutton-up"],
toolbarbutton#scrollbutton-down[part="scrollbutton-down"] {
  fill: var(--classic_squared_tabs_new_tab_icon_color) !important;
  color: var(--classic_squared_tabs_new_tab_icon_color) !important;
}
```
