### ISSUE TITLE
ac_popup_classic_with_two_lines_fx68.css

### ISSUE THREAD

**Issue by Thalon77** [Aris-t2/CustomCSSforFx#268]
1. Describe the issue

Something changed in the way popup results are displayed onscreen using the option I wrote in the subject, see attached Screen2

2. What should have happened instead?

The apparance should be different (at least it always was so since I began using the CSS), with thinner fonts in the first line, smaller blue fonts in the second line and a bit more space between results, see the attached Screen1

3. Steps to reproduce the issue?

Switching between V 2.90 and V2.96 like I did, something changed between those two releases.

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)

![Screen1](https://user-images.githubusercontent.com/33811707/71972784-b3291880-320d-11ea-8242-e6d2c70e864a.jpg)
![Screen2](https://user-images.githubusercontent.com/33811707/71972790-b58b7280-320d-11ea-8608-57a814aaf264.jpg)

5. System information
- OS & OS version: Win 10pro
- DPI / HiDPI resolution: 1920x1080
- Firefox version: V72
- Firefox theme / lw-theme: using only crystal Icons from the CSS.

**Comment by Aris-t2** [comment]
Font size changed within the files. You an configure it inside `general_variables.css` file.

**Comment by motfis** [comment]
Firefox updates becomes a bit anoying.... now everytime they update, the custom css is need to be changed...
My problem is not classic 2 lines, but for ac_popup_default_with_two_lines_fx68. it is not shown as 2 lines. could you fix it?
![Screenshot (559)](https://user-images.githubusercontent.com/8572695/72002522-de305e00-3247-11ea-8246-2d6947bb9012.png)

**Comment by Aris-t2** [comment]
Use this instead of `ac_popup_default_with_two_lines_fx68.css` in Fx72 (it will add this as a new option on next update):

```css
.urlbarView .urlbarView-results > .urlbarView-row > .urlbarView-row-inner {
  flex-wrap: wrap !important;
}
.urlbarView .urlbarView-results > .urlbarView-row > .urlbarView-row-inner > .urlbarView-no-wrap {
  max-width: 100% !important;
  flex-basis: 100% !important;
}
.urlbarView .urlbarView-results > .urlbarView-row[has-url] > .urlbarView-row-inner > .urlbarView-url {
  margin-top: 2px !important;
  padding-inline-start: calc(6px + 2px + 16px) !important;
}
.urlbarView[actionoverride] .urlbarView-results > .urlbarView-row[has-url] > .urlbarView-row-inner > .urlbarView-no-wrap > .urlbarView-title-separator,
.urlbarView .urlbarView-results > .urlbarView-row[has-url]:not([type$=tab]) > .urlbarView-row-inner > .urlbarView-no-wrap > .urlbarView-title-separator,
.urlbarView .urlbarView-results > .urlbarView-row[type=remotetab]:not([selected]):not(:hover) {
  display: none !important;
}

#urlbar-results {
  --item-padding-start: 0 !important;
  --item-padding-end: 0 !important;
}
```
