### ISSUE TITLE
Tabs have white background

### ISSUE THREAD

**Issue by laz2727** [Aris-t2/CustomCSSforFx#27]
The entire tabs toolbar has a white background and i can't seem to remove it (i've successfully removed backgrounds for the rest of the toolbar).
![2017-11-14 22 59 45](https://user-images.githubusercontent.com/2369751/32796191-ed6de538-c965-11e7-92ae-74e361365956.png)

And a sorta unrelated question: where do you even find all these values to plug into userChrome?

**Comment by Aris-t2** [comment]
Try

```css
#main-window #navigator-toolbox #TabsToolbar:-moz-lwtheme{
  background: unset !important;
}
```
