### ISSUE TITLE
Context Menu CSS Help

### ISSUE THREAD

**Issue by Mike-Reddick** [Aris-t2/CustomCSSforFx#276]
How I can put extensions entries above the firefox native entries, on context menu, put extensions entries on top of context menu, someone can post the CSS please?

extension entry 1
extension entry 2
extension entry 3
----------------------
native entry 1
native entry 2
native entry 3

**Comment by Aris-t2** [comment]
The pseudo code for your example would look like this:
```css
#id_of_extension_entry_1 {
  -moz-box-ordinal-group: 0 !important;
}

#id_of_extension_entry_2 {
  -moz-box-ordinal-group: 1 !important;
}

#id_of_extension_entry_3 {
  -moz-box-ordinal-group: 2 !important;
}

#id_of_native_entry_1 {
  -moz-box-ordinal-group: 3 !important;
}

#id_of_native_entry_2 {
  -moz-box-ordinal-group: 4 !important;
}

#id_of_native_entry_3 {
  -moz-box-ordinal-group: 5 !important;
}
```

Keep in mind changing context menuitems order might not always work even, if your code is correct.

Use the general support thread for questions next time.
[[!] GENERAL discussion, feedback, questions belong here! (v10)](https://github.com/Aris-t2/CustomCSSforFx/issues/273)
