### ISSUE TITLE
[Fx72+] autohiding sidebar

### ISSUE THREAD

**Issue by Homie51** [Aris-t2/CustomCSSforFx#277]
Hi friends

Since the update  to Firefox 72 some codes don't work.

For exemple I often use "the mouse-over boomarks code" (the lateral panel of bookmars is hidden and we hover over the left of the screen to display the bookmarks panel)... with theses lines of code.

Sorry for my poor english, I'm just a french guy :D

`/*survol de la souris volet bookmarks*/

:root {
  --sidebar-hover-width: 8px;
  --sidebar-visible-width: 300px;
}

#sidebar-box {
  position: relative !important;
  overflow-x: hidden !important;
  margin-right: calc(var(--sidebar-hover-width) * -1) !important;
  left: var(--sidebar-hover-width) !important;
  min-width: var(--sidebar-hover-width) !important;
  max-width: var(--sidebar-hover-width) !important;
  opacity: 0 !important;
}

#sidebar-box:hover {
  margin-right: calc(var(--sidebar-visible-width) * -1) !important;
  left: var(--sidebar-visible-width) !important;
  min-width: var(--sidebar-visible-width) !important;
  max-width: var(--sidebar-visible-width) !important;
  opacity: 1 !important;
}

#sidebar {
  opacity: 0 !important;
}

#sidebar:hover {
  opacity: 1 !important;
}

/* #sidebar-header is hidden by default, change "none" to "inherit" to restore it. */
#sidebar-header {
  display: none !important;
}

/* #sidebar-splitter styles the divider between the sidebar and the rest of the browser. */
#sidebar-splitter {
}`

**Comment by Aris-t2** [comment]
Something like this might work as a workaround (insert variables, if needed):

```css
#sidebar-box #sidebar {
  min-width: 8px !important;
  width: 8px !important;
  max-width: 8px !important;
  opacity: 0 !important;
}

#sidebar-box:hover #sidebar {
  min-width: 300px !important;
  width: 300px !important;
  max-width: 300px !important;
  opacity: 1.0 !important;
}

#sidebar-box #sidebar-header {
  visibility: collapse !important;
}
#sidebar-box:hover #sidebar-header {
  visibility: visible !important;
}
```

Please use the [GENERAL discussion thread](https://github.com/Aris-t2/CustomCSSforFx/issues/273) for questions next time.

**Comment by Homie51** [comment]
Hi

Thank you that's almost works ;)

The lonely problem: the lateral panel push the page (so that make it smaller instead to cover the left part)

**Comment by Aris-t2** [comment]
There is always room for improvement ;)

```css
#sidebar-box #sidebar {
  min-width: 8px !important;
  width: 8px !important;
  max-width: 8px !important;
  opacity: 0 !important;
  position: absolute !important;
  display: block !important;
}

#sidebar-box:hover #sidebar {
  min-width: 300px !important;
  width: 300px !important;
  max-width: 300px !important;
  opacity: 1.0 !important;
}


#sidebar-box #sidebar-header {
  visibility: collapse !important;
}
#sidebar-box:hover #sidebar-header {
  visibility: visible !important;
}

#sidebar-box {
  z-index: 1000 !important;
  margin-right: -8px !important;
  position: relative !important;
  opacity: 0 !important;
}

#sidebar-box:hover {
  margin-right: unset !important;
  position: relative !important;
  opacity: 1.0 !important;
}

#sidebar-box ~ #appcontent {
  margin-left: -8px !important;
}

#sidebar-box:hover ~ #appcontent {
  margin-left: unset !important;
}
```

**Comment by Homie51** [comment]
Thank you for your work ;) but no effect :D, the panel always "push" the page and make ot smaller...

**Comment by Aris-t2** [comment]
Sorry, I misunderstood you before.You were looking for something that stays on top of the page, right?

**Comment by Aris-t2** [comment]
Alright, here is the one incl. variables ;)


```css
:root{
  --sidebar-hover-width: 8px;
  --sidebar-visible-width: 300px;
}

#sidebar-box #sidebar {
  min-width: var(--sidebar-hover-width) !important;
  width: var(--sidebar-hover-width) !important;
  max-width: var(--sidebar-hover-width) !important;
  opacity: 0 !important;
  position: absolute !important;
  display: block !important;
}

#sidebar-box:hover #sidebar {
  min-width: var(--sidebar-visible-width) !important;
  width: var(--sidebar-visible-width) !important;
  max-width: var(--sidebar-visible-width) !important;
  opacity: 1.0 !important;
}

#sidebar-box #sidebar-header {
  visibility: collapse !important;
}
#sidebar-box:hover #sidebar-header {
  visibility: visible !important;
}

#sidebar-box {
  z-index: 1000 !important;
  -moz-margin-end: calc(-1 * var(--sidebar-hover-width)) !important;
  position: relative !important;
  opacity: 0 !important;
}

#sidebar-box:hover {
  -moz-margin-end: unset !important;
  opacity: 1.0 !important;
}

#sidebar-box ~ #appcontent {
  -moz-margin-start: calc(-1 * var(--sidebar-hover-width)) !important;
}

#sidebar-box:hover ~ #appcontent {
  -moz-margin-start: calc(-1 * (var(--sidebar-visible-width) + var(--sidebar-hover-width))) !important;
}
```
