### ISSUE TITLE
[Fx72+][Add-ons manager] squeezed tools menu when using buttons + icons

### ISSUE THREAD

**Issue by bege10** [Aris-t2/CustomCSSforFx#279]
1. Describe the issue
addonlists_show_buttons_instead_of_menu_popup_fx72.css and addonlists_replace_button_labels_with_icons_fx72.css make the tools menu in add-ons manager look very squeezed. To me this looks ugly.
If this is intentionally, can you, please, put the code for this change in a separate file?

2. What should have happened instead?
Don't change the menu look.

3. Steps to reproduce the issue?
Activate/deactivate the two files.

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)

![Screenshot_196](https://user-images.githubusercontent.com/1184237/74093834-f78f2900-4ad7-11ea-842d-100994cb1f83.png)

![Screenshot_197](https://user-images.githubusercontent.com/1184237/74093835-f827bf80-4ad7-11ea-8ac7-de70b514a168.png)

5. System information
- OS & OS version: Windows 10 Professional 64 bit
- OS theme name: dark, transparent
- DPI / HiDPI resolution: 1920x1080
- Firefox version: 72.0.2
- Firefox theme / lw-theme: Standard
- This projects settings the issue occurs with: 

Thank you very much for your work.

**Comment by Aris-t2** [comment]
Mozilla crippled the ability to customize add-on managers content with every recent update more and more.

The "buttons" used by the add-on item and the content of the top options button share a huge amount of code without giving the possibility to distinguish it. Workarounds on top of other workarounds unfortunately create glitches like seen on your screenshots.

I will try to fix this, but can't make any promises. The following code improves things in my tests, but may not offer the same result on your config.

Replace the content of `addonlists_replace_button_labels_with_icons_fx72.css` with this code

```css
/* Firefox Quantum userChrome.css tweaks ************************************************/
/* Github: https://github.com/aris-t2/customcssforfx ************************************/
/****************************************************************************************/


@-moz-document url-prefix(chrome://mozapps/content/extensions/extensions.xul), url-prefix(about:addons),url-prefix(chrome://mozapps/content/extensions/aboutaddons.html) {
	

	html {
	  --addon-page-options-width: 340px;
	}
	
	/* <some> locales require adjustments */
	html:-moz-any([lang="ru"],[lang="it"],[lang="fr"],[lang="el"]) {
	  --addon-page-options-width: 440px;
	}
	
	html[lang*="es-"] {
	  --addon-page-options-width: 460px;
	}
	
	link:-moz-any([href$="panel-item.css"],[href$="panel-list.css"]) ~ button {
	  width: 22px !important;
	  height: 22px !important;
	  padding: 0 !important;
	  padding-inline-end: 0px !important;
	  background-position: center !important;
	  background-color: unset !important;
	}
	
	link:-moz-any([href$="panel-item.css"],[href$="panel-list.css"]) ~ button label:not([accesskey]) {
	  visibility: hidden !important;
	}
	
	link:-moz-any([href$="panel-item.css"],[href$="panel-list.css"]) ~ button label[accesskey]:hover {
	  background: var(--grey-30);
	}
	
	link:-moz-any([href$="panel-item.css"],[href$="panel-list.css"]) ~ button label[accesskey] {
	  padding-top: 1px !important;
	  padding-bottom: 1px !important;
	}
	
	addon-page-options panel-list panel-item[accesskey][checked] {
	  background: url("chrome://global/skin/icons/check.svg") 2px no-repeat !important;
	}

	panel-item[action="toggle-disabled"][data-l10n-id="disable-addon-button"] {
	  --icon: url("chrome://browser/skin/zoom-out.svg") !important;
	}
	
	panel-item[action="toggle-disabled"][data-l10n-id="enable-addon-button"] {
	  --icon: url("chrome://browser/skin/zoom-in.svg") !important;
	}
	
	panel-item[data-l10n-id="remove-addon-button"] {
	  --icon: url("chrome://global/skin/icons/delete.svg") !important;
	}

	panel-item[data-l10n-id="install-update-button"] {
	  --icon: url("chrome://global/skin/icons/update-icon.svg") !important;
	}
	
	panel-item[data-l10n-id="preferences-addon-button"] {
	  --icon: url("chrome://browser/skin/settings.svg") !important;
	}
	
	panel-item[data-l10n-id="report-addon-button"] {
	  --icon: url("chrome://global/skin/icons/warning.svg") !important;
	}
	
	panel-item[data-l10n-id="expand-addon-button"],
	panel-item[data-l10n-id="manage-addon-button"] {
	  --icon: url("chrome://browser/skin/chevron.svg") !important;
	}
	
	panel-item[data-l10n-id="ask-to-activate-button"] {
	  --icon: url("chrome://browser/skin/zoom-in.svg") !important;
	}
	
	panel-item[data-l10n-id="always-activate-button"] {
	  --icon: url("chrome://browser/skin/zoom-in.svg") !important;
	}
	
	panel-item[data-l10n-id="never-activate-button"] {
	  --icon: url("chrome://browser/skin/zoom-out.svg") !important;
	}

	panel-item[action="toggle-disabled"][data-l10n-id="disable-addon-button"]:hover,
	panel-item[action="toggle-disabled"][data-l10n-id="enable-addon-button"]:hover,
	panel-item[data-l10n-id="remove-addon-button"]:hover,
	panel-item[data-l10n-id="install-update-button"]:hover,
	panel-item[data-l10n-id="preferences-addon-button"]:hover,
	panel-item[data-l10n-id="report-addon-button"]:hover,
	panel-item[data-l10n-id="expand-addon-button"]:hover,
	panel-item[data-l10n-id="manage-addon-button"]:hover,
	panel-item[data-l10n-id="ask-to-activate-button"]:hover,
	panel-item[data-l10n-id="always-activate-button"]:hover,
	panel-item[data-l10n-id="never-activate-button"]:hover {
	  background-color: var(--grey-30) !important;
	}

	addon-page-options panel-list {
	  min-width: unset !important;
	  width: auto !important;
	  max-width: var(--addon-page-options-width) !important;
	  z-index: 1000 !important;
	}
	
	addon-page-options panel-list panel-item {
	  min-width: calc(var(--addon-page-options-width) - 20px) !important;
	  width: 320px !important;
	}

	link:-moz-any([href$="panel-item.css"],[href$="panel-list.css"]) ~ button label[accesskey] {
	  padding-inline-start: 20px !important;
	  padding-top: 3px !important;
	  padding-bottom: 3px !important;
	  min-width: calc(var(--addon-page-options-width) - 10px) !important;
	  width: calc(var(--addon-page-options-width) - 10px) !important;
	}

	addon-page-options panel-list panel-item[accesskey][checked] {
	  background: url("chrome://global/skin/icons/check.svg") 5px no-repeat !important;
	}

}
```

Btw, thanks for the proper bug report.

**Comment by bege10** [comment]
Thank you very much for the workaround.
With addonlists_replace_button_labels_with_icons_fx72.css it looks so:

![Screenshot_198](https://user-images.githubusercontent.com/1184237/74180915-9cc51100-4c40-11ea-8efe-7085600b71ea.png)

With additionally addonlists_show_buttons_instead_of_menu_popup_fx72.css so:

![Screenshot_200](https://user-images.githubusercontent.com/1184237/74181024-cda54600-4c40-11ea-924d-1f36ed1c8e22.png)

So this code also has an impact on the menu.

Why I would like this menu not to be altered at all is because I add icons to the menu entries with this code (from Endor in camp-firefox.de forum):

```
#page-options > panel-list:nth-child(1) > panel-item:nth-child(1)::before {
content: '';
display: block;
width: 16px;
height: 16px;
background-image: url('../../../../../icons/Bild5.png');
background-size: 16px 16px !important;
margin-left: 15px;
margin-right: -31px;}

#page-options > panel-list:nth-child(1) > panel-item:nth-child(2)::before {
content: '';
display: block;
width: 16px;
height: 16px;
background-image: url('../../../../../icons/Bild61.png');
background-size: 16px 16px !important;
margin-left: 15px;
margin-right: -31px;}

#page-options > panel-list:nth-child(1) > panel-item:nth-child(4)::before {
content: '';
display: block;
width: 16px;
height: 16px;
background-image: url('../../../../../icons/Bild3.png');
background-size: 16px 16px !important;
margin-left: 15px;
margin-right: -31px;}

#page-options > panel-list:nth-child(1) > panel-item:nth-child(5)::before {
content: '';
display: block;
width: 16px;
height: 16px;
background-image: url('../../../../../icons/Bild66.ico');
background-size: 16px 16px !important;
margin-left: 15px;
margin-right: -31px;}


/* #page-options > panel-list:nth-child(1) > panel-item:nth-child(7) {
fill: transparent !important;}

#page-options > panel-list:nth-child(1) > panel-item:nth-child(7)::before {
content: '';
display: block;
width: 16px;
height: 16px;
background: url('https://raw.githubusercontent.com/Endor8/CSS/master//Icons/Bild62.png') no-repeat !important;
background-size: 18px 18px !important;
margin-left: 16px;
margin-right: -32px;
margin-bottom: 3px;}

#page-options > panel-list:nth-child(1) > panel-item:nth-child(7):not([checked])::before {
content: 'Nicht die';
font-size: 14px;
padding-left: 22px !important;
padding-right: 35px !important;
padding-top: 1px !important;
padding-bottom: 2px !important;
display: block;
width: 16px;
height: 16px;
background: url('../../../../../icons/Bild63.png') no-repeat !important;
background-size: 18px 18px !important;
margin-left: 18px;
margin-right: -32px;}
 */


#page-options > panel-list:nth-child(1) > panel-item:nth-child(8)::before {
content: '';
display: block;
width: 16px;
height: 16px;
background-image: url('../../../../../icons/Bild64.png');
background-size: 16px 16px !important;
margin-left: 15px;
margin-right: -31px;}

#page-options > panel-list:nth-child(1) > panel-item:nth-child(10)::before {
content: '';
display: block;
width: 16px;
height: 16px;
background-image: url('../../../../../icons/Bild67.png');
background-size: 16px 16px !important;
margin-left: 15px;
margin-right: -31px;}
```

With this code but without your code it looks like this:

![Screenshot_201](https://user-images.githubusercontent.com/1184237/74181460-a56a1700-4c41-11ea-937f-3deba0e2b97a.png)

With addonlists_replace_button_labels_with_icons_fx72.css so:

![Screenshot_202](https://user-images.githubusercontent.com/1184237/74181861-4789ff00-4c42-11ea-8f20-bda2d30f5d59.png)

And with addonlists_show_buttons_instead_of_menu_popup_fx72.css the icons vanish.

**Comment by Aris-t2** [comment]
I agree, it would be better not to touch the menu at all, but there is no way to achieve the buttons/icon then.
You can however extend the space between the edge and the label so icons won't overlap with the text.

```css
link:-moz-any([href$="panel-item.css"],[href$="panel-list.css"]) ~ button label[accesskey] {
  padding-inline-start: 40px !important;
}
```

Also try to add this to increase popups width in German locale:

```css
html[lang="de"] {
  --addon-page-options-width: 370px;
}
```

This should also remove the doubled check mark:

```css
addon-page-options panel-list panel-item[accesskey][checked] {
  background: unset !important;
}
```
