### ISSUE TITLE
Megabar moves above the back button (backforward connected option)

### ISSUE THREAD

**Issue by samehb** [Aris-t2/CustomCSSforFx#287]
**1. Describe the issue:** .megabar pops above the the back button when custom_backforward_connected_to_location_bar.css is used. It happens when the bar becomes active.

**2. What should have happened instead?** It should go behind the back button always.

**3. Steps to reproduce the issue?**
1. Enable the megbar.
2. Enable the custom_backforward_connected_to_location_bar.css + custom_backforward_connected_to_location_bar_fx71_extra.css options.
3. Click the megabar and type.

**4. SCREENSHOTS** with/without this projects files (drag & drop images into this post)

![1](https://user-images.githubusercontent.com/4786100/78464138-5810a000-76ee-11ea-9acc-b27d81908ab1.png)
![2](https://user-images.githubusercontent.com/4786100/78464139-5941cd00-76ee-11ea-821c-b5acc1799489.png)

**5. System information**
**- latest CustomCSSforFx files (yes / no [no support, if 'no']):** Yes.
**- OS & OS version:** Windows 7 x64.
**- OS theme (if not default):** Default.
**- Firefox version:** 74
**- Firefox theme / lw-theme:** Default

Here is the fix:

```css
/* The reason I am starting with z-index 3, is that the active tab has a z-index of 2. */
#main-window .megabar {
  z-index: 3 !important;
}

#main-window:not([uidensity=compact]) #nav-bar #back-button {
  z-index: 5 !important;
  position: relative !important;
  ...
}

#main-window:not([uidensity=compact]):not([uidensity=touch]) #nav-bar #forward-button[disabled] + #urlbar-container::before {
  ...
  z-index: 4 !important;
}

#main-window:not([uidensity=compact]):not([uidensity=touch]) #nav-bar #back-button + #forward-button:not([disabled])::before {
  ...
  z-index: 4 !important;
}
```

By the way, I am personally using a single absolute overlay on my customized project, instead of the two above. I am also using the backforward connected solution with compact layout.  The fix above is compatible with the project without my customizations, though.

There is also a small issue with icon spacing when using the backforward connected option. When the forward button is hidden, the tracking/identity icons are very close together. You can see it at the screenshot above.  Here is my fix:

```css
#main-window[uidensity=compact] #nav-bar #back-button+#forward-button[disabled]+#urlbar-container #urlbar-input-container:not([pageproxystate="invalid"])>#tracking-protection-icon-container {
  padding-inline-start: 17px !important;
}

#main-window[uidensity=compact] #nav-bar #back-button+#forward-button[disabled]+#urlbar-container #urlbar-input-container:not([pageproxystate="invalid"])>#tracking-protection-icon-container:not([hidden])+#identity-box {
  padding-inline-start: 31px !important;
  margin-inline-start: -29px !important;
}
```

You may need to adjust those values because those are based on my personal customizations.

Regards.
