### ISSUE TITLE
FX76 tabs below nav bar issue MacOS

### ISSUE THREAD

**Issue by dinkydogs** [Aris-t2/CustomCSSforFx#300]
after updating to Firefox 76 my tabs lost the line at the bottom of the tab. this is using the option of "css/tabs/tabs_below_navigation_toolbar_fx74_macOS.css" 

<img width="295" alt="image" src="https://user-images.githubusercontent.com/63877723/81147619-81ac2980-8f2f-11ea-93c8-6e07d42f7b7a.png">

but using this option the line is present at the bottom "css/tabs/tabs_below_navigation_toolbar_fx74_macOS_default_tabs.css"

<img width="385" alt="image" src="https://user-images.githubusercontent.com/63877723/81147652-925c9f80-8f2f-11ea-8af9-8f6a1a1242a9.png">

This didn't happen in Firefox75.

Also, what is the difference between the two options? looking at the tabs I can't see a difference.

Thank you

**Comment by Aris-t2** [comment]
This will be fixed on next update.

Use this code till then:

```css
#tabbrowser-tabs #tabbrowser-arrowscrollbox {
  margin-top: -1px !important;
  margin-bottom: 1px !important;
}
```
