### ISSUE TITLE
scrollbutton not hidden in multirow

### ISSUE THREAD

**Issue by zolstarym** [Aris-t2/CustomCSSforFx#302]
Add all information required in 1-5 and delete this line and everything above it before submitting.

1. Describe the issue
Scrollbuttons are not hidden when multirow is enabled:
@import "./css/tabs/tabs_multiple_lines_fx71.css"; /**/  /* Fx 71+ */
see attached pic
![Screenshot from 2020-05-07 12-40-57](https://user-images.githubusercontent.com/1832149/81346304-4fa5df00-9077-11ea-8e8b-205dd65a73fe.png)
When the tabs reach the end of available space, the scrollbuttons appear above and below the tab bar.
In tabs area on userchrome, @import "./css/tabs/tab_close_hidden.css"; /**/ is also enabled
and in general variables.css:
  /* for tabs_multiple_lines.css and tabs_multiple_lines_v2.css */
  --tab_min_width_mlt: 60px !important;
  --tab_max_width_mlt: 300px !important;

Using version 3.1.3

5. System information
- latest CustomCSSforFx files (yes / no [no support, if 'no']):
- OS & OS version: 
Linux mint 19.3
- OS theme (if not default): 
- DPI / HiDPI resolution: 
- Firefox version: 76 
- Firefox theme / lw-theme: 
- This projects 'settings' the issue occurs with:

**Comment by Aris-t2** [comment]
```css
link[href$="arrowscrollbox.css"] ~ #scrollbutton-up,
link[href$="arrowscrollbox.css"] ~ #scrollbutton-down {
  display: none !important;
}
```
