### ISSUE TITLE
Is there a way to remove the icon button that appeares in tabs?

### ISSUE THREAD

**Issue by gabri25ele** [Aris-t2/CustomCSSforFx#307]
I don't find in userchrome.css so I think there isn't an option yet to this.

**Comment by Aris-t2** [comment]
```css
.tabbrowser-tab:not([pinned]) .tab-icon-image:not([src]),
.tab-throbber,
.tab-icon-pending,
.tab-icon-image,
.tab-sharing-icon-overlay,
.tab-icon-overlay {
  display: none !important;
}
```
