### ISSUE TITLE
"Search with" is still shown when using ac_popup_searchwith_and_visit_items_hidden.

### ISSUE THREAD

**Issue by AndersOhrt** [Aris-t2/CustomCSSforFx#32]
Hi!

I'm using ac_popup_searchwith_and_visit_items_hidden.css to hide the "Search with" and "Visit" links. The "Visit" one disappears, but the "Search with Google" is still there. I'm using Firefox 57.

**Comment by Aris-t2** [comment]
Post a screenshot.

I hope you don't meant the search content at popups bottom, because that stuff is handled by "browser.urlbar.oneOffSearches" preferene.

**Comment by AndersOhrt** [comment]
It's this one:

![searchwith](https://user-images.githubusercontent.com/6324231/32842953-cd7f0afe-ca1e-11e7-8cba-97183e014ce6.jpg)

I've already set oneOffSearches to false.

**Comment by Aris-t2** [comment]
Looks like this for me before and after "enabling" ac_popup_searchwith_and_visit_items_hidden.css :
![1](https://user-images.githubusercontent.com/6013569/32844363-7f911c7a-ca22-11e7-883e-373d605f770d.png)

![2](https://user-images.githubusercontent.com/6013569/32844364-82128b82-ca22-11e7-8069-b5dfe49cd811.png)

Make sure you are only using this projects files and do not combine any CSS code with previous custom/own code while testing.

This code is used by that option:
```css
/* Hide "Visit/Search" items */
#PopupAutoCompleteRichResult richlistitem:first-of-type:-moz-any([type*="heuristic"],[actiontype="searchengine"],[actiontype="visiturl"],[actiontype="keyword"],[actiontype="switchtab"]),
#PopupAutoCompleteRichResult richlistitem[anonid="type-icon-spacer"] {
  display: none !important;
}

#PopupAutoCompleteRichResult .autocomplete-richlistbox {
  min-height: 0 !important;
  height: auto !important;
}

```
