### ISSUE TITLE
Findbar doesn't appear on top left corner

### ISSUE THREAD

**Issue by iG8R** [Aris-t2/CustomCSSforFx#325]
1. Describe the issue
Findbar doesn't appear neither on top left corner nor anywhere else despite selecting any css with "on_top" part in its name.

5. System information
- latest CustomCSSforFx files (yes / no [no support, if 'no']): yes 3.1.7
- OS & OS version: Windows 10 64bit Pro
- OS theme (if not default): Default
- DPI / HiDPI resolution: 150% 3840x2160
- Firefox version: 84.0 (64-bit)
- Firefox theme / lw-theme: default
- This projects 'settings' the issue occurs with: findbar_on_top.css

**Comment by 2BeeOrNot** [comment]
Try deleting or commenting out the following line in findbar_on_top.css:
display: flex !important;
Seems to work.

**Comment by iG8R** [comment]
Thanks. It works but not like it was before. Now the Findbar shifts entire page downwards but previous one was overlapped with it.

**Comment by MarkRH** [comment]
Yeah, same thing here.  It actually shows up as a single black line right above the bottom window border:

![image](https://user-images.githubusercontent.com/8035962/102570236-8c759200-40ac-11eb-8906-100c21cadf7f.png)

**Comment by millerdl** [comment]
> Thanks. It works but not like it was before. Now the Findbar shifts entire page downwards but previous one was overlapped with it.

I had the same problem and tried the fix suggested by @iG8R and got the same shift.  Still it's way better than not having the find capability at all.

**Comment by Akkerman74** [comment]
I was saved by editing the line:
margin-top: -1px !important;    --->   margin-top: -860px !important;

**Comment by Aris-t2** [comment]
The findbar was moved to another position, so the old solution does not work anymore.
There is still a way to achieve the findbar on top by modifying the code inside `findbar_on_top.css`, but the value of 86px in this example is not perfect for every configuration. It has to be adjusted depending on the size/height of the top toolbars. Next update will offer "default" top findbar, which is not on top of the web content anymore.

```css
:-moz-any(.browserContainer,#viewSource) :-moz-any(findbar,#FindToolbar) {
  -moz-box-ordinal-group: 0;
  position: fixed !important;
  display: flex !important;
  /*margin-top: -1px !important;*/ /* removed */
  top: 86px !important;  /* added */
  box-shadow: unset !important;
  border: 1px solid #e1e1e2 !important;
  border-top: 0px solid transparent !important;
  border-radius: 0 0 3px 3px;
  transition-property: margin-top, opacity, visibility !important;
  background-image: unset !important;
}
```

The `margin-top` fix by @Akkerman74 works in a similar way.
