### ISSUE TITLE
[Fx84+] url colored?

### ISSUE THREAD

**Issue by gabri25ele** [Aris-t2/CustomCSSforFx#326]
I have the URL text colored.

![Immagine](https://user-images.githubusercontent.com/33927879/102710842-88689080-42b5-11eb-9bd6-a98042d51444.png)

possible to have not colored?
is it related to some other settings (colored)?
I can't find any voice with browser.urlbar

**Comment by Aris-t2** [comment]
Unfortunately urlbars text color is not just modified by CSS anymore.

Try this, it may improve the situation a bit:

```css
#urlbar-input,
#urlbar-input * {
  color: black !important;
}
```
