### ISSUE TITLE
FF45-style Download Icon reverts during downloads

### ISSUE THREAD

**Issue by IdrisQe** [Aris-t2/CustomCSSforFx#331]
1. Describe the issue
FF45 download icon does not function correctly on FF78 ESR (Waterfox G3.1.0)
When downloading a file, icon reverts until you click when download is complete to reset icon to default state.

2. What should have happened instead?
Icon would ideally have a FF45 style icon for proceeding downloads as well.
(Unsure if this has been tried and deemed impossible, or if this is a bug)

3. Steps to reproduce the issue?
-Set icon appearance to FF45
-Download a file

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)
![gif](https://user-images.githubusercontent.com/40530630/107573722-c2159380-6ba2-11eb-8f60-37f6d41948b0.gif)

5. System information
- latest CustomCSSforFx files (yes / no [no support, if 'no']): Yes
- OS & OS version: Win10 Home 1909
- DPI / HiDPI resolution: 1920x1080
- Firefox version: 78 ESR (Waterfox G3.1.0)
- Firefox theme / lw-theme: Default?
- This projects 'settings' the issue occurs with: Firefox 45 Icon appearance

**Comment by Aris-t2** [comment]
Unfortunately this is intended behavior.
Old/classic icons do not offer same features the "new/current" icon does.

**Comment by IdrisQe** [comment]
Oh, so it's not possible to replace the "in progress" icons too? Or even just stop them from showing and have a static icon?
I know it's such a minor thing but this'll drive me up the wall, so I guess I might as well get used to the new icon styles.

**Comment by Aris-t2** [comment]
It should be possible to alter the code. I have not looked into it yet.

**Comment by Aris-t2** [comment]
Add this code to your `my_userChrome.css` or `userChrome.css` file:

```css
#downloads-indicator-progress-outer,
#downloads-button[progress] > .toolbarbutton-badge-stack > #downloads-indicator-anchor > #downloads-indicator-progress-outer,
#downloads-indicator-icon,
#downloads-indicator-progress-inner {
  background: -moz-image-rect(url("./image/toolbar_fx45.png"), 0, 198, 18, 180) center no-repeat !important;
  list-style-image: none !important;
}

#downloads-notification-anchor[notification="start"] > #downloads-indicator-notification,
#downloads-button[notification="finish"] > .toolbarbutton-badge-stack > #downloads-indicator-anchor > #downloads-indicator-icon,
#downloads-button[notification="start"] > .toolbarbutton-badge-stack > #downloads-indicator-anchor > #downloads-indicator-icon,
#downloads-button[notification="finish"] > .toolbarbutton-badge-stack > #downloads-indicator-anchor > #downloads-indicator-icon {
  animation-name: unset !important;
}

#downloads-notification-anchor,
#downloads-indicator-notification {
  display: none !important;
}
```
