### ISSUE TITLE
[Firefox 88+] url menu is uglier again, dunno why + ctrl-F is invisible + help figuring out few code segments, please?

### ISSUE THREAD

**Issue by Nyekomimi** [Aris-t2/CustomCSSforFx#342]
As seen here: http://prntscr.com/11ww03s

I dunno what to do. Some of settings I've been using to make Firefox look good again were no longer options in newest version of custom, such as:
@import "./css/locationbar/locationbar_adjustments.css"; /**/
@import "./css/locationbar/locationbar_border_roundness.css"; /**/
@import "./css/locationbar/dropmarker_at_the_end.css"; /**/
@import "./css/locationbar/dropmarker_visible.css"; /**/ /* Windows only */

Other issue - ctrl+f is just invisible for me. Can't really attach screenshot of something that's not visible >.< Ensured that all my custom code is gone before submitting it - with just the file you provided it's still gone.

As side note, is there any chance someone can help me figure out how to take counterparts of these custom code segments and use the userchrome.css instead? I'm pretty sure at least some of these are built-in by now. I did these by copying existing and/or recommended solutions to major problems I've been encountering.

#toolbar-menubar, #menubar-items, #main-menubar {                                                                  
  background: #F9F9FA !important;                                             
  -moz-appearance: unset !important;                                          
}

.tab-throbber{display:none !important;}

#reload-button, #stop-button {
display: inherit !important; 
} 
#reload-button > .toolbarbutton-icon {
-moz-appearance: none !important; 
}

#pageActionButton {
    display: none !important; 
} 

#PanelUI-button {
  visibility: collapse !important;
}

#PopupAutoCompleteRichResult[autocompleteinput="urlbar"] .autocomplete-richlistitem:-moz-any([type*="heuristic"],[actiontype="searchengine"],[actiontype="visiturl"],[actiontype="keyword"],[actiontype="switchtab"]) .ac-url-text,
#PopupAutoCompleteRichResult[autocompleteinput="urlbar"] .autocomplete-richlistitem .ac-title-text {
  min-width: calc((100vw - 100px)*0.45) !important;
  width: calc((100vw - 100px)*0.45) !important;
}

#PopupAutoCompleteRichResult[autocompleteinput="urlbar"] .autocomplete-richlistitem:-moz-any([type*="heuristic"],[actiontype="searchengine"],[actiontype="visiturl"],[actiontype="keyword"],[actiontype="switchtab"]) .ac-title-text,
#PopupAutoCompleteRichResult[autocompleteinput="urlbar"] .autocomplete-richlistitem .ac-url-text {
  min-width: calc((100vw - 100px)*0.55) !important;
  width: calc((100vw - 100px)*0.55) !important;
}

And, finally - what do I select in userchrome.css in order to remove the "view image in new tab" option and bring back the "view image" option?

**Comment by glennpc** [comment]
Many of those settings don't work anymore on newer versions of FF. This is what I use to make it look similar to the older versions:

@import "./css/locationbar/selection_color_for_bright_bg.css"; /**/

@import "./css/locationbar/megabar_expanding_breakout_disabled.css"; /**/

@import "./css/locationbar/megabar_border_roundness.css"; /**/

As far as the dropmarker, I use this script which gets placed in my_userChrome.css file:

#page-action-buttons::before { display: -moz-inline-box; content: ""; height: 24px; width: 24px;
padding: var(--urlbar-icon-padding); fill: var(--lwt-toolbar-field-color, black);
fill-opacity: 0.6; -moz-context-properties: fill, fill-opacity;
background: no-repeat center url(chrome://global/skin/icons/arrow-dropdown-16.svg); opacity: 0; transition: opacity 150ms linear }
#page-action-buttons::before{ opacity: 1 }
.urlbar-input-box:not(:focus-within){ margin-inline-end: -24px; }
#urlbar-input:not(:focus-within){ padding-inline-end: 24px !important; }
.urlbar-input-box:focus-within ~ #page-action-buttons::before{ -moz-user-focus: normal }

Your find bar is invisible? This is what I use which is placed in my_userChrome.css file:

.browserContainer > findbar { -moz-box-ordinal-group: 0; position: fixed !important;
border-top: none !important; margin-top: -1px !important; --toolbar-field-focus-border-color: #C0C0C0 }

It places the find bar at the top with the close button at the right. That will only work on Fx88. Starting with Fx89, the code had to be modified.

![ff88](https://user-images.githubusercontent.com/54756104/115901968-b94d0380-a416-11eb-9fec-a0ef466b13ba.png)


View image option can be brought back only by using an add-on, not with CSS. Try this out- 
https://addons.mozilla.org/en-US/firefox/addon/view-image-context-menu-item/

**Comment by Nyekomimi** [comment]
Hello! The color seems fine now, but...

The find bar is still invisible. The URL bar is still fully round instead of looking well (rounded square as it used to be in good old days). http://prntscr.com/11xk7z4

As for View Image - the huge, HUGE issue with it is that it actually gives the option all the way on bottom instead of where muscle memory guides me. Thats why I really need something, anything that makes it where it should be...

**Comment by glennpc** [comment]
I'm not sure why your find bar doesn't show up. It normally shows up on the bottom unless you use a script telling it to show up at the top. Perhaps you have another code enabled that's hiding it?

Glad to see your color is fine and the URL bar is rounded. 

That's a useful add-on for restoring the view image. I bet many will be using that add-on.

**Comment by Nyekomimi** [comment]
URL bar is *too* rounded!

I've removed all the custom codes except for ones you provided + one more. Unless there is option in userChrome.css that hides the search bar intentionally, that's an bug in it.

Also here's solution to View Image being on very bottom:

menuitem[label="View Image"] {-moz-box-ordinal-group:0;}
menuitem#context-viewimage {-moz-box-ordinal-group:10;}

**Comment by glennpc** [comment]
Here's what I use for the URL and search bar to make it look a little less rounded:

#urlbar #urlbar-background,
#urlbar, #urlbar-input-container,
#searchbar, .searchbar-textbox
{ border-radius: 14px !important; }
#urlbar[focused="true"][open] #urlbar-input-container
{ border-bottom-left-radius: 14px !important; }

Lower the amount of the 14px and it will be more squared looking.

Thanks for the info on how to move the view image on the context menu.

**Comment by Aris-t2** [comment]
There is always room for improvement. Use the below code inside the mentioned file. It should offer a slightly better result for the "open" megabar popup. The value of `1.5` within the code is suitable for the default configuration, but using another "roundness" value than `20px`, will require a different value than `1.5`.

`megabar_border_roundness.css`

```css
:root {
	--megabar_border_roundness: 20px;
}

#urlbar #urlbar-background,
#urlbar, #urlbar-input-container,
#searchbar, .searchbar-textbox {
  border-radius: var(--megabar_border_roundness) !important;
}

#urlbar[focused="true"]:not([usertyping="true"]) .urlbarView,
#urlbar .search-one-offs,
#urlbar .search-one-offs .search-panel-header,
#urlbar .search-one-offs .search-panel-one-offs-container {
  border-bottom-left-radius: var(--megabar_border_roundness) !important;
  border-bottom-right-radius: var(--megabar_border_roundness) !important;
}

#urlbar .search-one-offs .search-setting-button-compact {
  border-bottom-right-radius: var(--megabar_border_roundness) !important;
}

#urlbar[focused="true"][open] #urlbar-input-container {
  border-bottom-left-radius: 0px !important;
  border-bottom-right-radius: 0px !important;
}



#urlbar[open="true"] #urlbar-background,
#urlbar[open="true"],
#urlbar[open="true"] #urlbar-input-container {
  border-radius: calc(var(--megabar_border_roundness) / 1.5) !important;
}

#urlbar[focused="true"]:not([usertyping="true"]) .urlbarView,
#urlbar .search-one-offs,
#urlbar .search-one-offs .search-panel-header,
#urlbar .search-one-offs .search-panel-one-offs-container {
  border-bottom-left-radius: calc(var(--megabar_border_roundness) / 1.5) !important;
  border-bottom-right-radius: calc(var(--megabar_border_roundness) / 1.5) !important;
}

#urlbar .search-one-offs .search-setting-button-compact {
  border-bottom-right-radius: calc(var(--megabar_border_roundness) / 1.5) !important;
}

```


I can't tell you much about your "findbar" issue. There is no code inside this project, that hides findbar on purpose.

Remove anything inside your chrome folder, when experiencing issues and run tests to see what happens without any custom code.
