### ISSUE TITLE
FF89.0b8 -  tabs_below_navigation_toolbar not working correclty anymore

### ISSUE THREAD

**Issue by Omnibrain007** [Aris-t2/CustomCSSforFx#344]
With the latest update FF89.0b8 the **tabs_below_navigation_toolbar** css not working anymore. 
For test I only used the 5 css of tabs_below_navigation_toolbar.

When I use the standard css for "tabs_below_navigation_toolbar" then the tabs are at the very bottom of the window and only active tab will be shows
When replacing the tabs_below_navigation_toolbar_fx65.css with the tabs_below_navigation_toolbar_fx65_v2.css then it looks a little bit better, the tabs are not anymore at bottom but there is a big space below the tabs. 
![grafik](https://user-images.githubusercontent.com/81635182/117105621-b6d79b80-ad7e-11eb-8b42-d4b18e8fcc5e.png)

FF 89.0b8 (64bit)-Win10 20H2

**Comment by Aris-t2** [comment]
Not sure, if this is a Fx 89 only issue, but it works "fine" on Nightly, when using the complete package and changing one line only inside `userChrome.css`:
```css
/* - Fx 65+ v2 - mainly for multi-lined tabs (Glitches with inactive menubar!) ******************/  /* <- use this for multiple tab lines support */
 @import "./css/tabs/tabs_below_navigation_toolbar_fx65_v2.css"; /**/
```

![image](https://user-images.githubusercontent.com/6013569/117150116-25851b00-adb8-11eb-8110-a1ea05a1347d.png)
![image](https://user-images.githubusercontent.com/6013569/117150325-52393280-adb8-11eb-93ad-4733135daa09.png)

**Comment by yochaym** [comment]
hi aris,

the problem with tabs_below_navigation_toolbar is caused by the removal of position: relative from the navigator-toolbox.
apart from adding it you can try something like this to make it work w/wo proton (needs restart after changing the pref):
```css
#navigator-toolbox {
	position: relative;
}

.tabbrowser-tab {
	height: calc(var(--tab-min-height_tnot) + 1px);
}

@media (-moz-proton) {
	:root {
		--tab-min-height: calc(var(--tab-min-height_tnot) + 1px) !important;
	}

	.tab-content {
		height: calc(100% - 4px);
	}
}
```
btw you can use something like this to get more reasonable menus with proton (should probably be chrome&content):
```css
@media (-moz-proton) {
	:root {
		--toolbarbutton-inner-padding: 6px !important;
		--arrowpanel-menuitem-padding: 4px var(--arrowpanel-menuitem-padding-block) !important;
	}
	
	menupopup > menuitem, menupopup > menu {
		padding-block: 3px 4px !important;
	}
}
```
p.s only tested on nightly...

**Comment by Omnibrain007** [comment]
Aris you mean not to load the code from _tabs_below_navigation_toolbar_fx68.css, ..fx72.css and ..fx74.css_

So when I just load from userChrome.css the tabs_below_navigation_toolbar_fx65_v2.css and included the abs_below_navigation_toolbar.css. then it looks much better like this:
![grafik](https://user-images.githubusercontent.com/81635182/117174804-65ef9380-adce-11eb-9853-f9f112156b8b.png)

But with additional the position code from yochaym it looks nearly normal. Perhaps just a little fine tuning needed.
![grafik](https://user-images.githubusercontent.com/81635182/117174739-540df080-adce-11eb-8e3c-c2b29498e921.png)

**Comment by Aris-t2** [comment]
Default code + the fix posted by **yochaym** works fine. I've added the code to the project. It already is part of the "pre" releases.

**Comment by yochaym** [comment]
hi aris,

tabs_below_navigation_toolbar_fx89 will not work correctly when proton is enabled & classic_squared_tabs is not imported...
something like the code below should make it work regardless.
```css
@media (-moz-proton) {
	
    #TabsToolbar {
	--toolbarbutton-inner-padding: calc((var(--tab-min-height_tnot) - 15px) / 2 - 4.5px) !important;
    }

    .tabbrowser-tab {
	min-height: unset !important; 
    }
}
```
p.s padding is for when the tabs overflow arrows & buttons are visible...

**Comment by Aris-t2** [comment]
Check [3.2.2](https://github.com/Aris-t2/CustomCSSforFx/releases/tag/3.2.2) release.

**Comment by ichier** [comment]
Hi there.
tabs_below_navigation_toolbar is the only hack that i use.
with the 3.2.2 release the active tab was overlapping into the website/contentarea.
so i added 10px (took the snips from 72 and 68 ...):
```css
@media (-moz-proton) {
	#main-window:not([chromehidden*="toolbar"]) #navigator-toolbox {
	  padding-bottom: calc(0px + var(--tab-min-height_tnot) + 10px) !important;
	}
	#TabsToolbar {
	  height: calc(var(--tab-min-height_tnot) + 10px) !important;
	}
}
```
