### ISSUE TITLE
when i use "TABS BELOW NAVIGATION AND BOOKMARKS TOOLBARS" and "MOVE NAVIGATION TOOLBAR TO HIGHER POSITON"  adressbar and buttons are lefter than it is posssible

### ISSUE THREAD

**Issue by trofey** [Aris-t2/CustomCSSforFx#346]
when i use "TABS BELOW NAVIGATION AND BOOKMARKS TOOLBARS" and "MOVE NAVIGATION TOOLBAR TO HIGHER POSITON" adressbar and buttons are lefter than it is posssible. i want to ask how to move buttons and adressbar to the right

![Untitled](https://user-images.githubusercontent.com/84445458/118796477-53805a00-b8a4-11eb-915b-23ef7a3120be.jpg)

latest CustomCSSforFx files
windows 7 x64
1920x1080 
firefox x64 88.0.1

**Comment by Aris-t2** [comment]
There is no support for "classic Win 7 theme", when using this feature.

Try this code:

```css
  #main-window[tabsintitlebar] #nav-bar:not(:-moz-lwtheme),
  #main-window[tabsintitlebar] #nav-bar {
	-moz-margin-end: 80px !important;
  } 
```
