### ISSUE TITLE
[FX 89+] Color of active tab indistinguishable with Dark Theme

### ISSUE THREAD

**Issue by nicolaasjan** [Aris-t2/CustomCSSforFx#357]
1. Color of active and inactive tabs is the same.

2. What should have happened instead?
There should be a clearly visible difference.

3. Steps to reproduce the issue?
Switch to Dark Theme and look at the second tab from the right.

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)
![Screenshot-tabs-89-1](https://user-images.githubusercontent.com/14093220/120516069-4056a980-c3cf-11eb-957d-2456df15e393.png)

5. System information
- latest CustomCSSforFx files (yes / no [no support, if 'no']): yes
- OS & OS version: Linux Mint 19.3 Mate
- OS theme (if not default): Mint X
- DPI / HiDPI resolution: 1920x1080
- Firefox version: 89.0
- Firefox theme / lw-theme: Dark (built in)
- This projects 'settings' the issue occurs with: 

Proton disabled via `about:config`.
`@import "./css/tabs/tabs_below_navigation_toolbar_fx89.css"; /**/`

I've applied a (temporary?) fix using the following code in `my_userChrome.css`:

```
/* highlight active tab (my_userChrome.css) */
#TabsToolbar .tabbrowser-tab[selected=true] .tab-background { background-image: radial-gradient(Transparent,Yellow) !important; }
```
Screenshot:
![Screenshot-tabs-89-2](https://user-images.githubusercontent.com/14093220/120517147-67fa4180-c3d0-11eb-944b-ba736d4f9f8d.png)

**Comment by Aris-t2** [comment]
Test recent pre releases. This issue should be gone. (At least it was in my tests ;-) )

**Comment by nicolaasjan** [comment]
> Test recent pre releases. This issue should be gone. (At least it was in my tests ;-) )

Tested `custom_css_for_fx_v3.2.1pre4`.

That didn't make any difference, unfortunately...
Is there a setting I must enable first?
Screenshot (the Google tab at the right is the active one):
![Screenshot_prerelease4](https://user-images.githubusercontent.com/14093220/120777279-6a21e480-c525-11eb-85bf-3a745a0c2032.png)

**Comment by Aris-t2** [comment]
I see what happened.

The code ended up being inside @media (-moz-proton) {} instead of being "always" applied.

```css

#tabbrowser-tabs:not([movingtab]) > #tabbrowser-arrowscrollbox > .tabbrowser-tab > .tab-stack > .tab-background[multiselected=true]:-moz-lwtheme,
#tabbrowser-tabs:not([movingtab]) > #tabbrowser-arrowscrollbox > .tabbrowser-tab > .tab-stack > .tab-background[selected=true]:-moz-lwtheme {
  background-color: var(--tab-selected-bgcolor, var(--toolbar-bgcolor)) !important;
}

#main-window:not([lwtheme-image="true"]) #tabbrowser-tabs:not([movingtab]) > #tabbrowser-arrowscrollbox > .tabbrowser-tab > .tab-stack > .tab-background[multiselected=true]:-moz-lwtheme,
#main-window:not([lwtheme-image="true"]) #tabbrowser-tabs:not([movingtab]) > #tabbrowser-arrowscrollbox > .tabbrowser-tab > .tab-stack > .tab-background[selected=true]:-moz-lwtheme {
  background-image: var(--toolbar-bgimage) !important;
}
```
