### ISSUE TITLE
[Fx 90+][Linux][tabs not on top] In 90.0b1 text in menu bar became invisible (black on black) with Dark Theme

### ISSUE THREAD

**Issue by nicolaasjan** [Aris-t2/CustomCSSforFx#365]
1. Describe the issue
In 90.0b1 text in menu bar became invisible (black on black) with Dark Theme.

2. What should have happened instead?
Text in the menu bar should be white.

3. Steps to reproduce the issue?
Install Beta or Nightly.

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)
![Schermafdruk op 2021-06-05 11-34-00](https://user-images.githubusercontent.com/14093220/120887248-00bbd780-c5f2-11eb-9594-bba0f199a9f3.png)

5. System information
- latest CustomCSSforFx files (yes / no [no support, if 'no']): Yes
- OS & OS version: Linux Mint 19.3 Mate
- OS theme (if not default): Mint X
- DPI / HiDPI resolution: 1920x1080
- Firefox version: 90 & 91
- Firefox theme / lw-theme: Dark Theme (built in)
- This projects 'settings' the issue occurs with: N/A

No issue with Light Theme or System Theme.
Is there some `userChrome.css` trick to make the text white again?

[Edit]
Same issue with other dark themes.

**Comment by Aris-t2** [comment]
```css
#main-menubar > menu > label {
  color: white !important;
}
```

**Comment by Aris-t2** [comment]
Might be a Linux issue. This does not happen on Windows for me.

**Comment by nicolaasjan** [comment]
> ```css
> #main-menubar > menu > label {
>   color: white !important;
> }
> ```

Thanks!
It worked.

Strange though, that it has never been an issue with previous Firefox versions.

**Comment by nicolaasjan** [comment]
However, this setting doesn't work well with the System Theme...
![Schermafdruk op 2021-06-05 12-42-01](https://user-images.githubusercontent.com/14093220/120889072-d0793680-c5fb-11eb-8ab4-478b95b2aaa2.png)

**Comment by Aris-t2** [comment]
The code was for your dark theme test only.

This should do the job for all lw-themes.
```css
#main-menubar:-moz-lwtheme-brighttext > menu > label {
  color: white !important;
}

#main-menubar:-moz-lwtheme-darktext > menu > label {
  color: black !important;
}
```
