### ISSUE TITLE
[Fx89+] [tabs not on top mode][default browser tabs] - cleaning up code - please test 

### ISSUE THREAD

**Issue by Aris-t2** [Aris-t2/CustomCSSforFx#380]
I'm trying to remove  old pre-Fx57-88 code, that is not required anymore to achieve "tabs below navigation-/bookmarks toolbar".

Please test an report.

So far this is working (on my system) without any other CSS:
- Windows 10
- default, dark, light and other lw-themes
- tab size (controlled by density settings: compact, normal, touch)
- fullscreen mode
- fullscreen videos (e.g. Youtube)

_EDIT_
- also works with CustomCSSforFx, if classic squared tabs are disabled.

------------------------------

```css
#TabsToolbar {
  position: absolute;
  display:block;
  bottom: 0;
  width: 100vw;
  background-color: var(--toolbar-bgcolor);
  background-image: var(--toolbar-bgimage);
  background-clip: padding-box;
  color: var(--toolbar-color);
}

#tabbrowser-tabs {
  width: 100vw;
}

#navigator-toolbox {
  position: relative;
  padding-bottom: calc( var(--tab-min-height) + 8px );
}

#main-window[tabsintitlebar][sizemode="maximized"]:not([inDOMFullscreen="true"]) #titlebar {
  height: 36px;
}

/* move caption buttons to windows top right position */
.titlebar-buttonbox-container {
  position: fixed;
  right: 0;
  visibility: visible;
  display: block;
}

#TabsToolbar .titlebar-buttonbox-container,
#TabsToolbar .private-browsing-indicator,
#TabsToolbar #window-controls,
#TabsToolbar *[type="caption-buttons"],
#TabsToolbar *[type="pre-tabs"],
#TabsToolbar *[type="post-tabs"] {
  display: none;
}
```

**Comment by yochaym** [comment]
hi aris,

there are 2 issues with classic_squared_tabs that you may want to look into...
1) when there are pinned tabs and many tabs open so the tabs scrollbar arrows are showing (as in #373) - the pinned tab height is incorrect.
2) in combination with tabs not on top (new & old) the active tab shows the bottom line (the separator from the content).
tested on nightly with v3.2.5pre3 
are you keeping --tab-min-height_tnot?

**Comment by Aris-t2** [comment]
The test is for "default browser tabs", not classic squared tabs, but a few tweaks will make it compatible too.

**Comment by Atexor** [comment]
Hey, I tested your CSS and it looks really fine and compact compared to old version with a lot of outdated code.
I used your modified CSS it working fine on FF89 was nightmare.

Hovewer I noticed one problem - menu bar has different color than rest of them. It looks a bit buggy when set "fancy" themes like Mozilla Alpenglow. Take a look on background of items called "Plik", "Edycja", "Widok" etc.

![obraz](https://user-images.githubusercontent.com/34380553/121789169-ff7f4180-cbd3-11eb-8368-ac2036a02d0f.png)

For me the workaround-solution is adding that code from one of your older versions, that was used for removing color overlay for lw-themes.

```
#main-window:not([style*='--lwt-header-image:url("resource:///chrome/browser/content/browser/defaultthemes/compact.header.png");']) :-moz-any(#nav-bar,#PersonalToolbar,#TabsToolbar):-moz-lwtheme{
  background: unset !important;
}
```

Hovewer, as you maybe noticed above, for custom themes it changes colors to darker. [That theme](https://addons.mozilla.org/pl/firefox/addon/dark-gray-theme-webextension/) shouldn't look on that way.
![obraz](https://user-images.githubusercontent.com/34380553/121789274-e6c35b80-cbd4-11eb-92dc-27114ec8c1ae.png)

Do you have solution to make all Firefox bars with the same color?

Also to my mind, tab height is a bit too much.

Your solution from previous version for FF89 to reduce tab height changes it nicely.
```
@media (-moz-proton) {
	.tabbrowser-tab {
		min-height: unset !important; 
	}
}
```

**Comment by ImSpecial** [comment]
So from the GENERAL discussion thread the other day I bought up an issue I was having with the alignment of certain elements (buttons and whatnot) when tabs were on the bottom.

https://github.com/Aris-t2/CustomCSSforFx/issues/368#issuecomment-859938421

(Default tabs on top v2.3.4)
https://i.imgur.com/EgfbxhM.png

(Tabs on bottom v2.3.4)
https://i.imgur.com/BuqleXG.png

Well the good news is that the alignment (min/max/close button, etc.) are all fixed up and perfectly working exactly how you would expect they would while hovering over them with the mouse cursor, and the tabs all seem to look great and function properly too.

But there seem to be some color issues/big thick lines that are some kind of an alignment issue with the theme?

(tabs_below_navigation_toolbar_fx89 v2.3.5)
https://i.imgur.com/XuPcl6Y.png

And the code snippet from the OP. (seems pretty similar to v2.3.5 now but the line is a little thicker here)

OP Bottom
https://i.imgur.com/yZPKOJF.png

And I'm not sure if this is a bug or intentional but there is a black line along the bottom of the tabs where they meet the web page.

Arrow line
https://i.imgur.com/7hiw9tu.png

How would I go about removing this line, I was rather have my tabs flush with page and have no noticeable lines seen.

**Comment by yochaym** [comment]
1) v3.2.6 reintroduced the pinned tabs issue (not sure why you removed this [#L189](https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/css/tabs/classic_squared_tabs.css#L189), but it also didn't work when the pinned tab was selected). maybe it would be easier to fix by setting margin-block: 0 on the .tab-background.
2) to fix the active tab bottom line you should have kept [#L35](https://github.com/Aris-t2/CustomCSSforFx/blob/68e8a5519cb9d77d92d25d57fd45aa5bddd73690/classic/css/tabs/tabs_below_navigation_toolbar_fx89.css#L35) and just add height to the TabsToolbar like this [L23](https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/css/tabs/tabs_below_main_content_fx72.css#L23) so the tabs will overflow 1px down...
3) you can make tabs_below_navigation_toolbar_fx89 work also as a standalone by using 0 specificity to set the --tab-min-height so it will get overridden by classic_squared_tabs although it is imported before:
```css
:where(:root) {
	--tab-min-height: calc(var(--tab-min-height_tnot) - 8px) !important;
}
```

**Comment by ImSpecial** [comment]
I updated to v3.2.6 and went to check if there were any improvements, "tabs_below_navigation_toolbar_fx89" looks and behaves the same as far as I can see, so same "line" problem as before.

I did notice "tabs_below_navigation_toolbar_fx89_WinLin_defaults_tabs", which I never tried before so I tried it and it looks and behaves very similar but looks better as you can see from this image;

(v3.2.6 "tabs_below_navigation_toolbar_fx89_WinLin_defaults_tabs")
https://i.imgur.com/cMDG5q7.png

BTW, this all happens the same, with the "about:config" tweak "browser.proton.enabled" true or false, makes no difference in my reports.

**Comment by Aris-t2** [comment]
@ImSpecial 

It looks like this for me (as intended):
![image](https://user-images.githubusercontent.com/6013569/121908222-138a8680-cd2d-11eb-9791-0b5abcc673b6.png)

Not sure, if this is what you are looking for, but the following code will override toolbar colors for lw-themes used by tabs_below_navigation_toolbar_fx89/tabs_below_navigation_toolbar_fx89_WinLin_defaults_tabs

```css
#main-window:not([style*='--lwt-header-image']) #TabsToolbar:-moz-lwtheme,
toolbar:-moz-lwtheme {
  background: unset !important;
  background-color: unset !important;
  background-image: unset !important;
}
```

**Comment by ImSpecial** [comment]
I use this to make mine black; (probably needs an updating)
```
/* different "Tab Toolbar" colors */
#main-window:not([style*='--lwt-header-image']) toolbar:-moz-lwtheme:-moz-lwtheme-brighttext,
#main-window:not([style*='--lwt-header-image']) #TabsToolbar:-moz-lwtheme:-moz-lwtheme-brighttext,
#main-window:not([style*='--lwt-header-image']):-moz-lwtheme-brighttext {
 background-image: linear-gradient(black,black) !important;
}
```
How can I adept your code or mine to fix this line problem, while keeping the other Themes like "Light", "System", etc. from looking like shit?

When I use yours and change the "unset" parts to "linear-gradient(black,black)" All themes are now black. And I still have the line problem.

**Comment by Aris-t2** [comment]
This should do the trick:

```css
#main-window:not([style*='--lwt-header-image']) #navigator-toolbox:-moz-window-inactive:-moz-lwtheme:-moz-lwtheme-brighttext,
#main-window:not([style*='--lwt-header-image']) #navigator-toolbox:-moz-lwtheme:-moz-lwtheme-brighttext,
#main-window:not([style*='--lwt-header-image']) #titlebar:-moz-lwtheme:-moz-lwtheme-brighttext,
#main-window:not([style*='--lwt-header-image']) toolbar:-moz-lwtheme:-moz-lwtheme-brighttext,
#main-window:not([style*='--lwt-header-image']) #TabsToolbar:-moz-lwtheme:-moz-lwtheme-brighttext,
#main-window:not([style*='--lwt-header-image']):-moz-lwtheme-brighttext {
 background-image: linear-gradient(black,black) !important;
}
```

**Comment by ImSpecial** [comment]
OMG OMG OMG OMG! I think this is perfect! I'll have to test it for a bit and give it a day but I think everything is cured with that!!!

One last tiny tiny thing, since I have your attention here and very minor, when hovering over tabs the little tab divider expands and kinda ends up being to long, how can I shorten this "expanding" by a single pixel or so to make it flush.

https://i.imgur.com/EGAsBkx.png
https://i.imgur.com/ijtWEj4.png
https://i.imgur.com/Kt1YXg3.png

**Comment by Aris-t2** [comment]
This nice block controls separators height:

```css
:root[tabsintitlebar] #toolbar-menubar[autohide=true] + #TabsToolbar .tabbrowser-tab::after,
.tabbrowser-tab:hover::after,
#tabbrowser-tabs:not([movingtab]) > #tabbrowser-arrowscrollbox > .tabbrowser-tab[beforehovered]::after,
.tabbrowser-tab[multiselected]::after,
#tabbrowser-tabs:not([movingtab]) > #tabbrowser-arrowscrollbox > .tabbrowser-tab[before-multiselected]::after,
#tabbrowser-tabs:not([movingtab]) > #tabbrowser-arrowscrollbox > .tabbrowser-tab[beforeselected-visible]::after,
#tabbrowser-tabs[movingtab] > #tabbrowser-arrowscrollbox > .tabbrowser-tab[visuallyselected]::before,
.tabbrowser-tab[visuallyselected]::after {
  margin-top: 1px !important;
  margin-bottom: 0 !important;
}
```
