### ISSUE TITLE
Help for Firefox 89  CustomCSSforFx 3.2.5

### ISSUE THREAD

**Issue by tonybannister** [Aris-t2/CustomCSSforFx#386]
CustomCSSforFx 3.2.5) Windows 10 Home 64-bit 20H2 19042.1052 1920x1080
Firefox 89 64 bit Firefox Windows 95 Theme  Proton Disabled 

Can anyone suggest how to achieve the below have tried going through the user Chrome etc etc but cannot find the answer.
I am not a css wiz, it is several years since i made the old Chrome. 

This my Firefox 88.0.1 with CustomCSSforFx Version 2.3.7 settings

![88 Menu Bar Tab Red](https://user-images.githubusercontent.com/85840008/121815375-753be980-cc76-11eb-99fc-5010c2992d1e.png)
![88 Tab Menu](https://user-images.githubusercontent.com/85840008/121815376-75d48000-cc76-11eb-8187-38389d59dbde.png)

After many years I cannot remember how I got the red top on the selected tab also it would be nice to get the menus looking the same as the old version.
This is my Firefox 89  with CustomCSSforFx Version 3.2.5 settings

![89 Menu Red top](https://user-images.githubusercontent.com/85840008/121815377-766d1680-cc76-11eb-898b-9cf34e5aa3ae.png)
![89 Tab Menu](https://user-images.githubusercontent.com/85840008/121815378-766d1680-cc76-11eb-9ffb-16eb44c90b28.png)

PS How do I make the forward & back arrows **Bold**

**Comment by GaVenga** [comment]
das interessiert mich ebenfalls!
that interests me too!

**Comment by Aris-t2** [comment]
**default_tabs_tab_line_red_for_unloaded_tabs.css** offered the "red" line for Fx 57-88 default tabs. If Proton is disabled, the option should work in Fx 89-90 too.

However, it is not compatible to Proton tabs. From Fx 91 on Proton will be active by default and the preference to disable it, will be gone.

The theme you are using is detected as "dark" theme, so Firefox now paints your context menu dark too.

You can not make the forward & backward arrows bold, but you can try another custom icon set or custom (large) back forward buttons.

**Comment by tonybannister** [comment]
Thank you very much for answering so prompt. Well it seems as though it does not matter as again Firefpx looses a customization possibility, but default_tabs_tab_line_red_for_unloaded_tabs.css  is not enabled in my Firefox 88 CustomCSSforFx Version 2.3.7 browser, but it does have red line at the top. which turns blue when the  Windows 95 Theme is turned off.
Curious to say the least.
Anyway I will have either turn on Proton and build a new customization or try another browser.
Pit I have used that look for 20 years, sigh!!! o for the days of  MyIE and Green Browser .

**Comment by Aris-t2** [comment]
Default browser tabs in Fx 88 and before offered a tab line by default. Most likely your themes accent color was red, so the line was red for you. This line is not present for Protons default tabs anymore.

**Comment by Speravir** [comment]
@tonybannister, @Aris-t2:

If the tab with the red line is really an unloaded tab and this was done with `default_tabs_tab_line_red_for_unloaded_tabs.css` which
> offered the "red" line for Fx 57-88 default tabs.

and
> However, it is not compatible to Proton tabs.

It works with an adaptation of what I posted on [13th June](https://github.com/Aris-t2/CustomCSSforFx/issues/368#issuecomment-860124204):

```css
.tabbrowser-tab[pending] .tab-context-line {
	margin-top: 0 !important;
	background-color: red !important;
}
```
Note, Tony, that I need to set the top margin to zero, but Aris replied ~today~ yesterday that it works for him with the default setting.

If you use container tabs the above rule gets in conflict with the default usage, though. I myself have instead a rule in use where the tab label (the title) is differently coloured for unloaded tabs.

**Comment by B00ze64** [comment]
@tonybannister Thanks for making me look into this (Bold Buttons). So yeah, in 89 they are so thin, I keep wondering where they are, lol. So I grabbed them from Firefox 88. They are in InstallDir/Browser/Omni.JA. I put them in MyImages folder, and the CSS in the MyCSS folder, then I just @import my CSS file ->

```css
@-moz-document url("chrome://browser/content/browser.xhtml"), url("chrome://browser/content/browser.xul") {

#back-button { /* chrome://browser/skin/back.svg */
	list-style-image: url("../MyImages/FF/back.svg") !important; }
#forward-button { /* chrome://browser/skin/forward.svg */
	list-style-image: url("../MyImages/FF/forward.svg") !important; }
#sidebar-button { /* chrome://browser/skin/sidebars.svg */
	list-style-image: url("../MyImages/FF/sidebars.svg") !important; }
#reload-button { /* chrome://browser/skin/reload.svg */ 
	list-style-image: url("../MyImages/FF/reload.svg") !important; }
#stop-button { /* chrome://browser/skin/stop.svg */ 	
	list-style-image: url("../MyImages/FF/stop.svg") !important; }
#home-button { /* chrome://browser/skin/home.svg */
	list-style-image: url("../MyImages/FF/home.svg") !important; }
}
```
