### ISSUE TITLE
[Fx91+][Bookmarks popup] compact popup required

### ISSUE THREAD

**Issue by Marcosdw** [Aris-t2/CustomCSSforFx#395]
Hello,

See screenshot in 90.0
![Capture d’écran 2021-07-14 095137](https://user-images.githubusercontent.com/18121470/125587543-03355401-37db-4467-ba4b-cb617ad299a1.png)

in 91.0b1 and 92.0a1
![Capture d’écran 2021-07-14 094932](https://user-images.githubusercontent.com/18121470/125587636-d851ac67-d943-479e-9d00-2fcb7565b9fc.png)

How to return to the space of version 89 and 90 ?

Greetings

**Comment by Aris-t2** [comment]
Test `compact_menus_proton.css` and this code:

```css
:is(menupopup, panel)[type=arrow] {
  --panel-border-radius: 0px !important;
}
```

**Comment by Marcosdw** [comment]
.subview-subheader,
panelview .toolbarbutton-1,
.subviewbutton,
.widget-overflow-list .toolbarbutton-1 {
  margin: 0 !important;
  min-height: 0 !important;
  padding: 2px !important;
}
	
menupopup > menuitem,
menupopup > menu {
  padding-block: 2px !important;
  padding-inline-start: 4px !important;
}

#context-navigation :-moz-any(#context-back,#context-forward,#context-reload,#context-stop,#context-bookmarkpage) {
  padding: 2px !important;
  -moz-margin-start: -10px !important;
}
:is(menupopup, panel)[type=arrow] {
  --panel-border-radius: 0px !important;
}

does not work

**Comment by Aris-t2** [comment]
There is still room for improvement, test this:

```css
.subview-subheader,
panelview .toolbarbutton-1,
.subviewbutton,
.widget-overflow-list .toolbarbutton-1 {
margin: 0 !important;
min-height: 0 !important;
padding: 2px !important;
}

menupopup > menuitem,
menupopup > menu {
padding-block: 2px !important;
padding-inline-start: 4px !important;
}

#context-navigation :-moz-any(#context-back,#context-forward,#context-reload,#context-stop,#context-bookmarkpage) {
padding: 2px !important;
-moz-margin-start: -10px !important;
}

* menupopup,
:is(menupopup, panel)[type=arrow] {
--panel-border-radius: 0px !important;
--panel-padding: 0px !important;
}
```

![image](https://user-images.githubusercontent.com/6013569/126030140-b8c9dbff-efbc-43bc-a039-88048f914ea2.png)
