### ISSUE TITLE
"Remote tab" label look weirdly ouf of place

### ISSUE THREAD

**Issue by ThiefMaster** [Aris-t2/CustomCSSforFx#397]
1. Describe the issue
The label for tabs on other computers running Firefox looks very weird and out-of-place.

2. What should have happened instead?
It should be shown in a nicer way (like it happened before Proton became mandatory in FF 91)

3. Steps to reproduce the issue?
Probably having Proton and synced tabs is enough.

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)
![image](https://user-images.githubusercontent.com/179599/125830799-2168a5a3-418e-41e3-aafb-b839182dcc01.png)

5. System information
- latest CustomCSSforFx files: yes
- OS & OS version: Win 10
- OS theme (if not default): 
- DPI / HiDPI resolution: 2560x1440
- Firefox version: 91.0b2
- Firefox theme / lw-theme: Dark 1.2
- Proton enabled (yes / no): yes :(
- This projects 'settings' the issue occurs with: 

```css
@import "./config/general_variables.css"; /**/
@import "./config/color_variables.css"; /**/  /* <- default 'grey' colors */
@import "./css/buttons/button_padding_proton.css"; /**/
@import "./css/tabs/default_tabs_tab_line_red_for_unloaded_tabs_proton.css"; /**/
@import "./css/tabs/default_tabs_tab_line_purple_in_private_mode_proton.css"; /**/
@import "./css/locationbar/megabar_expanding_breakout_disabled.css"; /**/
@import "./css/locationbar/ac_popup_megabar_title_and_url_two_lines.css"; /**/
@import "./css/locationbar/ac_popup_megabar_compact_results.css"; /**/
@import "./css/locationbar/ac_popup_megabar_search_engines_hidden.css"; /**/
```

**Comment by Aris-t2** [comment]
Does this happen to "switch to tab" item too?
Both use the same code. Unfortunately I can not test remote tabs items.
https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/css/locationbar/ac_popup_megabar_title_and_url_two_lines.css#L63

![image](https://user-images.githubusercontent.com/6013569/125985662-e0abad3c-3ee2-4bf2-abb4-4258f8096616.png)

**Comment by ThiefMaster** [comment]
No, that one looks fine:

![image](https://user-images.githubusercontent.com/179599/125993554-46dfbaa0-3ec5-498a-a9f9-20f3b48b6afc.png)

The easiest way to reproduce it is probably by creating a second firefox profile, and then syncing it with your Mozilla account :/

**Comment by Aris-t2** [comment]
Test this code inside `ac_popup_megabar_title_and_url_two_lines.css` (replace everything):

```css
#urlbar .urlbarView-results > .urlbarView-row > .urlbarView-row-inner {
  flex-wrap: wrap !important;
}
#urlbar .urlbarView-results > .urlbarView-row > .urlbarView-row-inner > .urlbarView-no-wrap {
  max-width: 100% !important;
  flex-basis: 100% !important;
}
#urlbar .urlbarView-results > .urlbarView-row[has-url] > .urlbarView-row-inner > .urlbarView-url {
  margin-top: 2px !important;
  padding-inline-start: calc(6px + 2px + 16px) !important;
}
#urlbar[actionoverride] .urlbarView-results > .urlbarView-row[has-url] > .urlbarView-row-inner > .urlbarView-no-wrap > .urlbarView-title-separator,
#urlbar .urlbarView-results > .urlbarView-row[has-url]:not([type$=tab]) > .urlbarView-row-inner > .urlbarView-no-wrap > .urlbarView-title-separator {
  display: none !important;
}

/* support for heuristic items: search, remote tab, switch to tab */
#urlbar .urlbarView-results > .urlbarView-row:-moz-any([type=search],[type=switchtab]) > .urlbarView-row-inner > .urlbarView-no-wrap > .urlbarView-title-separator,
#urlbar .urlbarView-results > .urlbarView-row:not([has-url="true"]) > .urlbarView-row-inner > .urlbarView-no-wrap > .urlbarView-title-separator {
  display: none !important;
}

#urlbar .urlbarView-results > .urlbarView-row:-moz-any([type=search],[type=switchtab]) > .urlbarView-row-inner > .urlbarView-no-wrap,
#urlbar .urlbarView-results > .urlbarView-row:not([has-url="true"]) > .urlbarView-row-inner > .urlbarView-no-wrap {
  padding-bottom: 19px !important;
}

#urlbar .urlbarView-results > .urlbarView-row:-moz-any([type=remotetab]):not([selected]):not(:hover) > .urlbarView-row-inner > .urlbarView-no-wrap {
  padding-bottom: 15px !important;
}

#urlbar .urlbarView-results > .urlbarView-row:-moz-any([type=search],[type=switchtab]) > .urlbarView-row-inner > .urlbarView-no-wrap > .urlbarView-action,
#urlbar .urlbarView-results > .urlbarView-row:not([has-url="true"]) > .urlbarView-row-inner > .urlbarView-no-wrap > .urlbarView-action,
#urlbar .urlbarView-results > .urlbarView-row:-moz-any([type=remotetab]):not([selected]):not(:hover) > .urlbarView-row-inner > .urlbarView-no-wrap > .urlbarView-action {
  display: block !important;
  margin-bottom: -19px !important;
  position: absolute !important;
  padding-inline-start: calc(6px + 2px + 16px) !important;
}

/* Proton compatibility */
@media (-moz-proton) {

#urlbar .urlbarView-results > .urlbarView-row[has-url] > .urlbarView-row-inner > .urlbarView-url {
  padding-inline-start: calc(6px + 1px + 16px) !important;
}

#urlbar .urlbarView-results > .urlbarView-row:is([type=search],[type=switchtab]) > .urlbarView-row-inner > .urlbarView-no-wrap > .urlbarView-action,
#urlbar .urlbarView-results > .urlbarView-row:not([has-url="true"]) > .urlbarView-row-inner > .urlbarView-no-wrap > .urlbarView-action {
  margin-bottom: -37px !important;
}

#urlbar .urlbarView-results > .urlbarView-row:-moz-any([type=remotetab]):not([selected]):not(:hover) > .urlbarView-row-inner > .urlbarView-no-wrap > .urlbarView-action {
  margin-bottom: -47px !important;
  padding-inline-start: 16px !important;
}

#urlbar .urlbarView-results > .urlbarView-row[type=switchtab] > .urlbarView-row-inner > .urlbarView-no-wrap > .urlbarView-action {
  margin-bottom: -47px !important;
  -moz-appearance: none !important;
  background: unset !important;
  padding-inline-start: 15px !important;
}

#urlbar .urlbarView-results > .urlbarView-row[type=remotetab] > .urlbarView-row-inner > .urlbarView-no-wrap > .urlbarView-action {
  -moz-appearance: none !important;
  background: unset !important;
}

}
```

Try to tweak values wherever `[type=remotetab]` is part of the rule.
