### ISSUE TITLE
'Custom CSS tweaks for Firefox' - v4.0.0+ release supports Firefox 91+ and 91 ESR

### ISSUE THREAD

**Issue by Aris-t2** [Aris-t2/CustomCSSforFx#403]
https://github.com/Aris-t2/CustomCSSforFx/releases

**There is no support anymore for v3.x.x versions of this project.**

Due to major changes most of the configuration in userChrome.css and userContent.css has to be redone with v4.0.0 files.
This release it "Proton" ready. Do not disable "Proton" switches in about:config anymore.

- dropped support for "Custom CSS tweaks for Firefox" v3.x.x
- dropped support for Firefox versions lower than 91 (89-90 should still work)
- removed settings not compatible to Firefox 91+ (89-90 should still work)
- renamed settings, so there won't be any version depended settings at least for a while ("_fx65", "_fx75", "_fx89" etc.)
- cleaned up code of many files
- replaced deprecated or unneeded rules/names with current ones

----------------------------------

Report **issues** with v4.0.0 release and Firefox 91+ here in this thread.

If there is a "feature" v3.x.x offered, that did not make it into v4.0.0, but still is working on Firefox 91+, add a comment about it here.

----------------------------------

**Get Firefox 91 / 91 ESR**

https://ftp.mozilla.org/pub/firefox/releases/91.0/

https://ftp.mozilla.org/pub/firefox/releases/91.0esr/

**Comment by chpasha** [comment]
Hi, i have v4.0.1 installed on Firefox 91.0 on Linux, everything is fine so far except for the tab appearance for tabs on bottom (below content) - the labels and icons are to close to the bottom and not centered vertically in the tab. I had the same issue with v3 and firefox 89-90, but I could solve it with proton disabled, now this settings seems to have no effect. 

I have reset all my settings and left only default_tabs_enhanced.css + tabs_below_main_content.css activated, looks like this:
![screenshot-2021_08_13_13_39](https://user-images.githubusercontent.com/9569489/129352203-1b51b61e-3ce4-4a99-b861-7f418f6b8f68.png)

is it some known issue?

**Comment by Aris-t2** [comment]
The code for "tabs below content" did not receive any cleanup/updates for a while. It was not compatible with new ui.

Test `tabs_below_main_content_default_tabs.css` from 4.0.2pre4: https://github.com/Aris-t2/CustomCSSforFx/releases/

**Comment by chpasha** [comment]
Thank you, looks better now. I think the height of tabs could be a couple pixels smaller on top and bottom

![image](https://user-images.githubusercontent.com/9569489/129358970-926d9a47-1db8-48cd-8bff-56b5ddf1698a.png)

**Comment by Aris-t2** [comment]
"default tabs" sizes are kept default ;-)

The density setting in customizing mode controls tab height, but you can override it by enabling and using `--tab-min-height` in `general_variables.css`

**Comment by chpasha** [comment]
> "default tabs" sizes are kept default ;-)
so this is a new firefox design that sucks, oh my

> The density setting in customizing mode controls tab height, but you can override it by enabling and using `--tab-min-height` in `general_variables.css`
thank you very much. I think I will stick to classic-astralized theme for a while

**Comment by Aris-t2** [comment]
![image](https://user-images.githubusercontent.com/6013569/129373703-cb4af4b6-5b1f-43d1-90a6-31c7d331bebf.png)

I managed to tweak the bottom area for default tabs. Looks like this now.

**Comment by chpasha** [comment]
really nice, I'll give it a try, thank you

**Comment by Aris-t2** [comment]
Changes are part of [4.0.2pre5](https://github.com/Aris-t2/CustomCSSforFx/releases)

**Comment by chpasha** [comment]
thank you, looks much better now

**Comment by Underx01** [comment]
@Aris-t2

Hope you can help me restore my (themed) context-drop-menu while using Firefox 91+:

From (After Firefox 91):
![From](https://user-images.githubusercontent.com/22816976/129423794-832208b3-b2bf-4799-ae7f-f85169c04387.png)

To (Before Firefox 91):
![To](https://user-images.githubusercontent.com/22816976/129423117-4c9d5c88-5d82-4f0d-a9cf-c7d096ce529e.png)

You provided me with the following code (a long while ago) that worked perfectly till Firefox 91:

my_userChrome.css:
```cc
menupopup, 
menupopup menugroup {
  -moz-appearance: none !important;
  background: #dadce4 !important;
  border: 1.5 !important;
}

menupopup > :-moz-any(menu,menuitem,menugroup) label {
  color: black !important;
}

menupopup > :-moz-any(menu,menuitem,menugroup)[disabled] label {
  opacity: 0.5  !important;
}

menupopup menuseparator {
 -moz-appearance: none !important;
  border-top-color: #c0c0c0 !important;
  border-bottom-color: #f0f0f0 !important;
  padding-bottom: 0px !important;
  padding-top: 0px !important;
  margin-inline-start: 30.1px;
}

menupopup {
  background: linear-gradient(to right, #dadce4 26px, #c0c0c0 26px, #c0c0c0 27px, #f0f0f0 27px, #f0f0f0 28px, #dadce4 28px) !important;
  box-shadow: -1px -1px 1px #404040 inset !important;
  padding-bottom: 1px !important;
  padding-right: 1px !important;
}
```

Thank you in advance for the help and reply.

**Comment by Aris-t2** [comment]
Here is a quick workaround for some menupopups excluding everything bookmarks related. Bookmark popups need a different solution.


```css
menupopup:not(#BMB_bookmarksPopup,#OtherBookmarksPopup,[placespopup="true"]) :is(menu,menuitem,menugroup) label {
  color: black !important;
}

menupopup:not(#BMB_bookmarksPopup,#OtherBookmarksPopup,[placespopup="true"]) :is(menu,menuitem,menugroup)[disabled] label {
  opacity: 0.5  !important;
}

menupopup:not(#BMB_bookmarksPopup,#OtherBookmarksPopup,[placespopup="true"]) menuseparator {
 -moz-appearance: none !important;
  border-top-color: #c0c0c0 !important;
  border-bottom-color: #f0f0f0 !important;
  padding-bottom: 0px !important;
  padding-top: 0px !important;
  margin-inline-start: 26.1px !important;
  margin-inline-end: 0px !important;
}

menupopup:not(#BMB_bookmarksPopup,#OtherBookmarksPopup,[placespopup="true"]) {
   appearance: none !important;
   -moz-window-shadow: cliproundedunset !important;
   background-color: unset !important;
   /*background: linear-gradient(to right, #dadce4 26px, #c0c0c0 26px, #c0c0c0 27px, #f0f0f0 27px, #f0f0f0 28px, #dadce4 28px) !important;*/
   background: linear-gradient(to right, -moz-dialog 26px, #c0c0c0 26px, #c0c0c0 27px, #f0f0f0 27px, -moz-dialog 28px, -moz-dialog 28px) !important;
   border: 1px solid #c0c0c0 !important;
   border-radius: unset !important;
   --panel-color: unset !important;
   --panel-border-radius: unset !important;
   --panel-padding: unset !important;
   --panel-border-color: unset !important;
   --panel-background: unset !important;
   --nested-margin: unset !important;
  -moz-default-appearance: unset !important;
  --panel-background: unset !important;
  --nested-margin: unset !important;
  --panel-padding: unset !important;
  --panel-border-radius: unset !important;
  --panel-width: unset !important;
}

menupopup:not(#BMB_bookmarksPopup,#OtherBookmarksPopup,[placespopup="true"]) > menuitem,
menupopup:not(#BMB_bookmarksPopup,#OtherBookmarksPopup,[placespopup="true"]) > menu {
  padding-block: unset !important;
  padding-inline-start: unset !important;
}
   
menupopup:not(#BMB_bookmarksPopup,#OtherBookmarksPopup,[placespopup="true"]) menu,
menupopup:not(#BMB_bookmarksPopup,#OtherBookmarksPopup,[placespopup="true"]) menuitem,
menupopup:not(#BMB_bookmarksPopup,#OtherBookmarksPopup,[placespopup="true"]) menucaption {
  appearance: menuitem !important;
}

menupopup:not(#BMB_bookmarksPopup,#OtherBookmarksPopup,[placespopup="true"]) menu:not(.menu-iconic),
menupopup:not(#BMB_bookmarksPopup,#OtherBookmarksPopup,[placespopup="true"]) menuitem:not(.menuitem-iconic,[checked="true"]) {
  padding-inline-start: 30px !important;
}

menupopup:not(#BMB_bookmarksPopup,#OtherBookmarksPopup,[placespopup="true"]) menuitem:is([type="checkbox"],[type="radio"]):not([checked="true"]) {
  padding-inline-start: 24px !important;
}

menupopup:not(#BMB_bookmarksPopup,#OtherBookmarksPopup,[placespopup="true"]) .menu-iconic-left {
  padding-inline-start: 6px !important;	
}

/* compatibility with context_bfrsb_labels_without_icons.css / context_bfrsb_labels_with_icons.css*/
@media (-moz-os-version:windows-win10), (-moz-os-version:windows-win8), (-moz-os-version:windows-win7) {

  #context-navigation :is(#context-back,#context-forward,#context-reload,#context-stop,#context-bookmarkpage) {
	appearance: menuitem !important;
	min-height: unset !important;
  }
  
  #context-navigation :is(#context-back,#context-forward,#context-reload,#context-stop,#context-bookmarkpage):hover {
	background-color: unset !important;
  }
  
  #context-navigation > .menuitem-iconic > .menu-iconic-left > .menu-iconic-icon {
    width: 22px !important;
    height: 22px !important;
    padding: inherit !important;
    margin-top: inherit !important;
	margin-bottom: inherit !important;
	margin-inline-start: -6px !important;
	margin-inline-end: 2px !important;
  }
  
  #context-navigation :is(#context-back,#context-forward,#context-reload,#context-stop,#context-bookmarkpage):after {
	margin-inline-start: 6px !important;
  }
}
```

**Comment by DavyRay** [comment]
I just updated to 4.0.5 from 4.0.0 and i am trying to get my old settings back.  A lot has changed and certain items got changed along the way and i am having difficulty figuring out what to fix.

1. Menu items (bookmark or right-click) are really spaced apart. I would like to get them back to be more compact.

2. I had code set in my_userChrome.css to give a 2px spacing between the tabs so they were not so close to each other. see below.  It no longer works.
#tabbrowser-tabs .tab-context-line {display: none;} /* 2px container line */


I can always put back my old CSS files before I went to 4.0.5 and it will work.

I also recall posting something comments in this thread, but i can no longer see anything that I had posted.  I also do not see anything newer than 16 days ago on this thread.  Which seems odd

**Comment by Aris-t2** [comment]
You can add a space before tabs using this:

```css
#tabbrowser-tabs[haspinnedtabs]:not([positionpinnedtabs]) > #tabbrowser-arrowscrollbox > .tabbrowser-tab[first-visible-unpinned-tab] {
  margin-inline-start: 0px !important;
}
```

**Comment by DavyRay** [comment]
@Aris-t2 

i had the following lines in my_userchrome file

#tabbrowser-tabs .tab-context-line {display: none;} /* 2px container line */

#tabbrowser-tabs .tab-background {border-bottom: solid 2px var(--identity-icon-color) !important;} /* 2px highlight line for active tab  */


if I remove those 2 lines to put in the one you suggest, the spacing does not change. and I also use Multi-Account containers plugin.  It has a color line below each tab to let me know what container a specific tab is in.  If I remove those 2 lines, the colors go away. I think perhaps because the tab is now shorter. Though I am not sure why, but logically I think that is why.

**Comment by Aris-t2** [comment]
Post a screenshot. The above code needs a value greater than 0 (I forgot to mention it).

**Comment by DavyRay** [comment]
When I add your code in, it adds a space between the pinned tabs and the non pinned tabs.  Not between all the tabs

Here is an image without your code
![image](https://user-images.githubusercontent.com/44904766/131377532-5e34d72a-3d4b-4813-8ebf-bcb6ef2bf309.png)

Here is the image with your code and i added 12Px.  All it seems to do is put a space between the pinned tabs and the non pinned tabs.
![with space](https://user-images.githubusercontent.com/44904766/131378182-3916a883-73f0-444d-ad34-7d771a9b3652.jpg)

Here is a screen shot before I upgraded to 4.0.5.  This is what I am hoping to achieve.
![all spaces](https://user-images.githubusercontent.com/44904766/131378225-c41d21cb-b353-4fb9-ab5b-1e23b0cb663b.jpg)

This is an image showing the blue and yellow line below using the container addon for FF.  I need those 2 lines of code otherwise those colour lines do not show up.  Maybe if i could figure out how to put those lines on top of the tab instead of the bottom, then that may be another  solution for that
![image](https://user-images.githubusercontent.com/44904766/131378294-876533a6-187e-4948-b893-a17e4e90e067.png)

**Comment by droolio** [comment]
Just updated from v3.3.2.1 to v4.0.5 and re-enabled proton via about:config, after my update to FF 91 screwed up the tab bar completely.

I've searched and searched and can't find a way to **get back the old 'Photon' (FF 89) square tab** look. Not the 'classic square tabs' or 'squared tabs austrialized' older look - just any modern look where the tabs don't look like buttons! Non-floating, and connected to the main window below.

I use a bunch of modifications from CustomCSSforFx - mainly tabs below nav/bookmarks - otherwise, this is roughly what I'm looking for:

https://github.com/pellaeon/firefox-91plus-photon-userchrome

This is what my bars look like atm:

![image](https://user-images.githubusercontent.com/997518/131418778-2b6d8a32-ad5c-44b5-a023-ddfd961c643b.png)

Don't mind a bit of rounding and gaps, it's the not-sitting-on-the-window below bit that makes them not look like actual 'tabs', y'know?

**Comment by Aris-t2** [comment]
@DavyRay 
Forget the above code. This one should do the trick for you:

```css
#TabsToolbar .tabbrowser-tab {
  padding-inline: 1px !important;
}
```

@droolio 
I had plans to restore the Fx57-88 Photon tabs later. Your post made me remember that. ;-)
Test https://github.com/Aris-t2/CustomCSSforFx/releases/tag/4.0.6pre1
It is still WIP. Separators are not yet restored. It works with tabs below navigation toolbar and below main content.

![image](https://user-images.githubusercontent.com/6013569/131466941-c323ceb1-8b5e-487f-9fd4-9ddf7d8ddb7b.png)
