### ISSUE TITLE
Bookmarks Overflow Menu FF v92 Appearance

### ISSUE THREAD

**Issue by ChasCB** [Aris-t2/CustomCSSforFx#415]
Since Version 92 the Bookmarks overflow menu has changed dramatically with all white background and wider line spacing - it looks terrible. I disabled my own my_userChrome.css with no effect.
Previous versions had a gradient grey/white background like the Bookmarks Left hand Sidebar background still does.
Is it possible to add a css file to correct this so it reverts back to version 91 appearance? 
Thank you

macOS 15.7
FF V92

**Bookmarks Toolbar overflow menu**

![FF v92 Bookmarks Overflow menu](https://user-images.githubusercontent.com/7608263/132607883-9b9eecbe-4eea-4e9d-a0ca-85e315b7b364.png)

**Comment by Speravir** [comment]
Service link regarding @Pizzapops answer
> see my post in **Proton - tweaks (real compact mode)** for the mod to make popup menus more compact.

[Message from 6 days ago](https://github.com/Aris-t2/CustomCSSforFx/issues/334#issuecomment-912728824).

See also [Aris’ answer from yesterday](https://github.com/Aris-t2/CustomCSSforFx/issues/404#issuecomment-915359829) in the general discussion ticket. @Yaron10 had asked [2 days ago](https://github.com/Aris-t2/CustomCSSforFx/issues/404#issuecomment-914711947):
> What's the simplest way to display bookmarks (in the Bookmarks Toolbar) as menus?
(padding, background, border, separator etc.).

Quoting Aris:
> You can override variables used by Firefox, but they will affect more menus than just the bookmarks menus:
```css
:root {
  --panel-background: -moz-Dialog !important;
  --arrowpanel-background: -moz-Dialog !important;
  --panel-color: unset !important;
  --panel-border-color: unset !important;
  --panel-border-radius: 0px !important;
  --panel-padding: 0px !important;
  --panel-subview-body-padding: 0px !important;
  --arrowpanel-border-radius: 0px !important;
  --arrowpanel-menuitem-margin: 0px !important;
  --arrowpanel-menuitem-padding: 0px !important;
  --arrowpanel-menuitem-border-radius: 0px !important;
}
```
