### ISSUE TITLE
How change margin, restore icon in context menu and "plus" button

### ISSUE THREAD

**Issue by gabri25ele** [Aris-t2/CustomCSSforFx#435]
Sorry but I'm going crazy looking for these options... so I try to ask

1) How to change the **margin** in all menu to have the default value.

example:

standard customcssforfx
![002](https://user-images.githubusercontent.com/33927879/148933346-544c95e4-1d27-4300-9775-fb197d206443.png)

default value
![1002](https://user-images.githubusercontent.com/33927879/148933363-156d5651-24f0-4e44-a162-9227ba46e0d6.png)

2) How to **restore** the **icons** in context menu items: **'back', 'forward', 'reload', 'stop', 'bookmarks'** 

standard customcssforfx
![003](https://user-images.githubusercontent.com/33927879/148933491-8ff65381-8fd6-4df6-a677-482ccf1cc450.png)

default icons ('back', 'forward', 'reload', 'stop', 'bookmarks')
![1003](https://user-images.githubusercontent.com/33927879/148933523-e29ec30a-3c05-46a6-998b-6ac0ad9d2a3a.png)

3) How to **change color** of simple "**+**" (new tab)
![plus](https://user-images.githubusercontent.com/33927879/148933865-cd29500a-fd5e-4141-858a-abd05dd55152.png)

I found this (and works, added at userChrome.css)

#tabs-newtab-button{
  fill:white !important;
}

.tabs-newtab-button:hover{
  fill: white !important;
  background-color: rgba(255, 0, 0, 0.8) !important;
  border-radius: 4px;
}

is there an option in CustomCSSforFx for this?

**Comment by gabri25ele** [comment]
I found that the first two cases are caused bt enable compact menu
/* @import "./css/generalui/popup_compact_menus.css";

is possibile to not enable that item and to have the menu in classic **line spacing**?

**Comment by Aris-t2** [comment]
1. Menus in Firefox use different rules for different items. You can not solve this the easy way. Modify this code and change the values to get closer to what you are looking for:

```css
:root{
  --arrowpanel-menuitem-margin: 0px !important;
  --arrowpanel-menuitem-padding: 0 2px !important;
}

menupopup > menuitem,
menupopup > menu {
  padding-block: 2px !important;
  padding-inline-start: 22px !important;
}
```

2. Disable `context_bfrsb_labels_without_icons.css` option.

3. 
```css
#tabs-newtab-button .toolbarbutton-icon {
  fill: red !important;
}
```

**Comment by gabri25ele** [comment]
My mystake in first question...
I had mistakenly enabled compact mode, 

In the third question... the problem is when the browser has a color (dark) taken from windows theme and when Firefox is not on the top the "+" is not visible with a light color

![notactive](https://user-images.githubusercontent.com/33927879/149120655-46bf3f4a-6edf-4b33-ae37-a39edb91398b.png)

change color is a possibility to make it visible with both the dark and light bars ... it would be perfect instead to have an option for the color with window in the foreground and one for when the window is in the background, but I think it is not possible.

**Comment by Aris-t2** [comment]
This should cover all cases.

```css
/* default */
#tabs-newtab-button .toolbarbutton-icon {
  fill: black !important;
}

/* lw-theme with dark text */
#main-window:-moz-lwtheme-darktext #tabs-newtab-button .toolbarbutton-icon {
  fill: black !important;
}

/* lw-theme with bright text */
#main-window:-moz-lwtheme-brighttext #tabs-newtab-button .toolbarbutton-icon {
  fill: white !important;
}
```

**Comment by gabri25ele** [comment]
thanks... but with the automatic system theme, only the first entry is the one that matters, right?
the problem is that with the **automatic system theme**  Firefox takes the color with the active window, while with the window not active, the tab bar changes to clear.

![Video-29](https://user-images.githubusercontent.com/33927879/149371642-4143e04c-4711-4b93-a740-20582a5d16a5.gif)

the '+' is always the same color ... then... can't I keep the color of the Tab bar even with the Firefox window **not-active**?

**Comment by Aris-t2** [comment]
You can try to use

```css
#tabs-newtab-button .toolbarbutton-icon {
  fill: currentColor !important;
}
```
or create even more rules:


```css
/* default */
#tabs-newtab-button .toolbarbutton-icon {
  fill: black !important;
}

#main-window:-moz-window-inactive {
  fill: grey !important;
}

/* lw-theme with dark text */
#main-window:-moz-lwtheme-darktext #tabs-newtab-button .toolbarbutton-icon {
  fill: black !important;
}

/* lw-theme with dark text */
#main-window:-moz-window-inactive:-moz-lwtheme-darktext #tabs-newtab-button .toolbarbutton-icon {
  fill: grey  !important;
}

/* lw-theme with bright text */
#main-window:-moz-lwtheme-brighttext #tabs-newtab-button .toolbarbutton-icon {
  fill: white !important;
}

/* lw-theme with bright text */
#main-window:-moz-window-inactive:-moz-lwtheme-brighttext #tabs-newtab-button .toolbarbutton-icon {
  fill: grey !important;
}
```
