### ISSUE TITLE
[Windows][tabs not on top mode] move navigation toolbar to Firefox titlebar

### ISSUE THREAD

**Issue by Torbins** [Aris-t2/CustomCSSforFx#44]
Hi!
Can you, please, add this style to your pack: https://support.mozilla.org/en-US/questions/1185966 ?

**Comment by userOperaFF** [comment]
If you no time to test / find diff:

in  [tabs_below_navigation_toolbar.css](https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/css/tabs/tabs_below_navigation_toolbar.css): 
```css

/* Line 85 */
#TabsToolbar{
  border-top: 1px solid var(--tabs-border) !important;
  margin-bottom: 0px !important;
  border-bottom: 1px solid var(--tabs-border) !important;
}

/* Line 102 */
#main-window[tabsintitlebar][sizemode="normal"] #toolbar-menubar[autohide="true"][inactive="true"],
#main-window[tabsintitlebar][sizemode="maximized"] #toolbar-menubar[autohide="true"][inactive="true"] {
  /*margin-top: 21px !important;*/
}

/* added by Torbins */
#nav-bar {
  border-top: none !important;
  --toolbar-bgcolor: unset !important;
  margin-right: 110pt;
  background: rgba(255,255,255,.0) !important;
}

```
 with comment other css in userChrome.css (minimum comment`appbutton_in_titlebar.css`)
