### ISSUE TITLE
GENERAL discussion, feedback, questions belong here! (v15)

### ISSUE THREAD

**Issue by Aris-t2** [Aris-t2/CustomCSSforFx#452]
## Make sure you have updated your configuration to the most recent version of this projects files _and_ are using the latest version of the "options" required by your Firefox version >_before_< reporting problems!

Continued from https://github.com/Aris-t2/CustomCSSforFx/issues/3, https://github.com/Aris-t2/CustomCSSforFx/issues/41, https://github.com/Aris-t2/CustomCSSforFx/issues/88, https://github.com/Aris-t2/CustomCSSforFx/issues/109, https://github.com/Aris-t2/CustomCSSforFx/issues/133, https://github.com/Aris-t2/CustomCSSforFx/issues/163, https://github.com/Aris-t2/CustomCSSforFx/issues/189, https://github.com/Aris-t2/CustomCSSforFx/issues/211, https://github.com/Aris-t2/CustomCSSforFx/issues/241, https://github.com/Aris-t2/CustomCSSforFx/issues/273, https://github.com/Aris-t2/CustomCSSforFx/issues/308, https://github.com/Aris-t2/CustomCSSforFx/issues/368, https://github.com/Aris-t2/CustomCSSforFx/issues/404 and https://github.com/Aris-t2/CustomCSSforFx/issues/417

Instead of opening new "issues" for general talk we can use this area for discussions, feedback and questions. Open new "issues" for real bugs and problems.

**Custom JS scripts to restore more classic features**
https://github.com/Aris-t2/CustomJSforFx

**Things this project will not target/recreate**
- a CTR like plugin/application to generate ready-to-use CSS
- curved tabs (thanks those are finally gone!)
- old complete themes

**Things not possible with CSS**
- more toolbars like add-on/status bar (CSS can not create new toolbars)
  - displaying full sized status popup below window content is possible
  - bookmarks toolbar at windows bottom is possible (simulated addon-bar)
- new buttons (CSS can not create new buttons)
- additional menuitems (CSS can not create new items)
- custom/new/different functions for buttons/menuitems/menus
- activity indicator (see 'custom JS scripts')
- preference/options window
- additional location bar
- favicon in location bars identity box (see 'custom JS scripts')
- moving menubar items to a different toolbar
- restart button (see 'custom JS scripts')
- ... many more

**Comment by Aris-t2** [comment]
Get v4.1.5v2. Initial release only works, if "alternative appearance" for add-ons manager is active.

Switch tab item:
Hiding the url stops jumping.
Hiding the switch to tab item did not work as expected.

**Comment by mzso** [comment]
@Aris-t2 
Not sure if it's a good trade-off then. The URL is actually useful. And without it appearing, there's no indication that the item won't be switching tabs.

**Comment by BoomerangAide** [comment]
Installed CSS 4.1.5v2, and found a bug: in the "about" window, the button to download a new version is displayed with a black background when it should be gray, possibly a weird hardcoded use of the dark theme I'm not using?
Seen on 96.0.3 (that's the version of my portable version for testing)

On another note, I (apparently so far) currently managed to kill animations and other nonsense of my ie6 download button with the following code:
```css
/* Prevent download button from turning into something else */

#downloads-button:-moz-any([progress],[counter],[paused],[attention]) #downloads-indicator-progress-outer,
#downloads-button[attention] > #downloads-indicator-anchor > #downloads-indicator-icon {
	background: -moz-image-rect(url("./image/toolbar_fx_ie6.png"), 0, 198, 18, 180) center no-repeat !important;
	-moz-context-properties: unset !important;
}

#downloads-button[indicator="true"] {
	list-style-image: url("./image/toolbar_fx_ie6.png") !important;
	-moz-image-region: rect(0px, 198px, 18px, 180px) !important;
}

#downloads-indicator-start-image, 
#downloads-indicator-finish-image {
	list-style-image: url("./image/toolbar_fx_ie6.png") !important;
	-moz-image-region: rect(0px, 198px, 18px, 180px) !important;
	-moz-context-properties: unset !important;
}

#downloads-button[progress] > .toolbarbutton-badge-stack > #downloads-indicator-anchor > #downloads-indicator-icon,
#downloads-button[animate][notification] > .toolbarbutton-badge-stack > #downloads-indicator-anchor > #downloads-indicator-icon {
  visibility: visible !important;
}

#downloads-indicator-progress-outer {
	border: none !important;
}

#downloads-button > .toolbarbutton-badge-stack > .toolbarbutton-animatable-box {
	display:none !important;
}

#downloads-button[attention="info"] > .toolbarbutton-badge-stack > .toolbarbutton-badge {
	-moz-context-properties: unset !important;
}

#downloads-indicator-progress-inner{
	display: none !important;
}
/**/
```
Now I'm gonna see if there are some things I can remove from all that, but I wanted to share it as is, in the case I break it and can't find how to repair it 😛

**Comment by Aris-t2** [comment]
@mzso 
I will look for a better solution.

@BoomerangAide 

> Installed CSS 4.1.5v2, and found a bug: in the "about" window, the button to download a new version is displayed with a black background when it should be gray, possibly a weird hardcoded use of the dark theme I'm not using?
Seen on 96.0.3 (that's the version of my portable version for testing)

This happens without any custom code for me too.

**Comment by nicolaasjan** [comment]
Firefox 97.0, Linux; CustomCSSforFx 4.1.5 

I use : `@import "./css/locationbar/icons_colorized.css"`.
But now there is no padding between the colorized icons and text...:
![screenshot1](https://user-images.githubusercontent.com/14093220/153839934-ceac9daf-da29-432e-942b-e1fe41cddf52.png)

**Comment by Aris-t2** [comment]
Sounds like the Linux code is not applied properly after recent changes:

Does this work:

```css
@media (-moz-platform: linux) {

  :is(#context-back,#context-forward,#context-reload,#context-stop,#context-bookmarkpage) image {
	margin: 0 !important;
	width: 16px !important;
	height: 16px !important;
  }

  :is(#context-back,#context-forward,#context-reload,#context-stop,#context-bookmarkpage):after {
	margin-inline-start: 6px !important;
  }

}
```

or just this:


```css
  :is(#context-back,#context-forward,#context-reload,#context-stop,#context-bookmarkpage) image {
	margin: 0 !important;
	width: 16px !important;
	height: 16px !important;
  }

  :is(#context-back,#context-forward,#context-reload,#context-stop,#context-bookmarkpage):after {
	margin-inline-start: 6px !important;
  }
```
