### ISSUE TITLE
Appbutton in tab bar

### ISSUE THREAD

**Issue by suhr** [Aris-t2/CustomCSSforFx#46]
I want application button back in the tab bar, where it was before.

I use Linux, and `appbutton_in_titlebar.css` is Windows only.

**Comment by Aris-t2** [comment]
The button is always on navigation toolbar, but the "in titlebar" tricks places it windows to left corner.

Move it with this code to a different position. You will need to adjust the code for your needs.

```css
#PanelUI-button {
  -moz-appearance: none !important;
  -moz-box-ordinal-group: 0 !important;
  position: absolute !important;
  top: 22px !important;
  left: 2px !important;
}
```
You also may have to adjust tabs toolbar by moving it to the right:

```css
#TabsToolbar{
  -moz-padding-start: 30px !important;
}
```

**Comment by suhr** [comment]
Awesome, thank you!

How can I also remove round corners from this button? `border-radius: 0 0 0 0 !important;` doesn't seem to work.

**Comment by Aris-t2** [comment]
Try the inner button `#PanelUI-menu-button`.

**Comment by suhr** [comment]
Still doesn't work.

**Comment by Aris-t2** [comment]
```css
#PanelUI-button #PanelUI-menu-button .toolbarbutton-badge-stack {
	border-radius: 0 !important;
}
```
