### ISSUE TITLE
Padding Above the Tabs is Back in FF v101

### ISSUE THREAD

**Issue by gashtal** [Aris-t2/CustomCSSforFx#471]
1. Issue description:

**Starting from Firefox v101, the padding above the tabs (between top of tabs and top of browser) is back while using the latest version of CustomCSSforFx.**

2. Does the issue occur with latest CustomCSSforFx release?

**Yes, tested with 4.1.8v3.**

3. Steps to reproduce the issue:

**- Update to Firefox v101.**
**- Use CustomCSSforFx 4.1.8v3 with default configuration.**

4. SCREENSHOT(S) of the issue (drag & drop images into this post):
![171982305-7b30fc5e-2f49-45f9-8301-56efbc73c8ab](https://user-images.githubusercontent.com/27990818/173204273-265fa9da-7dde-44d7-aeb2-3965176b4d0e.png)

5. Is 'about:config > toolkit.legacyUserProfileCustomizations.stylesheets' set to 'true'?

**Yes.**

6. System information
- OS & OS version: **Windows 10 21H1 x64**
- DPI / HiDPI (e.g. 100%, 125%...): **100%**
- Firefox version: **101.0.1 (64-bit)**
- Firefox theme (e.g. default, dark, 'theme name & link'): **default**
- This projects userChrome.css/userContent.css 'settings' the issue occurs with: **default**

**Comment by Aris-t2** [comment]
Test https://github.com/Aris-t2/CustomCSSforFx/releases/tag/4.1.9pre

**Comment by gashtal** [comment]
@Aris-t2 The test solved the problem; than you for the very quick fix. :)

**Comment by dcoder42** [comment]
This fixes it for me too. I noticed the min/max/close buttons on Windows 10 are a bit too close to the top/right position

**Comment by schelef** [comment]
@Aris-t2 thanks

**Comment by ImSpecial** [comment]
I'm guessing whatever change you did with this now causes the tabs text to shift upward when moving tabs around? Was working fine before with v4.1.8, noticed this new behavior when I updated to 4.1.9.

**Comment by Aris-t2** [comment]
The recent tab changes are using this code:

```css
/* Fx 101+ */
#main-window[sizemode="maximized"][tabsintitlebar] #titlebar {
  margin-top: -5px !important;
}

#main-window[sizemode="fullscreen"][tabsintitlebar] #titlebar {
  margin-top: -3px !important;
}

#main-window[sizemode="maximized"][tabsintitlebar] #toolbar-menubar {
  padding-top: 5px !important;
}
```

Any chance you post a screenshot of the environment this change causes the mentioned issue for you.
