### ISSUE TITLE
sidebar_show_on_hover.css doesn't seem to work

### ISSUE THREAD

**Issue by ko56** [Aris-t2/CustomCSSforFx#475]
1. Issue description:
I expect that having the following in my `userChrome.css`
`@import "./css/generalui/sidebar_show_on_hover.css"; /**/`
will make the sidebar appear when my mouse hovers over it for a little bit.  Instead, it 
shows a thicker scrollbar.  And when I change the `8px` below to `28px`, nothing seems to happen:

```
:root{
  --sidebar-hover-width: 8px;
  --sidebar-visible-width: 300px;
}
```

2. Does the issue occur with latest CustomCSSforFx release?
Yes, I have classic [4.1.9v2](https://github.com/Aris-t2/CustomCSSforFx/commit/13d531e75acf5c56a92f0bd5ae0ca5b8e8b4cbec)

3. Steps to reproduce the issue:
As in 1. I also have
`@import "./css/generalui/sidebar_header_icons_colorized.css"; /**/`
And the sidebar is set on the right.

4. SCREENSHOT(S) of the issue (drag & drop images into this post):
I don't know how to make one with the mouse hovering over the sidebar.

5. Is 'about:config > toolkit.legacyUserProfileCustomizations.stylesheets' set to 'true'?
Yes, I have many other customizations in `userCrome.css` that al work fine.

6. System information
- OS & OS version:  FreeBSD 13.0
- DPI / HiDPI (e.g. 100%, 125%...):  96
- Firefox version: 101.0.1
- Firefox theme (e.g. default, dark, 'theme name & link'): default
- This projects userChrome.css/userContent.css 'settings' the issue occurs with: all default settings

**Comment by Aris-t2** [comment]
`sidebar_show_on_hover.css` works fine here. Make sure you enable the sidebar too, e.g. `Ctrl+B`.

**Comment by ko56** [comment]
I downloaded  `CustomCSSforFx-master.zip` and copied `CustomCSSforFx-master/classic/*` to my `.mozilla/firefox/<profile>/chrome/`, entirely unmodified.
Then I uncommented the line 
`@import "./css/generalui/sidebar_show_on_hover.css"; /**/`
in `userChrome.css.` This is the only change I made to `CustomCSSforFx-master/classic/*`.
The `View->Sidebar` menu item of Firefox has `Bookmarks` checked.
Still nothing happens when the mouse hovers over the right side of the window, other than the display of a somewhat thicker scrollbar.
What am I doing wrong?

**Comment by Aris-t2** [comment]
I believe there was no official option to move the sidebar to the right back then when this feature was added to the project.

Replace the content of `sidebar_show_on_hover.css` with this:

```css
/* Firefox userChrome.css tweaks ********************************************************/
/* Github: https://github.com/aris-t2/customcssforfx ************************************/
/****************************************************************************************/

:root{
  --sidebar-hover-width: 8px;
  --sidebar-visible-width: 300px;
}

#sidebar-box #sidebar {
  min-width: var(--sidebar-hover-width) !important;
  width: var(--sidebar-hover-width) !important;
  max-width: var(--sidebar-hover-width) !important;
  opacity: 0 !important;
  position: absolute !important;
  display: block !important;
}

#sidebar-box:hover #sidebar {
  min-width: var(--sidebar-visible-width) !important;
  width: var(--sidebar-visible-width) !important;
  max-width: var(--sidebar-visible-width) !important;
  opacity: 1.0 !important;
}

#sidebar-box #sidebar-header {
  visibility: collapse !important;
}
#sidebar-box:hover #sidebar-header {
  visibility: visible !important;
}

#sidebar-box {
  z-index: 1000 !important;
  position: relative !important;
  opacity: 0 !important;
}

#sidebar-box:hover {
  opacity: 1.0 !important;
}

#sidebar-box:not([positionend="true"]) {
  margin-inline-end: calc(-1 * var(--sidebar-hover-width)) !important;
}

#sidebar-box:not([positionend="true"]):hover {
  margin-inline-end: unset !important;
}

#sidebar-box:not([positionend="true"]) ~ #appcontent {
  margin-inline-start: calc(-1 * var(--sidebar-hover-width)) !important;
}

#sidebar-box:not([positionend="true"]):hover ~ #appcontent {
  margin-inline-start: calc(-1 * (var(--sidebar-visible-width) + var(--sidebar-hover-width))) !important;
}

#sidebar-box[positionend="true"] {
  margin-inline-start: calc(-1 * var(--sidebar-hover-width)) !important;
}

#sidebar-box[positionend="true"]:hover {
  margin-inline-start: unset !important;
}

#sidebar-box[positionend="true"] ~ #appcontent {
  margin-inline-end: calc(-1 * var(--sidebar-hover-width)) !important;
}

#sidebar-box[positionend="true"]:hover ~ #appcontent {
  margin-inline-end: calc(-1 * (var(--sidebar-visible-width) + var(--sidebar-hover-width))) !important;
}

```

There is still a glitch present when hovering the menu. Sidebar closes, because the cursor is technically on popup menu.
