### ISSUE TITLE
Firefox 103.0 broke the css to restore OS accent colors

### ISSUE THREAD

**Issue by noresk1** [Aris-t2/CustomCSSforFx#480]
The css that restores OS accent colors is no longer working as of Firefox 103.0

**Comment by noresk1** [comment]
Sorry, should have been a bit more specific. It's the "./css/toolbars/top_toolbar_OS_accent_colors.css" that is no longer working.

**Comment by Aris-t2** [comment]
Test this file.

<details> <summary> top_toolbar_OS_accent_colors.css </summary>

```css
/* Firefox userChrome.css tweaks ********************************************************/
/* Github: https://github.com/aris-t2/customcssforfx ************************************/
/****************************************************************************************/


  :root[sizemode=normal][tabsintitlebar] {
	border-top: 1px solid rgba(0,0,0,.7) !important;
  }
  :root[sizemode=normal][tabsintitlebar][always-use-accent-color-for-window-border]:not(:-moz-window-inactive) {
    border-top-color: -moz-accent-color !important;
  }
  :root[tabsintitlebar]:not(:-moz-lwtheme) {
    background-color: hsl(235,33%,19%) !important;
    color: hsl(240,9%,98%) !important;
  }

  :root[sizemode=normal][tabsintitlebar] {
    border-top: 1px solid -moz-accent-color !important;
  }
  :root[tabsintitlebar]:not(:-moz-window-inactive, :-moz-lwtheme),
  :root[tabsintitlebar]:not(:-moz-window-inactive)[lwt-default-theme-in-dark-mode] {
    background-color: -moz-accent-color !important;
    color: -moz-accent-color-foreground !important;
  }
  :root[tabsintitlebar][lwt-default-theme-in-dark-mode] #titlebar {
    --toolbarbutton-icon-fill: currentColor !important;
    --toolbarbutton-icon-fill-opacity: .7 !important;
  }

```
</details>

**Comment by noresk1** [comment]
It brought color back, but not what I was expecting.

 

This is from my Firefox ESR, which is what I expect.



 

This is from your test file.

**Comment by Aris-t2** [comment]
Yes, the files is a complete replacement.

The code to change colors is the same as before, but the check using media rules is gone, because Mozilla removed it, so I had to drop it too.

https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/css/toolbars/top_toolbar_OS_accent_colors.css#L6
https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/css/toolbars/top_toolbar_OS_accent_colors.css#L19

**Comment by noresk1** [comment]
After I compared your test file and the original I noticed the dropping of the media rules.

 

Do you think you’ll be able to fix the file to inherit the OS color scheme or has that ship now sailed?

**Comment by noresk1** [comment]
The test file is now showing a dark blue accent, but not my selected OS accent which is green. Can this be fixed?
Thanks

**Comment by Aris-t2** [comment]
Looks like Mozilla removed the "proper" way to achieve this.

We can cheat Win 7 AeroGlass code to get accent colors, but it wont offer the same results.

Accent color for windows:
```css
    :root {
      background-color: transparent !important;
      appearance: auto !important;
      -moz-default-appearance: -moz-win-borderless-glass !important;
    }
    #appcontent {
      appearance: auto !important;
      -moz-default-appearance: -moz-win-exclude-glass !important;
    }
```
