### ISSUE TITLE
Lubuntu 22.04.1 and titlebar with menubar activated

### ISSUE THREAD

**Issue by Firefoxfan** [Aris-t2/CustomCSSforFx#522]
1. Does the issue occur without any files inside /chrome/ folder?
no

2. Issue description, userChrome.css/userContent.css 'settings' the issue occurs with and steps to reproduce the issue:
With activ userChrome.css/userContent.css and activating titlebar and menubar in FF, the text of the menubar and the buttonbar are overlapping and the entries of menubar are nearly unreadable.

3. Does the issue occur with the most recent version of CustomCSSforFx (release/test/dev build)?
actual release 4.2.6

4. Screenshots showing the issue (drag & drop images into this post):
![grafik](https://user-images.githubusercontent.com/49429671/206118921-a26fc7ee-e2ec-440f-91e6-1455160797cb.png)

5. System information
- Lubuntu 22.04.1 (no problem in Windows 11 Pro using the same configuration of CustomCSSforFx]
- DPI: 100 %
- Firefox version:  107.0.1
- Firefox theme build in light
- Is 'about:config > toolkit.legacyUserProfileCustomizations.stylesheets' set to 'true': yes
- Is 'about:config > layout.css.moz-box-flexbox-emulation.enabled' set to 'true' (Fx 107 only): yes

**Comment by Aris-t2** [comment]
This happens with `tabs_below_navigation_toolbar_alt.css`, right?

Add this to the bottom of the mentioned file:

```css
/* Linux */
@media (-moz-platform: linux) {
	/* set to '0', if no menubar is used */
	#main-window:not([tabsintitlebar]):not([sizemode="fullscreen"]) #nav-bar {
	  margin-top: 26px !important;
	}
}
```
