### ISSUE TITLE
Couple "tab" related issues with FF 108.0

### ISSUE THREAD

**Issue by ImSpecial** [Aris-t2/CustomCSSforFx#525]
I hate Firefox update day!

I wanted to report some issues I'm now noticing with Firefox after an update this morning, I made some gifs of the problem, so hopefully they should tell the story better then I can.

Issue # 1
---------
Tab text now have this "fade" effect when the text is too long for the tab, now to stop the "cutting off" from happening when the mouse hovers over them?
https://i.imgur.com/9tcFCIE.gif

Issue # 2
---------
When moving tabs around, there's this "divider" of sorts line that appears, I'm guessing maybe it has to do with the tab button?
https://i.imgur.com/Dd7BsNz.gif

And normally I have this "tab button" removed from my bar (as shown now), but the line is still there, also without the button present my tabs now have this slight shifting upwards...
https://i.imgur.com/MCURMLa.gif

Any ideas?

**Comment by Aris-t2** [comment]
Looks like devs a busy on modifying ui again, but in areas, where no changes where needed...

Issue # 1
I guess you are using `tab_close_hidden.css`, right?

This should do the trick:

```css
:root{
  --tab-label-mask-size: 0 !important;
}

#TabsToolbar #tabbrowser-tabs .tabbrowser-tab:not([pinned]) .tab-close-button {
  visibility: hidden !important;
  opacity: 0 !important;
  min-width: 0.5px !important;
  width: 0.5px !important;
  max-width: 0.5px !important;
  padding-inline-start: unset !important;
  margin-inline-end: unset !important;
  padding: 0px !important;
}
```

Issue # 2
The options for classic squared and photon tabs already hide the devider between Firefox view button and tabs, but this code should help you:

```css
:root:not([privatebrowsingmode=temporary]) :is(toolbarbutton, toolbarpaletteitem) + #tabbrowser-tabs,
:root[privatebrowsingmode=temporary] :is(toolbarbutton:not(#firefox-view-button), toolbarpaletteitem:not(#wrapper-firefox-view-button)) + #tabbrowser-tabs {
  border-inline-start: 0px  !important;
}
```

**Comment by ImSpecial** [comment]
Both issues are now fixed because of that above code :). (I still get the shifting tabs on move though... :/)

So looks like my custom css has grown even larger...

Curious, is this a "me" problem, or for "everyone"? will a proper fix be in a future CustomCSSforFx release update?

**Comment by ImSpecial** [comment]
Another minor thing I'm noticing is there's now a gap between the edge and the first tab IF you have the about:config preference; 

`browser.tabs.firefox-view` set to `false`
https://i.imgur.com/xUMfrne.png

if `browser.tabs.firefox-view` is set to `true` this gap goes away...
https://i.imgur.com/ON0yoUY.png

Is there any way to fix this gap while the preference set to false?

**Comment by ImSpecial** [comment]
While it still might be a bug in your CSS, I figured out how to get rid of this gap.

Enable Firefox View via preference if you had it disabled before, unhide it if you are with CSS, now that you can see the button, just right-click it and "unpin" it from firefox naturally (yes Mozilla is allowing you to. /shock). Now that its gone you can disable View again via preference.

**Comment by Aris-t2** [comment]
I think this is more like a bug of `browser.tabs.firefox-view` preference, because it only hides the button, but keeps the space created before tabs. This should help:

```css
:root:not([privatebrowsingmode=temporary]) :is(toolbarbutton, toolbarpaletteitem) + #tabbrowser-tabs,
:root[privatebrowsingmode=temporary] :is(toolbarbutton:not(#firefox-view-button), toolbarpaletteitem:not(#wrapper-firefox-view-button)) + #tabbrowser-tabs {
  border-inline-start: 0px  !important;
  padding-inline-start: 0px  !important;
  margin-inline-start: 0px  !important;;
}
```

The space will be hidden by these options hide after the next update (some already do):
classic_squared_tabs.css
classic_squared_tabs_australized.css
default_tabs_photon.css
tabs_below_navigation_toolbar.css
tabs_below_navigation_toolbar_alt.css
tabs_below_navigation_toolbar_macOS.css
