### ISSUE TITLE
[Feature Request] Add the ability to customize Reader Mode background color

### ISSUE THREAD

**Issue by R8s6** [Aris-t2/CustomCSSforFx#527]
1. Does the issue occur without any files inside /chrome/ folder?
No

2. Issue description, userChrome.css/userContent.css 'settings' the issue occurs with and steps to reproduce the issue:

Currently by default, if we enable Reader Mode for a webpage, and select the Dark mode:
![](https://i.imgur.com/5jGqJjG.png)

The background color will be like this:
![](https://i.imgur.com/eIMk0mj.png)

It's dark but not dark enough to my taste. 

Is there a way to customize the background (and font) color using hex codes like `#00AABB`?

3. Does the issue occur with the most recent version of CustomCSSforFx (release/test/dev build)?
Yes.

4. Screenshots showing the issue (drag & drop images into this post):
Please see Question 2.

5. System information
- OS & OS version: Arch Linux Arm
- DPI / HiDPI (e.g. 100%, 125%...): 160
- Firefox version: 108.0
- Firefox theme (e.g. default, build in light/dark, external theme + link): built-in Dark
- Is 'about:config > toolkit.legacyUserProfileCustomizations.stylesheets' set to 'true': Yes.
- Is 'about:config > layout.css.moz-box-flexbox-emulation.enabled' set to 'true' (Fx 107 only): v108, so N/A.

Thank you very much!

**Comment by Aris-t2** [comment]
The variables would affect alle webpages, that use "dark-mode", but yes, it is possible.

Add this to your **my_userContent.css** file.

```css
:root {
  --dark-theme-background: #000000 !important;
  --dark-theme-foreground: #00AABB !important;
}
```


![image](https://user-images.githubusercontent.com/6013569/207871368-036bb140-0c0a-43ee-9ad1-7c78f220721f.png)

**Comment by R8s6** [comment]
Hi @Aris-t2 

Thanks for the suggestion! Sorry it's my first time using `my_userContent.css` file, is this how it's done:

In `./userContent.css`, I have:

```
@import "./my_userContent.css"; /**/
```
And in `./my_userContent.css`, i have:

```
:root {
  --dark-theme-background: #000000 !important;
  --dark-theme-foreground: #00AABB !important;
}
```
Is this enough to enable it? 

Asking because I don't see anything changes after restarting firefox (but everything else works as usual).

Thanks!

**Comment by Aris-t2** [comment]
You did everything right. I did not double check.

Unfortunately Firefox 108 and 110 use different variable names. This will work on both:

```css
:root {
  --dark-theme-background: #000000 !important;
  --dark-theme-foreground: #00AABB !important;
  --dark-background: #000000 !important;
  --dark-foreground: #00AABB !important;
}
```
