### ISSUE TITLE
[Fx58][default tabs] How to change or set tab border color

### ISSUE THREAD

**Issue by suhr** [Aris-t2/CustomCSSforFx#53]
It lacks the left border.

![2017-11-17-163630_1920x1080_scrot](https://user-images.githubusercontent.com/65870/32949978-a61fcffa-cb9c-11e7-94f0-f4337734db41.png)

**Comment by Aris-t2** [comment]
Is the border present, if you don't move the appbutton there?

What settings are you using, Which windows are you on?

**Comment by suhr** [comment]
> Is the border present, if you don't move the appbutton there?

No.

> What settings are you using, Which windows are you on?

Linux, i3wm.

**Comment by suhr** [comment]
> Is the border present, if you don't move the appbutton there?

No.

> What settings are you using, Which windows are you on?

Linux, i3wm.

**Comment by Aris-t2** [comment]
Is this the default theme or the "Light compact" theme?

**Comment by suhr** [comment]
Standard compact. I removed the blue line on an active tab with `.tab-line { display: none !important; }`.

FF 58 beta.

**Comment by Aris-t2** [comment]
Alright I see, you have not written, that this is about default tabs and not the squared tabs offered by CustomCSSforFx project.

Set border colors like this:

```css
.tabbrowser-tab {
  border-top: 1px solid var(--tabs-border-color) !important;
  border-left: 1px solid var(--tabs-border-color) !important;
  border-right: 1px solid var(--tabs-border-color) !important;
}
```

**Comment by suhr** [comment]
Now it looks like this:

![2017-11-17-212239_1920x1080_scrot](https://user-images.githubusercontent.com/65870/32962470-796538ec-cbc4-11e7-85de-825407d6d613.png)

Not exactly the result I wanted to achieve.

**Comment by suhr** [comment]
```
#PanelUI-button #PanelUI-menu-button .toolbarbutton-badge-stack {
  border-radius: 0 !important;
  border-right: 1px solid var(--tabs-border-color) !important;
}
```

This gives a natural looking result when the leftmost tab is selected, but when it's not it looks weird:

![2017-11-17-213011_1920x1080_scrot](https://user-images.githubusercontent.com/65870/32962867-f12962b2-cbc5-11e7-8119-1167cf955e6b.png)

I want the app button to look as natural as the `+` button looks.

**Comment by Aris-t2** [comment]
You have to adopt the code for your needs.

Only active tab needs borders, right? Or maybe left and right borders only?

Experiment with the code

```css
.tabbrowser-tab[selected=true] {
  border-left: 1px solid var(--tabs-border-color) !important;
  border-right: 1px solid var(--tabs-border-color) !important;
}
```

**Comment by suhr** [comment]
It would be easier if I knew what I actually try to CSS.

Anyway, CSS I have already looks reasonable good. I'll share it, maybe it will be useful for someone else:

```css
@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");

#PanelUI-button {
  -moz-appearance: none !important;
  -moz-box-ordinal-group: 0 !important;
  position: absolute !important;
  top: -29px !important;
}

#PanelUI-button #PanelUI-menu-button .toolbarbutton-badge-stack {
  border-radius: 0 !important;
  border-right: 1px solid var(--tabs-border-color) !important;
}

#TabsToolbar{
  -moz-padding-start: 30px !important;
}

.tab-line{
  display: none !important;
}
```
