### ISSUE TITLE
popup_compact_menus change also toolbar space icons

### ISSUE THREAD

**Issue by gabri25ele** [Aris-t2/CustomCSSforFx#535]
In the new 108 Firefox, the toolbar drop-down menu is wide again

![large](https://user-images.githubusercontent.com/33927879/208108848-8a3b70eb-cc01-47e0-88c3-0df15eb10098.png)

but if I enable popup_compact_menus, icon in toolbar is large

![after](https://user-images.githubusercontent.com/33927879/208109047-4f6b2fb0-efa9-4930-a1e0-f7cfee117edb.png)

if I disable icon in toolbar is closer

![closer](https://user-images.githubusercontent.com/33927879/208109186-57b5fbae-a8a4-4ea4-8f3e-e5effbb664db.png)

so they should be in both cases

am i doing something wrong?

...

actually I'm more interested in restricting the drop-down menu of the toolbar, (not the compact mode), however before the 108 it was like this:
![firefox precedente menu a discesa](https://user-images.githubusercontent.com/33927879/208112733-97c5b4cb-26a9-4992-a97c-67545693fbd5.png)

**Comment by Aris-t2** [comment]
Does this help you?

```css
#customizationui-widget-multiview #appMenu-libraryView,
#pageActionPanel panelview,
#widget-overflow panelview {
  min-width: 0 !important;
}
```

**Comment by Aris-t2** [comment]
Upload your chrome folder.

I have no idea how this code https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/css/generalui/popup_compact_menus.css would affect toolbar buttons on toolbar, because its rules strictly apply to stuff inside popups.

**Comment by gabri25ele** [comment]
my chrome folder?
ok
[chrome.zip](https://github.com/Aris-t2/CustomCSSforFx/files/10251971/chrome.zip)

**Comment by Aris-t2** [comment]
You have plenty to other code inside you chrome folder. Could you test [4.2.7v3](https://github.com/Aris-t2/CustomCSSforFx/releases) without any other tweaks?

**Comment by Aris-t2** [comment]
If it is only about the vertical space, you have to enable `popup_compact_menus.css` and replace its content with the code below. The variable `--item_y_padding: 0px;` controls the vertical padding. Default value was 3px.

<details> <summary> popup_compact_menus.css </summary>

```css
/* Firefox userChrome.css tweaks ********************************************************/
/* Github: https://github.com/aris-t2/customcssforfx ************************************/
/****************************************************************************************/


:root{
  --item_y_padding: 0px;
  --y_padding_before_label: 28px !important; /* for popup_menus_space_before_label.css */
  --y_padding_before_label_bm: calc(var(--y_padding_before_label) - 2px ) !important; /* for popup_menus_space_before_label.css */
  --panel-padding: 0px !important;
  --arrowpanel-menuitem-margin: 0px !important;
  --arrowpanel-menuitem-padding: calc( var(--item_y_padding) + 1px) 2px !important;
  --panel-subview-body-padding: 0px !important;
}

.subview-subheader,
panelview .toolbarbutton-1,
.subviewbutton:not(#appMenu-fxa-status2),
.widget-overflow-list .toolbarbutton-1 {
  margin: 0 !important;
  min-height: 0 !important;
  padding: calc( var(--item_y_padding) + 1px) 2px !important;
}

.widget-overflow-list .toolbarbutton-1 {
  padding: var(--item_y_padding) 2px !important;
}

#appMenu-popup .PanelUI-subView .subviewbutton:not(#appMenu-fxa-status2) {
  padding: calc( var(--item_y_padding) + 1px) 4px !important;
}
	
menupopup[type=arrow] > menuitem,
menupopup[type=arrow] > menu {
  padding-block: 0 !important;
  padding: var(--item_y_padding) 0 !important;
  padding-inline-start: 4px !important;
}

.panel-subview-body {
  padding: 0px !important;
}

* menupopup[type=arrow],
:is(menupopup, panel)[type=arrow] {
  --panel-padding: 0px !important;
}

#context-navigation :is(#context-back,#context-forward,#context-reload,#context-stop,#context-bookmarkpage) {
  padding: var(--item_y_padding) 2px !important;
  margin-inline-start: -6px !important;
}

:is(#context-back,#context-forward,#context-reload,#context-stop,#context-bookmarkpage) image {
  margin: 0 !important;
  padding: 0 !important;
  padding-inline-start: 4px !important;
  height: 16px !important;
}

:is(menupopup, panel)[type=arrow] :is(.menu-accel,.menu-iconic-accel) {
  margin-inline-end: 8px !important;
}

:is(menupopup, panel)[type=arrow] .menu-right {
  margin-inline-end: 4px !important;
}

.menu-iconic-icon {
  margin-inline-start: 2px !important;
  margin-inline-end: -2px !important;
}

@media (-moz-platform: windows-win10),(-moz-os-version:windows-win10) {
	
  menupopup > menuitem,
  menupopup > menu {
	padding-block: 0 !important;
	padding: var(--item_y_padding) 0 !important;
	padding-inline-start: 4px !important;
  }

  * menupopup {
	--panel-padding: 0px !important;
  }
  :is(menupopup, panel) :is(.menu-accel,.menu-iconic-accel) {
	margin-inline-end: 8px !important;
  }

  :is(menupopup, panel) .menu-right {
	margin-inline-end: 4px !important;
  }

  /* support for context_bfrsb_labels_with_icons.css */
  menugroup#context-navigation > menuitem.menuitem-iconic > hbox.menu-iconic-left > .menu-iconic-icon {
	margin-top: 0px !important;
	margin-bottom: 0px !important;
	margin-inline-start: 10px !important;
	margin-inline-end: 6px !important;
  }

}

#customizationui-widget-multiview #appMenu-libraryView,
#pageActionPanel panelview,
#widget-overflow panelview {
  min-width: 0 !important;
  padding: var(--item_y_padding) 0 !important;
}

#unified-extensions-panel .unified-extensions-item {
  padding-block: 0 !important;
  padding: 0 !important;
}

.unified-extensions-item-name,
.unified-extensions-item-message {
  padding-inline-start: 0 !important;
}

```

</details>

**Comment by Aris-t2** [comment]
The above change is part of [4.2.8 release](https://github.com/Aris-t2/CustomCSSforFx/releases) now.

**Comment by gabri25ele** [comment]
> If it is only about the vertical space, you have to enable `popup_compact_menus.css` and replace its content with the code below. The variable `--item_y_padding: 0px;` controls the vertical padding. Default value was 3px.
> popup_compact_menus.css

yes, we return to the same problem at the beginning

but if I enable popup_compact_menus, icon in toolbar is large



if I disable icon in toolbar is closer

**Comment by Aris-t2** [comment]
Unfortunately I do not know how to help you. I have no idea why `popup_compact_menus` affects buttons placed on toolbar, because the code was specifically made to target popups/menus only.

May this helps you:

```css
#customizationui-widget-multiview #appMenu-libraryView,
#pageActionPanel panelview,
#widget-overflow panelview {
  min-width: 0 !important;
  padding: 0 !important;
}
```
