### ISSUE TITLE
FF109 crashes with AeroGlass transparency (glass8.eu)

### ISSUE THREAD

**Issue by CO-Windler** [Aris-t2/CustomCSSforFx#548]
I am using "custom_css_for_fx_v4.2.5.zip" on an old Win10 together with AeroGlass by glass8.eu on my Thinkpad X61t.

Since the Firefox browser update to 109.0 the glass8.eu extension for toolbars causes a fatal crash. Starting Firefox, its window appears frameless, incomplete and shrivels smaller (resizes itself) until it almost disappears. (I can only close it through taskbar.) Firefox is unusable when enabled. 

So I had to disable it by commenting out this line:

`/* @import "./css/toolbars/general_toolbar_colors_aeroglass_windows10_glass8.css"; /**/`

Please fix this. Firefox looks terrible with default white Win8-style titlebar buttons and missing AeroGlass transparency effects.

**Comment by Aris-t2** [comment]
Looks like recent changes removed the previous glass rule. I took the one Firefox uses for Win7.

Replace the content of the mentioned file with this:

```css
/* Firefox userChrome.css tweaks ********************************************************/
/* Github: https://github.com/aris-t2/customcssforfx ************************************/
/****************************************************************************************/


/* Glass8 ( http://www.glass8.eu/ ) required for 'Windows 7'-like window transparency */

@-moz-document url(chrome://browser/content/browser.xul), url(chrome://browser/content/browser.xhtml) {
	#main-window {
      background-color: transparent !important;
      appearance: auto !important;
      -moz-default-appearance: -moz-win-borderless-glass !important;
	}
}
#main-window:not([customizing]) .titlebar-button,
#main-window:not([customizing]) .titlebar-button:not(#titlebar-close) > .toolbarbutton-icon{
  opacity: 0.01 !important;
}

#main-window:not([customizing]) .titlebar-button:hover {
  opacity: 1 !important;
}

#main-window:not([customizing]) .titlebar-button:not(#titlebar-close):hover {
  opacity: 0.1 !important;
  background: black !important;
}

```
