### ISSUE TITLE
[Request] Tabbar Context Menu Cleanup

### ISSUE THREAD

**Issue by ImSpecial** [Aris-t2/CustomCSSforFx#55]
A small follow up to https://github.com/Aris-t2/CustomCSSforFx/issues/50 's request

The [new tab_context_menuitems_visibility options](https://i.imgur.com/rcqKXfa.png) that were added is awesome! Can I request the same for [the Tabbar](https://i.imgur.com/KKtVm34.png), for some consistency between the two, there's not much to this menu though.

**Comment by Aris-t2** [comment]
I will look into it.

**Comment by ImSpecial** [comment]
Great dude! I noticed one tiny little thing though, there seems to be another separator that was missed, I like to have the one after Undo for the toolbar, but with it left alone, clicking on add-ons show a double separator one I image is . You might need to squint so see it, no big deal really, but you know, perfection.

https://i.imgur.com/KBzXdkD.png
https://i.imgur.com/8ytjvU0.png
https://i.imgur.com/ziFAq85.png

**Comment by Aris-t2** [comment]
There was no separator I missed. The one you see on your screenshots gets added by the add-on "Skip Redirect" and does not get hidden even, if it should.

It misses this code
```css
#skipredirect_sblask_copy-last-source-url[disabled="true"],
#skipredirect_sblask_copy-last-source-url[disabled="true"] + menuseparator {
 display: none !important;
}
```
