### ISSUE TITLE
Firefox View button is missing

### ISSUE THREAD

**Issue by ZTHawk** [Aris-t2/CustomCSSforFx#561]
After upgrading to CustomCSS 4.3.1v7 the Firefox View button disappeared:
![grafik](https://user-images.githubusercontent.com/23618799/220448817-2b9ee6d8-ab5a-4758-9226-306735d553a7.png)
Going back to 4.1.3 will make the button reappear:
![grafik](https://user-images.githubusercontent.com/23618799/220448968-18927346-4066-4a9b-9119-5604d14641e3.png)

I am using default settings (`tabs_firefox_view_button_hidden` is not active).

Edit:
The button is visible if `classic_squared_tabs` and/or `default_tabs_photon` is disabled.

**Comment by krystian3w** [comment]
Rather, it is hidden intentionally (deliberately/on purpose).

Seemingly from within the my_userChrome.css file it will work:

```css
#firefox-view-button {
   display: -moz-box !important;
}
```

But squared tabs resize that icon to enormous. Draft resize with enabled squared tabs:

```css
#firefox-view-button image {
   max-width: 16px !important;
   max-height: 16px !important;
}
```

Then looks similar to "default tabs photon".

---

Theoretically, you can try to exclude hiding it in editor mode:

```css
html:not([customizing="true"]) #firefox-view-button {
   display: none !important;
}
```

Perhaps it is similarly possible to detect whether it is in the default position in the row, it is unlikely to detect whether someone has moved it:

```css
html:not([customizing="true"]) .toolbar-items > hbox.customization-target > #firefox-view-button:first-child {
   display: none !important;
}
```
