### ISSUE TITLE
[Request] tabs below address bar and bookmarks bar below tabs

### ISSUE THREAD

**Issue by zebbr** [Aris-t2/CustomCSSforFx#599]
hi,
any chance you could add another option to the tabs below feature?

before my ff upgraded i had address bar at top, then tabs and booksmark bar below tabs. but now i'm stuck with address bar, then bookmarks bar and then tabs.

can't find any way to get the order back to how i had it.

**Comment by Aris-t2** [comment]
I'm not sure how much maintaining this will require, if this will become an own "option", but once you enabled `tabs_below_navigation_toolbar.css`, you can add this code to your `my_userChrome.css` file:

```css
#TabsToolbar {
  bottom: 30px !important;
}

#PersonalToolbar {
  margin-top: 26px !important;
}

#navigator-toolbox {
  padding-bottom: 0 !important;
}
```

You might have to use different values in your config.

![image](https://github.com/Aris-t2/CustomCSSforFx/assets/6013569/dd4dc1f6-aabf-43f1-b237-e7e901547740)
