### ISSUE TITLE
Bookmark bar icon padding increased

### ISSUE THREAD

**Issue by DJRBuckingham** [Aris-t2/CustomCSSforFx#613]
1. Does the issue occur without any files inside /chrome/ folder?
Yes.

2. Issue description, userChrome.css/userContent.css 'settings' the issue occurs with and steps to reproduce the issue:
The padding between icons on the bookmark bar has increased and setting the various padding-left/right settings in "buttons_on_bookmarks_toolbar_old_size_and_appearance.css" appears to have no effect.

This does occur without CustomCSSForFx installed, so may be a FF bug, but equally they may have changed element names/etc and thus the .css needs updating. Apologies if this not an appropriate issue to open, or has already been opened & closed - I couldn't see anything in the recent list.

3. Does the issue occur with the most recent version of CustomCSSforFx (release/test/dev build)?
Yes, with v4.4.0.

4. Screenshots showing the issue (drag & drop images into this post):
Old (FF v116.0 w/ v4.4.0)
![old](https://github.com/Aris-t2/CustomCSSforFx/assets/42737062/bebbf026-4260-4235-a97a-ad9962824b12)
New (FF v117.0 w/ v4.4.0)
![new](https://github.com/Aris-t2/CustomCSSforFx/assets/42737062/aab12249-08f4-433e-ab58-feb31cea477e)

5. System information
- OS & OS version: Windows 10
- DPI/HiDPI/scaling value, if not 100% (e.g. 125%, 150%...): 100%
- Firefox version: v117.0
- Firefox theme (e.g. default, build in light/dark, external theme + link): Default (light)

**Comment by RadeD0** [comment]
Confirming this, faced the same problem after upgrading to FF117

**Comment by Aris-t2** [comment]
Does this improve something?

```css
toolbarbutton.bookmark-item:not(.subviewbutton) {
  padding: 0 !important;
}
#PersonalToolbar {
  height: 18px !important;
}
```

**Comment by DJRBuckingham** [comment]
Yes, it does - thank you. I would say padding of 1px is about equivalent to how it used to be.

I also had to enable buttons_on_bookmarks_toolbar_aero_appearance_items.css otherwise there was no border/background when hovering over the icon. The border is also rounded rather than square as before, but that's fine for me.

**Comment by jack-ii** [comment]
> 
Not quite, the 0 makes a padding of 4px between the icons, before I had 2px (1 from left, 1 from right padding)

**Comment by Aris-t2** [comment]
You could try to also tweak the margin value:

```css
toolbarbutton.bookmark-item:not(.subviewbutton) {
  padding: 0px !important;
  margin: 0px !important;
}
```
