### ISSUE TITLE
Firefox 119.0 broke the color in selected tab

### ISSUE THREAD

**Issue by gabri25ele** [Aris-t2/CustomCSSforFx#627]
update Firefox to 119
update Customcssforfx and I read
'top_toolbar_OS_accent_colors.css' failed to work as expected on current Firefox versions and was removed
so how change title color and not active color?
ever in **general_variables.css**
how say here
https://github.com/Aris-t2/CustomCSSforFx/issues/480#

**Comment by Aris-t2** [comment]
> Firefox 119.0 broke the color in selected tab

Test [4.4.3 release](https://github.com/Aris-t2/CustomCSSforFx/releases).

I could reproduce the missing "active tab" color for some tab options.

> so how change title color and not active color?

Use `top_toolbar_colors.css` instead of the old `top_toolbar_OS_accent_colors.css`.

**Comment by gabri25ele** [comment]
> > Firefox 119.0 broke the color in selected tab
> 
> Test [4.4.3 release](https://github.com/Aris-t2/CustomCSSforFx/releases).

eh no, there is something wrong with this new version

I modified general variables 

  **/* for top_toolbar_colors.css */
  --top_toolbars_background: #0063b1 !important; 
  --top_toolbars_background_inactive: #ffffff !important;
  --top_toolbars_text: #ffffff !important;
  --top_toolbars_text_inactive: #999999 !important;**

but active tab is not transparent

![sshot-1](https://github.com/Aris-t2/CustomCSSforFx/assets/33927879/f7b297f2-998d-48cb-b066-52634a50b640)

the previous customcss version worked

![68747470733a2f2f692e696d6775722e636f6d2f7032514b526f542e706e67](https://github.com/Aris-t2/CustomCSSforFx/assets/33927879/a39d3fa5-d0c2-4066-9fe6-af30effebd9b)

**Comment by Aris-t2** [comment]
Why would changing titlebars and tab toolbars background color make active tab transparent?
This is not supposed to happen.

vanilla 4.4.3
- disabled classic_squared_tabs.css
- enabled default_tabs_photon.css
- enabled top_toolbar_colors.css

Result
![image](https://github.com/Aris-t2/CustomCSSforFx/assets/6013569/4c1134af-d948-4959-90cb-92a9786d29b0)

You might need something like this to get the active tab transparent:
```css
.tabbrowser-tab:is([selected],[multiselected]) {
  color: white !important;
}

.tabbrowser-tab:is([selected],[multiselected]) .tab-stack .tab-background {
  background: transparent !important;
  color: white !important;
}
```
With above code:
![image](https://github.com/Aris-t2/CustomCSSforFx/assets/6013569/375ffbc3-9099-48aa-ab39-247af0ed1adf)

**Comment by gabri25ele** [comment]
wait, not transparent.
I badly explained myself
this is the right way

![277634972-a39d3fa5-d0c2-4066-9fe6-af30effebd9b](https://github.com/Aris-t2/CustomCSSforFx/assets/33927879/b68bd818-02fc-4b92-87a8-5f074fb25559)

but with the 4.4.3 I don't have this result, but this

![277634824-f7b297f2-998d-48cb-b066-52634a50b640](https://github.com/Aris-t2/CustomCSSforFx/assets/33927879/18491209-365d-467a-9bef-91c62c3b50a0)

I think it's a problem in the new photon_alt css
because I replaced it with the old version and it works again

**Comment by gabri25ele** [comment]
If I enable default_tabs_photon.css, (instead of **default_tabs_photon_alt.css**) **very bad result**! 😵😵‍💫
this is not tabs_photon, this is **compact** tabs_photon and i don't want **compact** tab.
furthermore the tab active continues to be not white (see image)

![sshot-1](https://github.com/Aris-t2/CustomCSSforFx/assets/33927879/ae3d37eb-3403-497e-871a-a7940a41def9)

**Comment by gabri25ele** [comment]
it seems that I managed to get the card to come correctly by changing this value in default_tabs_photon_alt.css

.tab-background[multiselected],
.tab-background[selected] {
  
  background-image: var(--toolbar-bgimage) !important;
  background-color: #F9F9FA !important;
}


see image now

![now](https://github.com/Aris-t2/CustomCSSforFx/assets/33927879/1a04a798-6683-452b-bc07-71101f75e611)

but I think there is something wrong with 4.4.3 because with the previous version I didn't have to make all these changes for the active tab in "white" (the exact color would be #F9F9FA which blends in with the underlying background.

**Comment by Aris-t2** [comment]
I think themes and certain option combinations might cause different/broken results, because the code uses browsers color variables:

```css
.tab-background[multiselected],
.tab-background[selected] {
  background-color: var(--toolbar-bgcolor) !important;
  background-image: var(--toolbar-bgimage) !important;
}
```

All my tests are done in default state without any code combinations.

default_tabs_photon_alt.css looks like this for example with Colorful Abstract Neon 2.0 theme:
![image](https://github.com/Aris-t2/CustomCSSforFx/assets/6013569/3e6b43e2-49cb-41d0-82c1-9e42c7298595)

**Comment by gabri25ele** [comment]
aris, sorry I dont understand what are you saying. 
why now you're talking to me about themes.
I tell you that 4.4.3 doesn't work like 4.4.2v6
active tab is blue 
I don't want it transparent, but the same color as the bookmarks bar, like happens in 4.4.2v6
and I don't like the solution I found, (https://github.com/Aris-t2/CustomCSSforFx/issues/627#issuecomment-1777175891) for example in the anonymous window it is also colored
![prob](https://github.com/Aris-t2/CustomCSSforFx/assets/33927879/a6ecad10-51cd-48bc-b6d9-2a674b38db07)

**Comment by Aris-t2** [comment]
Look at the changes:
![image](https://github.com/Aris-t2/CustomCSSforFx/assets/6013569/1ab12cb2-e9f9-4a99-b4d2-03847b7a76c0)


The only thing changed between 4.4.2 and 4.4.3 was the removed `=true`. It caused the code not to work properly in Fx 119+. The result is intended to be the same as before, which is in my tests without any custom configuration.

Please backup everything in your chrome folder, extract the latest release there and change these three settings inside userChrome.css
- disabled classic_squared_tabs.css
- enabled default_tabs_photon.css
- enabled top_toolbar_colors.css

**Comment by gabri25ele** [comment]
> Please backup everything in your chrome folder, extract the latest release there and change these three settings inside userChrome.css
> 
>     * disabled classic_squared_tabs.css
> 
>     * enabled default_tabs_photon.css
> 
>     * enabled top_toolbar_colors.css

https://github.com/Aris-t2/CustomCSSforFx/issues/627#issuecomment-1777582959

try my test in a firefox portable
https://krakenfiles.com/view/qxPgoFIiBp/file.html

**Comment by Aris-t2** [comment]
Stay on version 4.4.2v6 until I find what is causing this and why.

**Comment by Aris-t2** [comment]
Test 4.4.3v2
https://github.com/Aris-t2/CustomCSSforFx/releases/tag/4.4.3

**Comment by runrunrirun** [comment]
Apologies if this is something else, but the tab bar since 119 dropped doesn't render text for inactive tabs (?) in the Firefox Syetem Default Theme on macOS.

![Screen Shot 2023-10-25 at 12 00 21 AM](https://github.com/Aris-t2/CustomCSSforFx/assets/1388365/bf6821bc-57cb-442a-84e2-d1b384af2c3d)

Looks the same in Light or Dark mode, the selected tab is the only one that has text. If I apply a 3rd party theme, then the tabs are normal. So maybe Mozilla broke the System Default theme somehow?

**Comment by gabri25ele** [comment]
> Test 4.4.3v2 https://github.com/Aris-t2/CustomCSSforFx/releases/tag/4.4.3

now everything seems fine 👌

**Comment by gabri25ele** [comment]
no problem, actually thank you for solving it so quickly...
Can I ask you a question...
to put the color of the line I modify the default_tabs_photon.css in this way
_.tabbrowser-tab[selected]:not([usercontextid]) .tab-context-line {
  background-color: #FF5037 !important;
}_

is this right or is there a better way to do it?

not very important, but is it possible to have another color of the line with the window not active?

**Comment by gabri25ele** [comment]
just another question, it's the last one, I swear!

always in inactive window I have this situation

![senza1](https://github.com/Aris-t2/CustomCSSforFx/assets/33927879/ffa0ada1-a7e1-449e-8676-6dccaa8d1d35)

but it is possible to put a line at the bottom of the tabs that closes and frames them? like this

![senza2](https://github.com/Aris-t2/CustomCSSforFx/assets/33927879/3771e4e0-2aff-4039-93c8-a839b9d3c803)

**Comment by Aris-t2** [comment]
Yes, there was a bug, that removed the line. It will be fixed on next update.

This works for now:

```css
* #nav-bar:not(:-moz-lwtheme) {
  box-shadow: 0 calc(-1 * var(--tabs-navbar-shadow-size)) 0 color-mix(in srgb, currentColor 20%, transparent) !important;
}
```

**Comment by Aris-t2** [comment]
> ...but is it possible to have another color of the line with the window not active?

Yes.

```css
#main-window:-moz-window-inactive .tabbrowser-tab[selected]:not([usercontextid]) .tab-context-line {
  background-color: red !important;
}
```

**Comment by gabri25ele** [comment]
> Yes, there was a bug, that removed the line. It will be fixed on next update.
> 
> This works for now:
> 
> ```css
> * #nav-bar:not(:-moz-lwtheme) {
>   box-shadow: 0 calc(-1 * var(--tabs-navbar-shadow-size)) 0 color-mix(in srgb, currentColor 20%, transparent) !important;
> }
> ```

ok very thanks you... very very thank you
but...

pay attention to the next update, 
the line **should not be present** (if possible) on the active tab in "foreground window mode"

![Senza titolo](https://github.com/Aris-t2/CustomCSSforFx/assets/33927879/6baf95dc-dc2e-478e-8769-7b8b07821a93)

**Comment by gabri25ele** [comment]
> > Yes, there was a bug, that removed the line. It will be fixed on next update.
> > This works for now:
> > ```css
> > * #nav-bar:not(:-moz-lwtheme) {
> >   box-shadow: 0 calc(-1 * var(--tabs-navbar-shadow-size)) 0 color-mix(in srgb, currentColor 20%, transparent) !important;
> > }
> > ```
> 
> ok very thanks you... very very thank you but...
> 
> pay attention to the next update, the line **should not be present** (if possible) on the active tab in "foreground window mode"
> 
> ![Senza titolo](https://user-images.githubusercontent.com/33927879/278301895-6baf95dc-dc2e-478e-8769-7b8b07821a93.png)

or even it is not necessary to be present in the entire window on the first floor

**Comment by noresk1** [comment]
As of this 119 release, I finally switched over to "top_toolbar_colors.css" from the modified approach using "top_toolbar_OS_accent_colors.css" that I had described in issue " Firefox 103.0 broke the css to restore OS accent colors #480 " 

Now I have a new challenge that I hope you can help with.  Can you tell me how I can get the left/right nav areas back to the generic light blue color instead of my custom color as now shown below? When I was using my modified OS_accent_colors css those two areas were matching the light blue area pointed to by the arrows. Thanks
![Capture](https://github.com/Aris-t2/CustomCSSforFx/assets/58830974/b45fa5a6-3aa4-48ef-9b3d-b4d7c77e08d1)

**Comment by noresk1** [comment]
I've also noticed that my currently active tab is not showing up highlighted. Any thoughts on that?

**Comment by noresk1** [comment]
Hovering over any tab highlights it, but the current active tab no longer shows hightlighted so it's difficult to know sometimes which of the many open tabs I have is actually selected.

**Comment by Aris-t2** [comment]
@gabri25ele 
Does the issue occur with `default_tabs_photon.css` or `default_tabs_photon_alt.css`?

![image](https://github.com/Aris-t2/CustomCSSforFx/assets/6013569/439f274c-e136-4663-b7a2-61ae68f17b02)

@noresk1 
Are you using the latest files? The active tab issue was fixed with 4.4.3 release.

"top_toolbar_colors.css" is mainly for the case where the tabs are on top. I can add a second version, that offers better compatibility for tabs below navigation toolbar.

**Comment by noresk1** [comment]
My bad, I'm on the latest files now and if you could add that enhanced version it would be appreciated. As you can see, the nav icons are now very washed out. Many thanks
![Capture](https://github.com/Aris-t2/CustomCSSforFx/assets/58830974/786a8c16-7416-40ea-a813-1de239491608)

**Comment by noresk1** [comment]
I would prefer leaving the title bar as white text, but would like the nav to be to be dark gray (much like when the window is inactive).

**Comment by Aris-t2** [comment]
```css
:root{
  --top_toolbars_background: hsl(235,33%,19%); /* #0063b1 */ /* hsl(235,33%,19%) was used by old accent color option  */ 
  --top_toolbars_background_inactive: hsl(235,13%,9%); /* #ffffff */
  --top_toolbars_text: #ffffff;
  --top_toolbars_text_inactive: #999999;
}

#main-window:not(:-moz-lwtheme) #titlebar,
#main-window:not(:-moz-lwtheme) #toolbar-menubar  {
  background: var(--top_toolbars_background) !important;
  color: var(--top_toolbars_text) !important;
}

#main-window:not(:-moz-lwtheme):-moz-window-inactive #titlebar,
#main-window:not(:-moz-lwtheme):-moz-window-inactive #toolbar-menubar {
  background: var(--top_toolbars_background_inactive) !important;
  color: var(--top_toolbars_text_inactive) !important;
}

#main-window:not(:-moz-lwtheme) #main-menubar > menu > label {
  color: var(--top_toolbars_text) !important;
}

#main-window:not(:-moz-lwtheme):-moz-window-inactive #main-menubar > menu > label {
  color: var(--top_toolbars_text_inactive) !important;
}

#main-window:not(:-moz-lwtheme) .titlebar-button,
#main-window:not(:-moz-lwtheme):-moz-window-inactive .titlebar-button,
#main-window:not(:-moz-lwtheme):-moz-window-inactive .titlebar-button.titlebar-close:hover {
  fill: CurrentColor !important;
}
```

**Comment by noresk1** [comment]
I just tried that, but have now lost the titlebar color.
![Capture1](https://github.com/Aris-t2/CustomCSSforFx/assets/58830974/e6b4ba2c-6a0a-4787-a721-f130e13ae92d)

**Comment by noresk1** [comment]
I tried coding my color in top_toolbar_colors in addition to already having it in general_variables but no change in behavior

**Comment by gabri25ele** [comment]
> @gabri25ele Does the issue occur with `default_tabs_photon.css` or `default_tabs_photon_alt.css`?

I use **default_tabs_photon_alt.css**

**Comment by gabri25ele** [comment]
> I tried coding my color in top_toolbar_colors in addition to already having it in general_variables but no change in behavior

I change color, here
https://github.com/Aris-t2/CustomCSSforFx/issues/627#issuecomment-1776975883

**Comment by Aris-t2** [comment]
> > @gabri25ele Does the issue occur with `default_tabs_photon.css` or `default_tabs_photon_alt.css`?
> 
> I use **default_tabs_photon_alt.css**

I will look into it.

> I tried coding my color in top_toolbar_colors in addition to already having it in general_variables but no change in behavior

Wait for next update. Variables are actually the same and can be used inside general variables css file like before.

**Comment by noresk1** [comment]
> > I tried coding my color in top_toolbar_colors in addition to already having it in general_variables but no change in behavior
> 
> Wait for next update. Variables are actually the same and can be used inside general variables css file like before.

Will do, thanks!

**Comment by noresk1** [comment]
Am now on 445 using top_toolbar_colors_v2 and all is goodness, thanks so much

**Comment by Aris-t2** [comment]
@gabri25ele

Is the issue still present with lates files?

**Comment by Aris-t2** [comment]
> > @gabri25ele Does the issue occur with `default_tabs_photon.css` or `default_tabs_photon_alt.css`?
> 
> I use **default_tabs_photon_alt.css**

`default_tabs_photon_alt.css` looks like this for me with current release:

(inactive window)
![image](https://github.com/Aris-t2/CustomCSSforFx/assets/6013569/c5ea2320-f704-48a2-be95-523023272de2)
(active window)

**Comment by gabri25ele** [comment]
> > > @gabri25ele Does the issue occur with `default_tabs_photon.css` or `default_tabs_photon_alt.css`?
> > 
> > 
> > I use **default_tabs_photon_alt.css**
> 
> `default_tabs_photon_alt.css` looks like this for me with current release:

ehi!
yes, seem work very good 👌

I see you added css/toolbars/**top_toolbar_colors_v2.css**
(I enabled this, instead top_toolbar_colors.css)
but then I always change general variables.css 😁

You could have included this too,
https://github.com/Aris-t2/CustomCSSforFx/issues/627#issuecomment-1779376625
maybe it would be useful to someone.

**Comment by gabri25ele** [comment]
wait... I have a problem...
the arrows with more tabs opened is in darl color (they weren't like that before)
![arrow](https://github.com/Aris-t2/CustomCSSforFx/assets/33927879/9731941b-dca9-42cc-a65b-9c2fe0c9a608)

**Comment by Aris-t2** [comment]
It seems you are using "tabs on top", then also keep `top_toolbar_colors.css`.
`top_toolbar_colors_v2.css` is mainly for tabs below navigation toolbar.

**Comment by gabri25ele** [comment]
> It seems you are using "tabs on top", then also keep `top_toolbar_colors.css`. `top_toolbar_colors_v2.css` is mainly for tabs below navigation toolbar.

both enabled, everything ok 👌

**Comment by gabri25ele** [comment]
> pay attention to the next update, the line **should not be present** (if possible) on the active tab in "foreground window mode"
> 
> ![Senza titolo](https://user-images.githubusercontent.com/33927879/278301895-6baf95dc-dc2e-478e-8769-7b8b07821a93.png)
> 
> or even it is not necessary to be present in the entire window in "foreground"

Firefox 123
the line come back 😨
what happens?

**Comment by gabri25ele** [comment]
wait...
I update css,

but now I can't change the color of the bar again. but why? don't you change here?

:root{
  --top_toolbars_background: #0063b1 */ /* hsl(235,33%,19%) was used by old accent color option  */ 
  --top_toolbars_background_inactive: #ffffff */
  --top_toolbars_text: #ffffff;
  --top_toolbars_text_inactive: #999999;
}

still dark!
![sshot-1](https://github.com/Aris-t2/CustomCSSforFx/assets/33927879/3c7dfc5f-2895-4180-b50f-516292e10dba)

damn!

**Comment by Aris-t2** [comment]
The issue was caused by an opacity change for inactive windows titlebar.

This should fix it:
```css
#main-window:-moz-window-inactive #titlebar {
  opacity: 1.0 !important;
}
```

**Comment by gabri25ele** [comment]
> The issue was caused by an opacity change for inactive windows titlebar.
> 
> This should fix it:
> 
> ```css
> #main-window:-moz-window-inactive #titlebar {
>   opacity: 1.0 !important;
> }
> ```

where would this be? I can not find. 😵‍💫

**Comment by gabri25ele** [comment]
tried also hsl code, the color does NOT change! 😭

:root{
  --top_toolbars_background: hsl(206,100%,35%); /* #0063b1 */ /* hsl(235,33%,19%) was used by old accent color option  */ 
  --top_toolbars_background_inactive: hsl(206,100%,35%); /* #ffffff */
  --top_toolbars_text: #ffffff;
  --top_toolbars_text_inactive: #999999;
}

**Comment by Aris-t2** [comment]
What exactly are you trying to achieve? Which color do you want to change?

The above code fix should remove the wrong line below the active tab for inactive windows. This issue was caused by Firefox.

The fix can be added to userChrome.css or my_userChrome.css.

**Comment by gabri25ele** [comment]
> What exactly are you trying to achieve? Which color do you want to change?

I want to change the bar of the tabs 

this dark 
![dark](https://github.com/Aris-t2/CustomCSSforFx/assets/33927879/7f951158-d7c0-4e1b-b0dd-d1bf57d2bcc5)
in a comfort blue
![confortblue](https://github.com/Aris-t2/CustomCSSforFx/assets/33927879/02991259-060b-40a6-9ab6-76e307578c77)
and the inactive in a blank version, like other programs do 
example
![tbsshot-1](https://github.com/Aris-t2/CustomCSSforFx/assets/33927879/ab86fb5a-0d91-4adc-abda-116e27332666)
![tbsshot-2](https://github.com/Aris-t2/CustomCSSforFx/assets/33927879/c3334f36-8adc-44f4-8fbe-138c729e9afa)

... and I was trying to change it to top_toolbar_colors_v2 when I didn't remember I had used the general_variables.css. 
So I wonder, is it better not to enable the general_variables.css ones or yes and do everything from there?

Then I see your code to opacity the tab.
I wonder, would it be possible to opaque the entire window while Not Focused? instead of just the bar?

**Comment by gabri25ele** [comment]
Maybe I'll stick with the general_variables.css 🤨

**Comment by gabri25ele** [comment]
Firefox 126 breaks the color again 😒

**Comment by Aris-t2** [comment]
Make sure you are using this projects latest files: https://github.com/Aris-t2/CustomCSSforFx/releases

`userChrome.css` > enable `top_toolbar_colors.css`
`general_variables.css` > change color variables `-top_toolbars*` to yours

This code does not work anymore in Fx 126+

```css
* #nav-bar:not(:-moz-lwtheme) {
  box-shadow: 0 calc(-1 * var(--tabs-navbar-shadow-size)) 0 color-mix(in srgb, currentColor 20%, transparent) !important;
}
```

Replace it with:

```css
:root:not([lwtheme]) * #nav-bar {
  box-shadow: 0 calc(-1 * var(--tabs-navbar-shadow-size)) 0 color-mix(in srgb, currentColor 20%, transparent) !important;
}
```

Not sure why you have issues with this one:

```css
#main-window:-moz-window-inactive .tabbrowser-tab[selected]:not([usercontextid]) .tab-context-line {
  background-color: red !important;
}
```
