### ISSUE TITLE
2 line megabar no longer indented

### ISSUE THREAD

**Issue by Silver-Nebula** [Aris-t2/CustomCSSforFx#633]
1. Does the issue occur without any files inside /chrome/ folder?
N/A. Issue is with a new setting in CustomCSSforFX

2. Issue description, userChrome.css/userContent.css 'settings' the issue occurs with and steps to reproduce the issue:
"./css/locationbar/ac_popup_megabar_title_and_url_two_lines.css";

This setting makes the megabar history entries show up as two lines. The first line contains the website icon, then the webpage Title. Second line contains the URL.

Previously, the second line was indented (which made the url text somewhat lineup with the title text). Now with FF119 and CustomCCforFX v4.4.4, the second line is left justified with no indent and makes skimming the entries a bit harder.

3. Does the issue occur with the most recent version of CustomCSSforFx (release/test/dev build)?
-> Check here: https://github.com/Aris-t2/CustomCSSforFx/releases <-
Yes

4. Screenshots showing the issue (drag & drop images into this post):

5. System information
- OS & OS version: Win10
- DPI/HiDPI/scaling value, if not 100% (e.g. 125%, 150%...): 100%
- Firefox version: 119
- Firefox theme (e.g. default, build in light/dark, external theme + link): Light

**Comment by Aris-t2** [comment]
Replace the code inside `ac_popup_megabar_title_and_url_two_lines.css` with this one and report back:

<details> <summary>ac_popup_megabar_title_and_url_two_lines.css </summary>

```css
/* Firefox userChrome.css tweaks ********************************************************/
/* Github: https://github.com/aris-t2/customcssforfx ************************************/
/****************************************************************************************/


/* based on [wrap]-code from default browser.css */

#urlbar .urlbarView-results > .urlbarView-row > .urlbarView-row-inner {
  flex-wrap: wrap !important;
}
#urlbar .urlbarView-results > .urlbarView-row > .urlbarView-row-inner > .urlbarView-no-wrap {
  max-width: 100% !important;
  flex-basis: 100% !important;
}
#urlbar .urlbarView-results > .urlbarView-row[has-url] > .urlbarView-row-inner > .urlbarView-url {
  margin-top: 2px !important;
  padding-inline-start: 23px !important;
}

#urlbar[actionoverride] .urlbarView-results > .urlbarView-row[has-url] > .urlbarView-row-inner > .urlbarView-no-wrap > .urlbarView-title-separator,
#urlbar .urlbarView-results > .urlbarView-row[has-url]:not([type$=tab]) > .urlbarView-row-inner > .urlbarView-no-wrap > .urlbarView-title-separator {
  display: none !important;
}

/* support for heuristic items: search, remote tab, switch to tab */
#urlbar .urlbarView-results > .urlbarView-row:is([type=search],[type=switchtab]) > .urlbarView-row-inner > .urlbarView-no-wrap > .urlbarView-title-separator,
#urlbar .urlbarView-results > .urlbarView-row:not([has-url]) > .urlbarView-row-inner > .urlbarView-no-wrap > .urlbarView-title-separator {
  display: none !important;
}

#urlbar .urlbarView-results > .urlbarView-row:is([type=search],[type=switchtab]) > .urlbarView-row-inner > .urlbarView-no-wrap {
  padding-bottom: 19px !important;
}

/*
#urlbar .urlbarView-results > .urlbarView-row:is([type=search],[type=switchtab]) > .urlbarView-row-inner > .urlbarView-no-wrap,
#urlbar .urlbarView-results > .urlbarView-row:not([has-url]) > .urlbarView-row-inner > .urlbarView-no-wrap {
  padding-bottom: 19px !important;
}

#urlbar .urlbarView-results > .urlbarView-row:is([type=remotetab]):not([selected]):not(:hover) > .urlbarView-row-inner > .urlbarView-no-wrap {
  padding-bottom: 15px !important;
}*/

#urlbar .urlbarView-results > .urlbarView-row:is([type=search],[type=switchtab]) > .urlbarView-row-inner > .urlbarView-no-wrap > .urlbarView-action,
#urlbar .urlbarView-results > .urlbarView-row:not([has-url]) > .urlbarView-row-inner > .urlbarView-no-wrap > .urlbarView-action,
#urlbar .urlbarView-results > .urlbarView-row:is([type=remotetab]):not([selected]):not(:hover) > .urlbarView-row-inner > .urlbarView-no-wrap > .urlbarView-action {
  display: block !important;
  position: absolute !important;
}

#urlbar .urlbarView-results > .urlbarView-row:is([type=search],[type=switchtab]) > .urlbarView-row-inner > .urlbarView-no-wrap > .urlbarView-action {
  margin-bottom: 30px !important;
  padding-inline-start: 24px !important;
}

#urlbar .urlbarView-results > .urlbarView-row:not([has-url]) > .urlbarView-row-inner > .urlbarView-no-wrap > .urlbarView-action {
  /*margin-bottom: 30px !important;*/
  padding-inline-start: 24px !important;
}

#urlbar .urlbarView-results > .urlbarView-row:is([type=remotetab]):not([selected]):not(:hover) > .urlbarView-row-inner > .urlbarView-no-wrap > .urlbarView-action {
  margin-bottom: -47px !important;
  padding-inline-start: 16px !important;
}

#urlbar .urlbarView-results > .urlbarView-row[type=switchtab] > .urlbarView-row-inner > .urlbarView-no-wrap > .urlbarView-action {
  margin-bottom: -47px !important;
  appearance: none !important;
  background: unset !important;
  padding-inline-start: 15px !important;
}

#urlbar .urlbarView-results > .urlbarView-row[type=remotetab] > .urlbarView-row-inner > .urlbarView-no-wrap > .urlbarView-action {
  appearance: none !important;
  background: unset !important;
}

#urlbar .urlbarView-row[dynamicType=onboardTabToSearch] > .urlbarView-row-inner {
  min-height: unset !important;
}

.urlbarView-row[dynamicType=onboardTabToSearch] > .urlbarView-row-inner > .urlbarView-no-wrap > .urlbarView-favicon {
  min-width: unset !important;
  height: unset !important;
}

.urlbarView-dynamic-onboardTabToSearch-description {
  display: none !important;
}

#urlbar .urlbarView-results > .urlbarView-row[has-url]:is([type=remotetab],[sponsored],[type=switchtab],[type=search]) > .urlbarView-row-inner > .urlbarView-url {
  display: none !important;
}

.urlbarView-row[rich-suggestion] > .urlbarView-row-inner > .urlbarView-favicon {
  width: 16px !important;
  height: 16px !important;
  flex-basis: 16px !important;
}

.urlbarView-row:not([rich-suggestion]),
.urlbarView-row[rich-suggestion][icon-size="16"] {
  --urlbarView-icon-margin-start: 0px !important;
  --urlbarView-icon-margin-end: 7px !important;
}

.urlbarView-row[label]::before {
  display: none !important;
}

.urlbarView-row[label] {
  margin-block-start: unset !important;
}

#urlbar .urlbarView-button-menu {
  z-index: 1 !important;
}

#urlbar .urlbarView-results > .urlbarView-row[rich-suggestion],
#urlbar .urlbarView-results > .urlbarView-row[role="presentation"]:is([type=search]) > .urlbarView-row-inner > .urlbarView-no-wrap > .urlbarView-action,
#urlbar .urlbarView-results > .urlbarView-row[role="presentation"]:not([has-url]) > .urlbarView-row-inner > .urlbarView-no-wrap > .urlbarView-action,
.urlbarView-row[role="presentation"][type="search"] .urlbarView-action {
  display: none !important;
}

/* Fx 119+ fix*/
.urlbarView-results[wrap] > .urlbarView-row {
    &[has-url] > .urlbarView-row-inner > .urlbarView-url {
      &:-moz-locale-dir(ltr) {
        margin-left: unset !important;
      }
      &:-moz-locale-dir(rtl) {
        margin-right: unset !important;
      }
    }
}
```
  
</details>
