### ISSUE TITLE
Firefox 124, Line spacing on elements in New Tab page

### ISSUE THREAD

**Issue by gabri25ele** [Aris-t2/CustomCSSforFx#643]
![i4gou5v005pc1](https://github.com/Aris-t2/CustomCSSforFx/assets/33927879/096c3524-8c53-4cbb-94dd-ba7825094984)

hey Aris, we need a default setting here ;)

**Comment by Aris-t2** [comment]
Test this inside "my_userContent.css" file or at the end of "userContent.css" file:

```css
.top-site-outer {
  width: 90px !important;
}

.top-site-outer .top-site-inner > a {
  padding: 5px 4px 2px !important;
}
```

Increase or decrease values the way you prefer it.
