### ISSUE TITLE
Can I have bookmarks toolbar below tabs?

### ISSUE THREAD

**Issue by FeodorPetrov** [Aris-t2/CustomCSSforFx#654]
I use
@import "./css/tabs/tabs_below_navigation_toolbar.css";
to place tabs below navigation toolbar.

But it is uncomfortable when bookmarks toolbar is above tabs, because I use showing of bookmarks toolbar only on new tab, and tabs toolbar always jumps up and down when I open a new tab.

Is this possible to place bookmarks toolbar below tabs?

I use firefox-126.0.1.

**Comment by Aris-t2** [comment]
Test this inside your `my_userChrome.css` file, while `tabs_below_navigation_toolbar.css` is active.

```css
#navigator-toolbox:has(#PersonalToolbar[collapsed="false"]) #TabsToolbar {
  bottom: 30px !important;
  border: 0 !important;
  box-shadow: unset !important;
}

#PersonalToolbar[collapsed="false"] {
  position: absolute !important;
  bottom: 0 !important; 
  width: 100% !important;
}

#navigator-toolbox:has(#PersonalToolbar[collapsed="false"]) {
  padding-bottom: 56px !important;
}
```
