### ISSUE TITLE
Is this possible to place status bar into location bar?

### ISSUE THREAD

**Issue by FeodorPetrov** [Aris-t2/CustomCSSforFx#655]
Is this possible to place status bar (lower left corner, showing loading addresses and links under mouse cursor) into location bar, how it was in firefox-3.6?

**Comment by Aris-t2** [comment]
Yes, it is possible.

You might have to adjust some values for your config:

```css
.urlbar-input-box::after {
  appearance: none; 
  display: flex;
  content: "";
  min-width: 200px;
  background-image: -moz-element(#statuspanel-label) !important;
  background-repeat: no-repeat;
}

#statuspanel-label {
  border: 0 !important;
  background-color: unset !important;
  padding-top: 6px !important;
  color: inherit !important;
}

#statuspanel {
  opacity: 0 !important;
}
```

**Comment by FeodorPetrov** [comment]
I have it doesn't fit all the way in...

![Screenshot_20240613_092109](https://github.com/Aris-t2/CustomCSSforFx/assets/163597288/dbdafa78-7992-48b4-80fa-56bae3cd4fd8)

**Comment by FeodorPetrov** [comment]
Is it possible to make it from left corner, not from right?

**Comment by FeodorPetrov** [comment]
So, I made
min-width: 2000px;
it, sort of, made it.

Thank you very much!

**Comment by Aris-t2** [comment]
The space has to be occupied using "min-width". You will run into the same issue, if placing statuspanel on the other side of location bar.

```css
#identity-box::before {
  appearance: none; 
  display: flex;
  content: "";
  min-width: 200px;
  background-image: -moz-element(#statuspanel-label) !important;
  background-repeat: no-repeat;
}

#statuspanel-label {
  border: 0 !important;
  background-color: unset !important;
  padding-top: 6px !important;
  color: inherit !important;
}

#statuspanel {
  opacity: 0 !important;
}
```
