### ISSUE TITLE
Addon bars (horizontal and vertical) are white with Firefox Alpenglow lw-theme

### ISSUE THREAD

**Issue by Janaue** [Aris-t2/CustomCSSforFx#676]
I use firefox ESR 128.2.0esr and I load the two scripts ./CustomJSforFx-master/scripts/addonbar.uc.js and ./CustomJSforFx-master/scripts/addonbar_vertical.uc.js to get addon bars, but with the official purple theme Firefox Alpenglow 1.4, the two bars are very white. Is it possible to change this in the userChrome.css ?

for instance to change the tab bar I use this 
#TabsToolbar{background-color: #101010 !important}

So i hope i can do the same for the two addon bars. I have also the same problem wit the sidebar. It's very white so I would like to change it's color in the CSS.

**Comment by Aris-t2** [comment]
Alpenglow 1.4 does not offer any colors there, but you can change that manually by editing `addonbar.uc.js` and `addonbar_vertical.uc.js` files. Replace the mentioned code like this:

```css
:root[lwtheme] #addonbar {
  background: var(--lwt-accent-color) !important;
 }
```
-->
```css
:root[lwtheme] #addonbar {
  background: purple !important;
 }
```

```css
:root[lwtheme] #addonbar_v {
   background: var(--lwt-accent-color) !important;
}
```
-->
```css
:root[lwtheme] #addonbar_v {
   background: purple  !important;
}
```
