### ISSUE TITLE
alltabs button is back with Firefox 131

### ISSUE THREAD

**Issue by gabri25ele** [Aris-t2/CustomCSSforFx#682]
**Firefox 131**
alltabs button changed and back in the bar

![sshot-1](https://github.com/user-attachments/assets/18c073f1-0001-415d-9616-436e3935ab68)

tried the new custom_css_for_fx_v4.5.6 but it doesn't seem to hide and shows when needed
only **always_hidden** works

**Comment by Aris-t2** [comment]
`alltabs_button_always_hidden.css` still works in Fx 131-133. Its ID did not change.

**Comment by gabri25ele** [comment]
> `alltabs_button_always_hidden.css` still works in Fx 131-133. Its ID did not change.
> 
> Not sure what you mean with "when its needed". Is it visible/hidden the way you need it without any custom CSS?

Didn't it once appear only when it was needed?
with a certain number of tabs? I think there was this option

**Comment by Aris-t2** [comment]
Maybe yes.

This code can make the alltabs button to only in browsers overflow mode. I guess this makes sense, right?

```css
#tabbrowser-tabs:not([overflow]) ~ #alltabs-button{
  visibility: collapse !important;
  display: none !important;
}
```
