### ISSUE TITLE
How would I highlight the currently selected tab

### ISSUE THREAD

**Issue by patfla** [Aris-t2/CustomCSSforFx#699]
How would I highlight the currently selected tab?  I was able to customize a previous userChrome.css project to change current-selected to a shade of orange with the following code.

```
.tabbrowser-tab[selected] .tab-content {
  /* background-color: #33cc33 !important; } */
  background-color: #ffa31a !important; }

```

Have fiddled with getting the same result in my installation of CustomCSSforFx, but this project is much more complex than the previous one.

**Comment by Aris-t2** [comment]
In general without any other code like the one from this project present, this will do the job:

```css
.tabbrowser-tab[selected] .tab-background {
  background-color: #ffa31a !important;
}
```

If you want to override this projects default setup with classic squared tabs:

```css
#TabsToolbar #tabbrowser-tabs .tabbrowser-tab[selected] .tab-content {
  background: #ffa31a !important;
}
```
