### ISSUE TITLE
Icon is not displayed on mouseover [tab_audio_icon.css]

### ISSUE THREAD

**Issue by Hobbix** [Aris-t2/CustomCSSforFx#700]
Firefox 133. Icon is not displayed on mouseover for tab_audio_icon.css.

**Comment by jack-ii** [comment]
Same problem for me, I deactivated it last week but hope it can come back, the default solution is not cool.

**Comment by Aris-t2** [comment]
Open `tab_audio_icon.css` and change the code to

```css
.tab-icon-stack:is([muted],[soundplaying],[activemedia-blocked]){
  grid-template-areas: "a s";
}
.tab-icon-overlay:is([muted],[soundplaying],[activemedia-blocked]) {
  grid-area: s;
}
.tab-icon-overlay {
  padding: 0 !important;
  border: 0 !important;
}
.tab-icon-stack:is([soundplaying], [muted], [activemedia-blocked]) > * {
  opacity: 1 !important;
}
```
