### ISSUE TITLE
[Firefox133][Photon tabs] tabs toolbar height

### ISSUE THREAD

**Issue by gabri25ele** [Aris-t2/CustomCSSforFx#706]
dear aris, 
I really don't know where to go to look at this. 
I just updated to **133** and the **height** of the tab bar has changed as you can see from the pictures

![133](https://github.com/user-attachments/assets/f8b5cae2-d2d6-47e2-841e-453b8084fe15)

previously it was

![132](https://github.com/user-attachments/assets/8ba9861e-4ffe-4fe4-b1ec-6d29ae928d10)

and the basic one is always the same

![132 basse](https://github.com/user-attachments/assets/2f65235a-cb25-45cc-a09a-216b7c7bbc05)

could this be it?

_[GENERAL]
Firefox 133+ had some code changes requiring the addition of versioned files again not just for testing purposes.
Make sure to use those files (_fx133.css) on Fx 133+ and not to use them on Firefox 132 and below._

update to custom_css_for_fx_v4.6.0_v3
but everything remained the same

**Comment by Aris-t2** [comment]
Add this to your code:

```css
/* Fx 133+ */
#tabbrowser-tabs[orient="horizontal"] .tab-background,
#tabbrowser-tabs[orient="horizontal"] {
  min-height: unset !important;
}
```
