### ISSUE TITLE
Enable Tab Close Icon On Hover for Non-Active Tab

### ISSUE THREAD

**Issue by ChasCB** [Aris-t2/CustomCSSforFx#710]
At present I use tab_close_on_active_tab_only.css

Is possible to css code so that the close icon appears on non-active Tabs on hover and also have the close icon permanent on active tab at the same time ?

Just an idea

Cheers

**Comment by Aris-t2** [comment]
We can base the code on tab_close_show_on_hover_only.css.
This will do what you suggested:

```css
:is(#TabsToolbar,#vertical-tabs) #tabbrowser-tabs .tabbrowser-tab:not([selected],[pinned],:hover) .tab-close-button {
  visibility: collapse !important;
  display: none !important;
}

:is(#TabsToolbar,#vertical-tabs) #tabbrowser-tabs .tabbrowser-tab:not([selected],[pinned]):hover .tab-close-button {
  visibility: visible !important;
  display: block !important;
}
```
