### ISSUE TITLE
[Firefox default dark theme] Active tab color contrast lost in 4.5.2+

### ISSUE THREAD

**Issue by gashtal** [Aris-t2/CustomCSSforFx#714]
1. Does the issue occur without any files inside /chrome/ folder?
N/A

2. Issue description, userChrome.css/userContent.css 'settings' the issue occurs with and steps to reproduce the issue:
Active tab color contrast lost in 4.5.2 for classic squared tabs australized (@import "./css/tabs/classic_squared_tabs_australized.css") in dark mode. Screenshots below show the problem:

4.4.9:
![4 4 9](https://github.com/user-attachments/assets/6e24260d-69a4-474f-92ec-857546bb66ac)

4.5.2 and newer:
![Latest](https://github.com/user-attachments/assets/585676f0-c430-40e4-bde2-6a0b96f47cad)

It is now very difficult to tell the active tab apart from other tabs in dark mode. I tested by overwriting "classic_squared_tabs_australized.css" from every version the file has been updated in, until I narrowed down the source of the issue to the changes introduced in v4.5.2:
https://github.com/Aris-t2/CustomCSSforFx/commit/6bc9e1dc4bca950111cb0120eb9e5b3d08d16158#diff-b3ea24c2e10225b911306d022138a2f3fbc7281c2df846ed94d2b16869e131f0
Problem is reproducible in latest v4.6.2, as well.

3. Does the issue occur with the most recent version of CustomCSSforFx (release/test/dev build)?
Yes.

4. Screenshots showing the issue (drag & drop images into this post):
Provided above.

5. System information
- OS & OS version: Windows 11 22H2
- DPI/HiDPI/scaling value, if not 100% (e.g. 125%, 150%...): 100% 
- Firefox version: 133.0
- Firefox theme (e.g. default, build in light/dark, external theme + link): Dark

**Comment by Aris-t2** [comment]
Actually this works as intended. The screenshot from 4.4.9 shows the wrong color.

**Comment by gashtal** [comment]
How is that the case? The color contrast in all older versions of this project was the same as the 4.4.9 screenshot. It was "changed" in 4.5.2. Also, the color difference for the default Firefox tabs is the same as 4.4.9:

![{18EA18AD-8410-420A-A7F2-4DC1E6A08663}](https://github.com/user-attachments/assets/271fcf9b-87d1-40d5-b8e8-7efae9ba412b)

Moreover, I think the screenshots clearly show that the difference between active and inactive tabs was much clearer in 4.4.9, while the change in 4.5.2 has now made it nearly impossible to tell active and inactive tabs apart. Note that the point of Dark Mode is to minimize the amount of white light coming out of the monitor, and having to crank up the monitor contrast to be able to tell them apart defeats the point of using Dark Mode in the first place.

**Comment by Aris-t2** [comment]
The goal for for classic squared tabs was always having active tabs color to match navigation toolbars color.

![image](https://github.com/user-attachments/assets/22babe04-c251-4fa6-a506-640414489790)
![image](https://github.com/user-attachments/assets/7e2a33a6-ecbd-4057-95be-0f5946505bce)
![image](https://github.com/user-attachments/assets/e22ff129-7b93-4466-b7a8-9093234d17d6)
![image](https://github.com/user-attachments/assets/b916c148-670f-4834-a78b-b4c09a5e9175)

You can of course override active tabs color using something like this in `my_userChrome.css` file:
```css
#TabsToolbar #tabbrowser-tabs .tabbrowser-tab[selected] .tab-content {
  background: linear-gradient(to bottom,lightgrey,grey) !important;
}
```
![image](https://github.com/user-attachments/assets/4c268f31-901f-4a5c-b9c4-a5bbfffdf48f)

```css
#TabsToolbar #tabbrowser-tabs .tabbrowser-tab[selected] .tab-content {
  background: linear-gradient(to bottom,grey,grey) !important;
}
```
![image](https://github.com/user-attachments/assets/5dbfa363-e4ed-4701-8a58-a9fa2e6eff64)

**Comment by gashtal** [comment]
@Aris-t2 Thank you for the clarification. I do see your point; however, I think the better way to correct this problem would have been to change the color of the navigation toolbar, rather than changing the color of the active tabs, which has now resulted in lowered or even opposite contrast between active and inactive tabs. Due to the specific design of the default Firefox tabs, maybe the default Dark theme of Firefox cannot be used as a good reference for this particular scenario. However, we can still use other browsers as reference, here:

Chrome:
![image](https://github.com/user-attachments/assets/a097907c-b190-4dc8-9660-664d3e0a5fe9)

Edge:
![image](https://github.com/user-attachments/assets/9eb410b9-ada8-4b15-8928-d3207a436198)

Vivaldi:
![{355903ED-911B-4ED6-A231-0CBC2F98F382}](https://github.com/user-attachments/assets/f9aa35cd-fb0e-4056-91ee-080370f9597e)

As can be seen, every other major browser out there uses lighter color and clear contrast for active tabs, and the navigation bar uses the same color and contrast to match; this is probably one of the few things that every major browser out there does in such a similar fashion. I do certainly understand that CustomCSSforFx provides the flexibility to the users to modify everything as they see fit; however, I think it makes sense for the default behavior to match that of common designs out there.

**Comment by Aris-t2** [comment]
I don't disagree, it all makes sense. However tab colors try to match toolbar colors set by Firefox. Once Mozilla decides to change default dark themes toolbar color, this projects files should adopt automatically.

You can try this lwtheme, it goes into the direction other browsers do: https://addons.mozilla.org/en-US/firefox/addon/blackqwreqwrqw/

**Comment by gashtal** [comment]
Thank you for the response. I highly doubt Mozilla would change their toolbar color since in their current deign, the active tab is not "connected" to the toolbar and the toolbar, the active tab, and inactive tabs, use three different colors so that the color difference creates a border between the active tab and the address field:

![image](https://github.com/user-attachments/assets/64b4ff24-8e10-434a-bb24-0ab054bb1be0)

I will check out the theme you mentioned.

**Comment by Aris-t2** [comment]
For your setup with classic australis tabs and dark theme you could try to add this to your `my_userChrome.css`:

```css
:root[lwtheme] {
  --tab-selected-bgcolor: #52525e !important;
}

:root[lwtheme] #tabbrowser-tabs:not([movingtab]) > #tabbrowser-arrowscrollbox > .tabbrowser-tab > .tab-stack > .tab-background:is([selected],[multiselected]) {
  background-color: unset !important;
}

:root[lwtheme] #nav-bar,
:root[lwtheme] #PersonalToolbar,
:root[lwtheme] #TabsToolbar #tabbrowser-tabs .tabbrowser-tab:is([selected],[multiselected]) .tab-content {
  background-color: unset !important;
  background-image: unset !important;
  box-shadow: unset !important;
  background: var(--tab-selected-bgcolor) !important;
}
```

![image](https://github.com/user-attachments/assets/6a68d259-d5c5-4173-a13f-9fc55938ca4d)
