### ISSUE TITLE
Private Browser indicator now adds extra toolbar below Tabbar

### ISSUE THREAD

**Issue by ChasCB** [Aris-t2/CustomCSSforFx#717]
Fx133 has added an extra bar below Tab Bar when in Private Browsing mode.
This extra bar pushes the Tab bar up and over the Bookmark bar.
I have never used css for Private Browsing alterations as I have needed to and this new behaviour is not wanted.
Using Aris.t2 private_mode_indicator_hidden.css does not rectify this Fx133 behaviour.
I would like to get rid of this in its entirety.
Perhaps a new css file or an alteration to the private_mode_indicator_hidden.css code ??

![Screen Shot 2024-12-03 at 15 19 36](https://github.com/user-attachments/assets/ef41c0d3-96e6-47f6-8347-a3c14d2bdf4e)

Fx133
mac OS

Cheers 🍷

**Comment by Aris-t2** [comment]
Not sure why `private_mode_indicator_hidden.css` does not solve your issue.
The file takes care of the current private mode indicators.

```css
#TabsToolbar :is(#private-browsing-indicator-with-label,.private-browsing-indicator-with-label, .private-browsing-indicator-icon,.private-browsing-indicator-label) {
  display: none !important;
}
```

But even, if the option is not active, the toolbar looks like this in private mode:
![image](https://github.com/user-attachments/assets/fb9a1b36-5428-4673-95bf-9a011bc8b5fa)
