### ISSUE TITLE
[Default / photon tabs - no tab line option] Facebook tab line is still present

### ISSUE THREAD

**Issue by MJ1979** [Aris-t2/CustomCSSforFx#724]
userChrome.css settings
1. Does the issue occur without any files inside /chrome/ folder?
No.

2. Issue description, userChrome.css/userContent.css 'settings' the issue occurs with and steps to reproduce the issue:
 
DEFAULT TABS - tab line is set to be active, per the default setting of userChrome.css file.
/* @import "./css/tabs/default_tabs_no_tab_line.css"; /**/

The issue is that Facebook always adds black tab line for each of the opened Facebook tabs. The black line is always visible, even thou the tab is not active.
When the tab is active it doesn't display the default blue line for the active tab, but the black instead... 

3. Does the issue occur with the most recent version of CustomCSSforFx (release/test/dev build)?
Yes, I'm using custom_css_for_fx_v4.6.9

4. Screenshots showing the issue (drag & drop images into this post):
Screenshot 1...
![2024-12-24_103554](https://github.com/user-attachments/assets/f0e41eda-72df-4366-870e-6076d5dee5e4)

Screenshot 2...
![2024-12-24_103622](https://github.com/user-attachments/assets/d0403716-0a05-4677-962d-1e8f7d36dd31)

5. System information
- OS & OS version: Win 10x64
- DPI/HiDPI/scaling value, if not 100% (e.g. 125%, 150%...): 100
- Firefox version: 133.0.3
- Firefox theme (e.g. default, build in light/dark, external theme + link): Default (Light_Green 2.0 by Saifyks)
I tried other themes and the issue remains the same...
- (https://addons.mozilla.org/en-US/firefox/user/5284319/?utm_source=firefox-browser&utm_medium=firefox-browser&utm_content=addons-manager-user-profile-link)

Thank you for your hard work and all the best...
M.J.

**Comment by Aris-t2** [comment]
Test this an report, if something changed:

```css
.tab-group-line,
.tab-context-line {
  display: none !important;
}
```

**Comment by MJ1979** [comment]
I don't know if I'm doing it correctly but I pasted in the text as in screenshot below, saved it, restarted Firefox and the result is that no tab line is visible at all....

![tab settings](https://github.com/user-attachments/assets/b3f56b5d-90b2-4ab6-89d2-e71f51e534a7)

**Comment by Aris-t2** [comment]
The code should be placed at the bottom/end of the file.

Not sure what else can cause this for "Facebook" tabs. I do not have an account there.

**Comment by MJ1979** [comment]
I didn't know... I tried it again as shown in screenshot below and the result is the same - no tab line is visible at all.... 
Thank you for trying and for the great work... 

![2024-12-25_153128](https://github.com/user-attachments/assets/130fa9b3-7586-4837-bc6f-cb2b8d08597b)

**Comment by Aris-t2** [comment]
If your goal is to only hide Facebook tab line, but keep the other one, the above code won't help.

Try this:

```css
.tabbrowser-tab:is([label="Facebook"],[label^="Facebook"],[label~="Facebook"]) :is(.tab-group-line,.tab-context-line) {
  background-color: transparent !important;
}

.tabbrowser-tab[selected]:is([label="Facebook"],[label^="Facebook"],[label~="Facebook"]) :is(.tab-group-line,.tab-context-line) {
  background-color: Highlight !important;
}
```
