### ISSUE TITLE
Custom Drop down menu Bookmarks background shade

### ISSUE THREAD

**Issue by 55trucker** [Aris-t2/CustomCSSforFx#727]
Aris:

looking thru your past versions is there a custom style to alter the oem background shade of each of the highlighted bookmarks menu & the drop down menus when hovered over?
The current background shade is dull gray, it's almost the same shade as the default menu color, hard to pick up the highlighted selection when hovered over.

I was trying find something to make the highlighted menus the same shade as the active tabs like this.....

![Pale Moon web browser photo](https://github.com/user-attachments/assets/81347713-a960-4cd7-8d76-61e0f46051c4)

my Firefox browser looks like this.....
 
![Firefox current browser photo](https://github.com/user-attachments/assets/46e5bbf7-dc73-49b4-9661-ac8ac1354fe5)

**Comment by Aris-t2** [comment]
You are looking for this:

```css
#main-menubar > menu {
  border: 1px solid transparent !important;
}

#main-menubar > menu:hover {
  background-image: linear-gradient(#99FFFF,#00CCFF,#99FFFF) !important;
  border: 1px solid #4379bd !important;
  border-radius: 3px !important;
  box-shadow:
	0 0 2px rgba(255, 255, 255, 0.4) inset,
	0 4px 6px rgba(255, 255, 255, 0.4) inset,
	0 11px 0 -2px rgba(255, 255, 255, 0.2) inset,
	0 13px 8px rgba(150, 150, 150, 0.3) inset, 
	1px 2px 4px rgba(0, 0, 0, 0.3) !important;
}
```
