### ISSUE TITLE
thanks i reapplyed first code and it worked

### ISSUE THREAD

**Issue by trofey** [Aris-t2/CustomCSSforFx#730]
thanks i reapplyed first code and it worked

_Originally posted by @trophhy in https://github.com/Aris-t2/CustomCSSforFx/discussions/606#discussioncomment-11565426_

but if i drag tab it doesnt scroll, how to fix it?

**Comment by Aris-t2** [comment]
You can not drag&drop tabs to either end of the tab bar, if the buttons are gone, because those buttons are essential for scrolling to work:

Instead of remove those buttons with

```css
#scrollbutton-up[part="scrollbutton-up"][tooltiptext],
#scrollbutton-down[part="scrollbutton-down"][tooltiptext] {
  display: none !important;
}
```

try to hide them with this:

```css
#scrollbutton-up[part="scrollbutton-up"][tooltiptext],
#scrollbutton-down[part="scrollbutton-down"][tooltiptext] {
  min-width: 0.1px !important;
  width: 0.1px !important;
  max-width: 0.1px !important;
  opacity: 0 !important;
}
```

Button will be gone, but scrolling will work.
