### ISSUE TITLE
Bookmarks show on hover not working (4.7.0)

### ISSUE THREAD

**Issue by Gnome16** [Aris-t2/CustomCSSforFx#740]
### Guidelines

- [x] I have read [how to report a new issue](https://github.com/Aris-t2/CustomCSSforFx/issues/4)
- [x] I have used the [latest release](https://github.com/Aris-t2/CustomCSSforFx/releases/latest)
- [x] I have set the `toolkit.legacyUserProfileCustomizations.stylesheets` in `about:config` to `true`

### Does the issue occur without any files inside /chrome/ folder?

No, because show on hover doesn't happen

### Description of the Issue

Turning on Bookmarks sidebar show on hover results in a blank panel appearing on the left, not the bookmarks.

### Issue description, userChrome.css/userContent.css 'settings' the issue occurs with and steps to reproduce the issue

Copy 4.7.0 into firefox/chrome and then change only the line in userChrome.css to turn on:

@import "./css/generalui/sidebar_show_on_hover.css"; /**/

### Does the issue occur with the most recent version of CustomCSSforFx (release/test/dev build)?

Yes, with the latest release

### System information

Windows 10 Home.
Firefox 136.0

**Comment by Aris-t2** [comment]
Mozilla introduced a new sidebar and the old code can not help anymore.

Use this as a workaround. A will be visible, that cannot be hidden, width "--sidebar-hover-width".

```css
:root{
  --sidebar-hover-width: 8px;
  --sidebar-visible-width: 300px;
}

#sidebar-main{
  display: none !important;
}

#sidebar-box,
#sidebar-box #sidebar {
  padding: 0 !important;
  margin: 0 !important;
  opacity: 0 !important;
}

#sidebar-box:hover,
#sidebar-box:hover #sidebar {
  opacity: 1.0 !important;
}

#sidebar-box {
  min-width: var(--sidebar-hover-width) !important;
  width: var(--sidebar-hover-width) !important;
  max-width: var(--sidebar-hover-width) !important;
}

#sidebar-box:hover {
  min-width: var(--sidebar-visible-width) !important;
  width: var(--sidebar-visible-width) !important;
  max-width: var(--sidebar-visible-width) !important;
}
```
