### ISSUE TITLE
Add some `padding-inline-end` to `menuitem:not([acceltext])`

### ISSUE THREAD

**Issue by CT-ABT** [Aris-t2/CustomCSSforFx#760]
I would suggest to add something like the following
```css
menuitem:not([acceltext]) {
	padding-inline-end: 16px !important;
}
```
to make the right side of some menus as follows look better on version 139 and above:

![Image](https://github.com/user-attachments/assets/10d2cb5a-f320-45a6-b712-7b3545db8f46)

Otherwise the right-ends of these menu’s text would be way too close to the right border. The exact value of `padding-inline-end` to add in the above sample, however, was just a quick example of mine to show the effect, not necessarily the best practice.

**Comment by CT-ABT** [comment]
And maybe
```css
:is(menu, menuitem) > image.menu-icon {
	margin-right: 6px !important;
}
```
please, currently the space between the icons and the texts are too small and therefore the left sides of the texts of the items with and without icons are not aligned. Please see the attached image as a demo for added `margin-right` to `:is(menu, menuitem) > image.menu-icon`s.

![Image](https://github.com/user-attachments/assets/2b6ed0c0-7ed6-47a8-9916-a2f6e30ae07a)
