### ISSUE TITLE
[default browser tabs + pinned tabs] Gap between tabs and toolbar with `tabs_multiple_lines.css` 

### ISSUE THREAD

**Issue by kevinptt0323** [Aris-t2/CustomCSSforFx#77]
**What should have happened instead?**

A little gap between tabs and toolbars if `tabs_multiple_lines.css` is enabled.

I guess the height should be `25px` [here](https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/css/tabs/tabs_multiple_lines.css#L60).

**Steps to reproduce the issue?**

1. Enable `./css/tabs/tabs_multiple_lines.css`
2. Open a new window with tabs.

**Screenshots (drag and drop images into this post)**

![1](https://user-images.githubusercontent.com/5292982/33407645-4b5b449e-d5ad-11e7-9d99-c1caa0e34aa0.png)

System information
* OS: Windows
* OS version: 10
* OS theme: Default
* DPI / HiDPI resolution: 1920x1080
* Firefox version: 57.0
* Firefox theme: Default
* Settings this issue occurs with:

**Comment by Aris-t2** [comment]
I will fix this on next update.

**Comment by stonecrusher** [comment]
It might make sense to put the height into a css variable to make it easy for people to cusomize their tab height.
To make it work for smaller heights we need to set the internal variable `--tab-min-height:0 !important;`.

---

    /* titlebar button height */
    toolbarbutton.titlebar-button {
      min-height: 31px !important;
    }

`.titlebar-button` has a different height value (although we can solve that by using `calc()` ), but in my tests it didn't do anything. Maybe it's for another OS? I'm using Windows 8.1. I stripped it out completely.

I also still have a 1px gap (looks like even below 1px compared to 1px borders) and will try to fix this in the afternoon.

So far this works well for me:

	:root{
		--height:25px;
		--right-end:50px; /* default: 41px */
                              /* I put some space for the newtab-button in first row. 
                                 This depends on how many pinned tabs you have. */
		--tab-min-height:0 !important;
	}

	/* titlebar buttons */
	#titlebar-buttonbox {
	  vertical-align: top !important;
	  display: block !important;
	}

	.tabbrowser-arrowscrollbox scrollbox {
	  overflow: visible !important;
	}

	.tabbrowser-arrowscrollbox scrollbox > box {
	  display: block !important;
	}

	/* tabs end position */
	.tabbrowser-tabs {
	  -moz-margin-end: var(--right-end) !important;
	}

	/* tab size */
	.tabbrowser-tab {
	  min-height: var(--height) !important;
	  max-height: var(--height) !important;
	  vertical-align: top !important;
	  -moz-box-sizing: border-box !important;
	}

	/* 'new tab' tab size */
	.tabs-newtab-button {
	  vertical-align: bottom !important;
	  height: var(--height) !important;
	}

**Comment by Aris-t2** [comment]
I reused the code from here https://github.com/Aris-t2/CustomCSSforFx/issues/39

Maybe
```css
toolbarbutton.titlebar-button {
  min-height: 31px !important;
}
```
was required there. I don't see any difference without it.

`display: block !important;` requires the "right-end". Removing it and the right end won't be needed at all.

```css
#titlebar-buttonbox {
  vertical-align: top !important;
  display: block !important;
}
```

Further more tab height is now controlled by the global variable `--tab-min-height`. It uses default values for default tabs and a "custom" value set by this projects smaller squared tabs. Everything happens automatically, so no file tweaking is necessary anymore.

Once I ran more tests, I will upload a new release version.

**Comment by Aris-t2** [comment]
Check v1.4.3.

**Comment by stonecrusher** [comment]
Uhm, v1.4.3 is a step back for me.
I don't have classic square tabs activated and you can't use it "standalone" anymore.

Even if I add
```CSS
:root {
  --tab-min-height:20px !important;
  --tab-min-height_ntml: 21px !important;
}
```

I then have the problem that the tabs won't go far to the right (playing around with `browser.tabs.tabMinWidth`) and a big gap between the tabs and the location bar.

For now I'll stick to the version I posted above.

**Comment by Aris-t2** [comment]
Strange, tabs stop for me right before caption buttons (min/max/close) and creata a new line. 
Tested on Windows 7/8/10. The gap at the right must be there, if tabs toolbar are on top and "in titlebar" or tabs will overlap with caption buttons like happened before 1.4.3.

![01](https://user-images.githubusercontent.com/6013569/33460868-6ed1041c-d630-11e7-95e0-d4c80fef691a.png)

![04](https://user-images.githubusercontent.com/6013569/33460958-ba7bb54c-d630-11e7-849e-c3c1b1d8d472.png)


This should be equal to previous "stand-alone" with the older values:

```
:root {
  --tab-min-height: 26px !important;
  --tab-min-height_ntml: 27px !important;
}
```

**Comment by stonecrusher** [comment]
Sorry, I couldn't provide a screenshots before because there would have been too much to censor (not what you think...)

Now from virtual machine:
<details>
<summary>code before</summary>

```CSS
:root {
	--height:25px;
	--right-end:50px; /* default: 41px */
                          /* I put some space for the newtab-button in first row. 
                             This depends on how many pinned tabs you have. */
	--tab-min-height:0 !important;
}

/* titlebar buttons */
#titlebar-buttonbox {
  vertical-align: top !important;
  display: block !important;
}

.tabbrowser-arrowscrollbox scrollbox {
  overflow: visible !important;
}

.tabbrowser-arrowscrollbox scrollbox > box {
  display: block !important;
}

/* tabs end position */
.tabbrowser-tabs {
  -moz-margin-end: var(--right-end) !important;
}

/* tab size */
.tabbrowser-tab {
  min-height: var(--height) !important;
  max-height: var(--height) !important;
  vertical-align: top !important;
  -moz-box-sizing: border-box !important;
}

/* 'new tab' tab size */
.tabs-newtab-button {
  vertical-align: bottom !important;
  height: var(--height) !important;
}
```
</details>

![single_before](https://user-images.githubusercontent.com/1388389/33481669-d7c05a08-d695-11e7-8803-e4300f9c7191.png)

![multi_before](https://user-images.githubusercontent.com/1388389/33481676-df565e66-d695-11e7-893c-bd8832b5bf86.png)


<details>
<summary>code after</summary>

```CSS

/* 'new tab' tab size */
:root {
  --tab-min-height: 25px !important;
  --tab-min-height_ntml: 25px !important; /* will cause the 1px glitch, better use 26px too */
}

/* titlebar buttons */
#titlebar-buttonbox {
  vertical-align: top !important;
}

.tabbrowser-arrowscrollbox scrollbox {
  overflow: visible !important;
}

.tabbrowser-arrowscrollbox scrollbox > box {
  display: block !important;
}

/* titlebar button height */
/*toolbarbutton.titlebar-button {
  min-height: 31px !important;
}*/

/* tab size */
.tabbrowser-tab[pinned] {
  min-height: var(--tab-min-height) !important;
}

.tabbrowser-tab:not([pinned]) {
  min-height: var(--tab-min-height) !important;
}

.tabbrowser-tabs .tabbrowser-tab {
  vertical-align: top !important;
  -moz-box-sizing: border-box !important;
  min-height: var(--tab-min-height) !important;
}

/* 'new tab' tab size */
.tabs-newtab-button {
  vertical-align: bottom !important;
  min-height: var(--tab-min-height_ntml) !important;
}


/* Button for scrolling tabs to the left */
.scrollbutton-up ,
.scrollbutton-down,
#TabsToolbar #alltabs-button{
  display: none;
}
```
</details>

![single_after](https://user-images.githubusercontent.com/1388389/33481712-05d80ad0-d696-11e7-8385-6ea87030de21.png)

![multi_after](https://user-images.githubusercontent.com/1388389/33481722-0a7f9698-d696-11e7-963b-dabef9d656f8.png)

**Comment by Aris-t2** [comment]
Tab gap is caused by pinned tabs.

Test this code:
```css
/* 'new tab' tab size */
:root {
  --tab-min-height_ntml: var(--tab-min-height);
  --pinned_tab-min-height: calc(var(--tab-min-height) - 4px );
}

/* titlebar buttons */
#titlebar-buttonbox {
  vertical-align: top !important;
}

.tabbrowser-arrowscrollbox scrollbox {
  overflow: visible !important;
}

.tabbrowser-arrowscrollbox scrollbox > box {
  display: block !important;
}

/* titlebar button height */
/*toolbarbutton.titlebar-button {
  min-height: 31px !important;
}*/

/* tab size */
.tabbrowser-tab[pinned] {
  min-height: var(--pinned_tab-min-height) !important;
}

.tabbrowser-tab:not([pinned]) {
  min-height: var(--tab-min-height) !important;
}

.tabbrowser-tabs .tabbrowser-tab {
  vertical-align: top !important;
  -moz-box-sizing: border-box !important;
  min-height: var(--tab-min-height) !important;
}

/* 'new tab' tab size */
.tabs-newtab-button {
  vertical-align: bottom !important;
  min-height: var(--tab-min-height_ntml) !important;
}


/* Button for scrolling tabs to the left */
.scrollbutton-up ,
.scrollbutton-down,
#TabsToolbar #alltabs-button{
  display: none;
}
```

It misses negative right margin to not overlap with caption buttons on other OSs

**Comment by stonecrusher** [comment]
> Tab gap is caused by pinned tabs.

Good to know. For me it's still a bit obscure.

> It misses negative right margin to not overlap with caption buttons on other OSs

So you could leave it in (default: outcommented) to make it easy to adjust to your OS?

Not sure, if I'm doing this right, but the new code didn't change the gap:

![screenshot 11](https://user-images.githubusercontent.com/1388389/33490042-10a0fe0c-d6b6-11e7-9bde-ac681604f303.png)
<details>
<summary>The code I used</summary>

```CSS
:root {
  --tab-min-height: 25px !important;  /* this is the only change compared to your post */
  --tab-min-height_ntml: var(--tab-min-height);
  --mlt_pinned_tab-min-height: calc(var(--tab-min-height) - 4px);
}

/* titlebar buttons */
#titlebar-buttonbox {
  vertical-align: top !important;
}

.tabbrowser-arrowscrollbox scrollbox {
  overflow: visible !important;
}

.tabbrowser-arrowscrollbox scrollbox > box {
  display: block !important;
}

/* titlebar button height */
/*toolbarbutton.titlebar-button {
  min-height: 31px !important;
}*/

/* tab size */
.tabbrowser-tab[pinned] {
  min-height: var(--mlt_pinned_tab-min-height) !important;
}

.tabbrowser-tab:not([pinned]) {
  min-height: var(--tab-min-height) !important;
}

.tabbrowser-tabs .tabbrowser-tab {
  vertical-align: top !important;
  -moz-box-sizing: border-box !important;
  min-height: var(--tab-min-height) !important;
}

/* 'new tab' tab size */
.tabs-newtab-button {
  vertical-align: bottom !important;
  min-height: var(--tab-min-height_ntml) !important;
}


/* Button for scrolling tabs to the left */
.scrollbutton-up ,
.scrollbutton-down,
#TabsToolbar #alltabs-button{
  display: none;
}
```
</details>
</br>
   
Before we waste too much time on that: Is this the version which only works up to FF59 and then breaks? I think I've read something like this somewhere.
I mean I personally am already happy with the old code I posted [above](https://github.com/Aris-t2/CustomCSSforFx/issues/77#issuecomment-348475963).

**Comment by Aris-t2** [comment]
The code should work in general. I only previously wrote "up to Fx59", because that was and still is the latest Nightly version.

I'm fine with the current version and if yours is working for you the way you like it, its fine with me too. One last question. Can you provide a screenshot of an active/selected pinned tab when using your code?

**Comment by stonecrusher** [comment]
> The code should work in general. 

I don't use the default settings of this project's userChrome.css but disabled all and enable only what I want. That's what I meant by "standalone option" --> The same as "in general"?

I didn't see notes on dependencies in the provided userChrome.css

To prevent conflicts, maybe just separate the option for tab height (as this is actually just about multiline tabs) so it works for other files of this project, too?
--> Using variables everywhere and a separate tabheight.css to set them

Don't know if it's possible or too complicated.


> Can you provide a screenshot of an active/selected pinned tab when using your code?

Of course, here you are (looks fine to me):

![screenshot 12](https://user-images.githubusercontent.com/1388389/33516128-939d07ee-d76d-11e7-96ad-5d6377a98466.png)


<details><summary>Code</summary>

```CSS
:root{
	--height:25px;
	--right-end:50px; /* default: 41px, I put some space for the newtab-button */
	--tab-min-height:0 !important;
}

/* titlebar buttons */
#titlebar-buttonbox {
  vertical-align: top !important;
  display: block !important;
}

.tabbrowser-arrowscrollbox scrollbox {
  overflow: visible !important;
}

.tabbrowser-arrowscrollbox scrollbox > box {
  display: block !important;
}

/* tabs end position */
.tabbrowser-tabs {
  -moz-margin-end: var(--right-end) !important;
}

/* tab size */
.tabbrowser-tab {
  min-height: var(--height) !important;
  max-height: var(--height) !important;
  vertical-align: top !important;
  -moz-box-sizing: border-box !important;
}

/* 'new tab' tab size */
.tabs-newtab-button {
  vertical-align: bottom !important;
  height: var(--height) !important;
}


/* Button for scrolling tabs to the left */
/* not necessary? */
/*.scrollbutton-up ,
.scrollbutton-down,
#TabsToolbar #alltabs-button{
  display: none;
}/**/
```
</details>

`FF 57.0.1 (x64)`, `Win 8.1`
