### ISSUE TITLE
[Fx57b6] How to override tabs_below_navigation_toolbar.css colors to default.

### ISSUE THREAD

**Issue by MarkRH** [Aris-t2/CustomCSSforFx#8]
Instead of me always commenting out this section:

```css
/*  mrh
#TabsToolbar:not(:-moz-lwtheme){
  border-left: 1px solid #5f7181 !important;
  border-right: 1px solid #5f7181 !important;
  background-image: linear-gradient(#f9f9fa,#f9f9fa) !important;
}

#TabsToolbar:-moz-lwtheme{
  background: rgba(255,255,255,0.4) !important;
}

@media (-moz-os-version: windows-win7),(-moz-os-version: windows-vista) {
  @media all and (-moz-windows-theme:aero) {
	#TabsToolbar:not(:-moz-lwtheme) {
	  background: #dbeaf9 !important;
	}
  }
}
*/
```

What would I need to do keep it at the default colors using a later override? 

I'm using a Windows Classic theme so it looks like this: http://www.markheadrick.com/firefox/firefox57-appearance.jpg

Thanks
(Apparently using backticks doesn't really format it as code here.)

**Comment by Aris-t2** [comment]
You can either add a custom code to userChrome.css or create a CSS file and point to it. Most important thing is your code has to be applied last or at least after default files code.

Try this:

```css
#TabsToolbar:not(:-moz-lwtheme){
  border-left: inherit !important;
  border-right: inherit !important;
  background-image: inherit !important;
}

#TabsToolbar:-moz-lwtheme{
  background: inherit !important;
}

@media (-moz-os-version: windows-win7),(-moz-os-version: windows-vista) {
  @media all and (-moz-windows-theme:aero) {
	#TabsToolbar:not(:-moz-lwtheme) {
	  background: inherit !important;
	}
  }
}
```

Because you are using default Firefox theme and Windows 7s classic OS theme you only have to take care of the first rule "#TabsToolbar:not(:-moz-lwtheme)".
