### ISSUE TITLE
[sidebar minimizer css] Resize sidebar to 0px or 9999px (prepared solution here)

### ISSUE THREAD

**Issue by myBestSoftAndPref** [Aris-t2/CustomCSSforFx#81]
Hi,
this code will let you resize your sidebar (Tree Style Tab panel for example) as you wish.
```css
#sidebar-box {
    overflow: hidden !important; /* fix */
    min-width: 0px !important;
    max-width: 9999px !important;
}
```

**Comment by Aris-t2** [comment]
I will add this to the project.

Only one small change is required to unsure sidebars content enlarges to the full possible width.

```css
#sidebar,
#sidebar-header,
#sidebar-box {
  overflow: hidden !important;
  min-width: 0px !important;
  max-width: 9999px !important;
}
```
