### ISSUE TITLE
[Custom icon sets] Icon for 'new tab' tab

### ISSUE THREAD

**Issue by Speravir** [Aris-t2/CustomCSSforFx#82]
The icon for the new tab button is in FFx 57 only changed in adjustment mode (in German: “Anpassen”). This is quite probably a Firefox bug, but it can easily be worked around:  
In `chrome://browser/skin/browser.css` you can find this code
```css
.tabs-newtab-button
#TabsToolbar > #new-tab-button ,
#TabsToolbar > toolbarpaletteitem > #new-tab-button {
  list-style-image: url(chrome://browser/skin/tabbrowser/newtab.svg);
}
```
In default mode only the class selector `.tabs-newtab-button` is assigned, so this has to be added to all the `icons_custom_icons` style files next to `#new-tab-button`.
