### ISSUE TITLE
New Tab Problem

### ISSUE THREAD

**Issue by samlive9090** [Aris-t2/CustomCSSforFx#86]
New Tab Problem Showing Blank Spaces & Leaving New Tab (+) Icon Far Away From Last Tab.

FF 57.0.2 (64Bit) & 1.4.9.

How to solve this problem ?

![newtab1](https://user-images.githubusercontent.com/25926948/33760813-1131cbd6-dc2d-11e7-9d82-9a6f5060e4f0.png)

![newtab2](https://user-images.githubusercontent.com/25926948/33760980-990e6faa-dc2d-11e7-95ea-abc2bb05ee7b.png)

[userChrome.zip](https://github.com/Aris-t2/CustomCSSforFx/files/1542229/userChrome.zip)

Thanks.

**Comment by Aris-t2** [comment]
This happens, because you have added custom code, that does break tabs btw. tabs toolbar. It has nothing to do with this projects files.

```css
.tabbrowser-tab:not([pinned])
{
  min-width: 74px !important;
  max-width: 78px !important;
}
```

For min width use browsers default settings:
`about:config > browser.tabs.tabMinWidth`

For max width use the file this project provides:
`@import url(./css/tabs/tab_maxwidth.css);`
