### ISSUE TITLE
Favicon Remover For All Tabs

### ISSUE THREAD

**Issue by John0877** [Aris-t2/CustomCSSforFx#98]
I would like to remove favicons altogether but I only see the option for pinned tabs to hide them.

Can I change:[code]
.tabbrowser-tab[pinned] .tab-icon-image:not([src]) {
   visibility: hidden !important;
}

.tabbrowser-tab[pinned] .tab-text {
  display: none !important;
}
[/code]
To this instead:[code]
.tabbrowser-tab .tab-icon-image:not([src]) {
   visibility: hidden !important;
}

Or is there a better way and can it be added to the UserChrome.css maybe?

**Comment by Aris-t2** [comment]
This will hide all tab icon images, but remember tab loading icon uses the same space, what will case tab text  jumps after loading.
```css
.tabbrowser-tab .tab-icon-image {
  visibility: collapse !important;
  display: none !important;
}
```

**Comment by John0877** [comment]
hide all tab icon images

**Comment by Aris-t2** [comment]
The icon is there since years. Before that there was no loading animation on tabs.

Hide both with this:

```css
.tabbrowser-tab .tab-throbber,
.tabbrowser-tab .tab-icon-image{
  display: none !important;
  visibility: collapse !important;
}
```
